### PR TITLE
Fix incorrect text position for UIButton on ARM release

### LINKED ISSUE #1327: hello UI text in button is cropped on phone

### PR DESCRIPTION
**Pull request by aballway**
When a UIImage doesn't exist calling size on it is not guaranteed to return CGSizeZero

Fixes #1327

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/winobjc/1364)

### CODE REVIEW

**Comment by DHowett-MSFT** [comment]
Can you reduce this chang efootprint to only the actually-touched lines?
This file will be churning a lot when ux/uxe merges in, and this would not be a helpful conflict marker location.

**Comment by DHowett-MSFT** [comment]
:shipit:

**Comment by msft-Jeyaram** [comment]
:shipit:

**Comment by jaredhms** [comment]
:shipit:

File: Frameworks/UIKit/UIButton.mm [hunk 1]
```diff
@@ -378,7 +378,7 @@ - (CGRect)imageRectForContentRect:(CGRect)contentRect {
 - (CGRect)titleRectForContentRect:(CGRect)contentRect {
     CGSize titleSize = [self.currentTitle sizeWithFont:self.font];
     CGSize totalSize = titleSize;
-    CGSize imageSize = [self.currentImage size];
+    CGSize imageSize = self.currentImage ? [self.currentImage size] : CGSizeZero;
```
Comment (aballway) [inline Frameworks/UIKit/UIButton.mm]: I'd prefer not to litter this code with comments, since this & similar patterns are common in here.  Yea CGSizeZero := CGSize{0, 0}

File: Frameworks/UIKit/UIButton.mm [hunk 2]
```diff
@@ -345,7 +345,8 @@ - (CGRect)contentRectForBounds:(CGRect)bounds {
 */
 - (CGRect)imageRectForContentRect:(CGRect)contentRect {
     CGSize titleSize = [self.currentTitle sizeWithFont:self.font];
-    CGSize imageSize = { 0 };
+    // TODO  #1365 :: Currently cannot assume getting size from nil will return CGSizeZero
```
Comment (jaredhms) [inline Frameworks/UIKit/UIButton.mm]: Looks good - thanks!
