### PR TITLE
Change NSURLSessionConfiguration initialization to match reference platform

### LINKED ISSUE #776: NSURLSessionConfiguration tests fail on OSX
[----------] 4 tests from NSURLSessionConfiguration
[ RUN      ] NSURLSessionConfiguration.initValues
Foundation/NSURLSessionConfigurationTests.m:26: Failure
Value of: sessionConfiguration.timeoutIntervalForResource
  Actual: 604800
Expected: 7
FAILED: timeoutIntervalForResource should be 7
[  FAILED  ] NSURLSessionConfiguration.initValues (0 ms)
[ RUN      ] NSURLSessionConfiguration.defaultSessionConfiguration
Foundation/NSURLSessionConfigurationTests.m:56: Failure
Value of: sessionConfiguration.TLSMinimumSupportedProtocol
  Actual: 4
Expected: kSSLProtocol3
Which is: 2
FAILED: TLSMinimumSupportedProtocol should be 2
[  FAILED  ] NSURLSessionConfiguration.defaultSessionConfiguration (0 ms)
[ RUN      ] NSURLSessionConfiguration.ephemeralSessionConfiguration
[       OK ] NSURLSessionConfiguration.ephemeralSessionConfiguration (0 ms)
[ RUN      ] NSURLSessionConfiguration.backgroundSessionConfigurationWithIdentifier
Foundation/NSURLSessionConfigurationTests.m:88: Failure
Value of: sessionConfiguration.URLCache != __null
  Actual: false
Expected: true
FAILED: URLCache should be non-null
[  FAILED  ] NSURLSessionConfiguration.backgroundSessionConfigurationWithIdentifier (1 ms)
[----------] 4 tests from NSURLSessionConfiguration (3 ms total)

### PR DESCRIPTION
**Pull request by aballway**
Changes default values to match reference platform:
* timeoutIntervalForResource is in seconds, not days
* Contrary to the documentation, TLSMinimumSupportedProtocol is kTLSProtocol1, rather than KSSLProtocol3
* Background session configurations have no URLCache

Fixes #776

### CODE REVIEW

File: Frameworks/Foundation/NSURLSessionConfiguration.mm [hunk 1]
```diff
@@ -28,7 +28,7 @@ - (instancetype)_initWithSharedDefaults {
     if (self = [super init]) {
         _allowsCellularAccess = YES;
         _timeoutIntervalForRequest = 60;
-        _timeoutIntervalForResource = 7;
+        _timeoutIntervalForResource = 7 * 24 * 60 * 60;
```
Comment (ms-jihua) [inline Frameworks/Foundation/NSURLSessionConfiguration.mm]: >7 * 24 * 60 * 60; [](start = 38, length = 17)

! The default is a whole week? That's rather scary o.o

**Comment by ms-jihua** [comment]
:shipit:

File: Frameworks/Foundation/NSURLSessionConfiguration.mm [hunk 2]
```diff
@@ -41,22 +41,13 @@ - (instancetype)_initWithSharedDefaults {
...
-}
-
 /**
  @Status Interoperable
 */
 - (instancetype)init {
     if (self = [self _initWithSharedDefaults]) {
         _TLSMaximumSupportedProtocol = kTLSProtocol12;
-        _TLSMinimumSupportedProtocol = kSSLProtocol3;
+        _TLSMinimumSupportedProtocol = kTLSProtocol1;
```
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSURLSessionConfiguration.mm]: >kTLSProtocol1 [](start = 39, length = 13)

is this an iOS vs OS X difference? Can you check in the Simulator?

File: Frameworks/Foundation/NSURLSessionConfiguration.mm [hunk 3]
```diff
@@ -65,15 +56,17 @@ - (instancetype)init {
  @Status Interoperable
 */
 - (instancetype)initEphemeralSession {
-    self = [self _initTLSAndCache];
+    if (self = [self init]) {
+        _URLCache = [[NSURLCache sharedURLCache] retain];
```
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSURLSessionConfiguration.mm]: >e sharedURLCache] retain]; [](start = 31, length = 26)

We're retaining this but never releasing it?

File: Frameworks/Foundation/NSURLSessionConfiguration.mm [hunk 4]
```diff
@@ -24,56 +24,43 @@ @interface NSURLSessionConfiguration ()
...
-
-    return self;
-}
-
-- (instancetype)_initTLSAndCache {
-    if (self = [self _initWithSharedDefaults]) {
         _TLSMaximumSupportedProtocol = kTLSProtocol12;
         _TLSMinimumSupportedProtocol = kTLSProtocol1;
-        _URLCache = [[NSURLCache sharedURLCache] retain];
+        //_URLCredentialStorage = [[NSURLCredentialStorage sharedCredentialStorage] retain];
```
Comment (msft-Jeyaram) [inline Frameworks/Foundation/NSURLSessionConfiguration.mm]: >   //_URLCredentialStorage = [[NSURLCredentialStorage sharedCredentialStorage] retain]; [](start = 5, length = 87)

can this be set? given NSURLCredentialStorage is implemented now.

File: Frameworks/Foundation/NSURLSessionConfiguration.mm [hunk 5]
```diff
@@ -24,56 +24,43 @@ @interface NSURLSessionConfiguration ()
...
     return self;
 }
 
 /**
  @Status Interoperable
 */
 - (instancetype)initBackgroundSession:(NSString*)identifier {
-    if (self = [self _initTLSAndCache]) {
+    if (self = [self init]) {
         _identifier = identifier;
```
Comment (msft-Jeyaram) [inline Frameworks/Foundation/NSURLSessionConfiguration.mm]: >identifier [](start = 22, length = 10)

should be copied.

Comment (msft-Jeyaram) [inline Frameworks/Foundation/NSURLSessionConfiguration.mm]: and released.

---
In reply to: [73748509](https://github.com/Microsoft/WinObjC/pull/828#discussion_r73748509) [](ancestors = 73748509)

File: Frameworks/Foundation/NSURLSessionConfiguration.mm [hunk 6]
```diff
@@ -136,4 +123,11 @@ + (NSURLSessionConfiguration*)backgroundSessionConfiguration:(NSString*)identifi
     return [NSURLSessionConfiguration backgroundSessionConfigurationWithIdentifier:identifier];
 }
 
+- (void)dealloc {
+    [_HTTPCookieStorage release];
+    [_URLCache release];
+    [_URLCredentialStorage release];
```
Comment (msft-Jeyaram) [inline Frameworks/Foundation/NSURLSessionConfiguration.mm]: nit: you can wrap them around StrongId

**Comment by msft-Jeyaram** [comment]
:clock1:

File: Frameworks/Foundation/NSURLSessionConfiguration.mm (hunk 2 above)
Comment (aballway) [inline Frameworks/Foundation/NSURLSessionConfiguration.mm]: It is also kTLSProtocol1 on iOS

---
In reply to: [73745172](https://github.com/Microsoft/WinObjC/pull/828#discussion_r73745172) [](ancestors = 73745172)

File: Frameworks/Foundation/NSURLSessionConfiguration.mm (hunk 6 above)
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSURLSessionConfiguration.mm]: I wouldn't use StrongId here. Since they're property getters and setters, you'd need to implement the backing ivar, any atomicity requirements, and the getter/setter yourself.

File: Frameworks/Foundation/NSURLSessionConfiguration.mm [hunk 7]
```diff
@@ -71,7 +71,7 @@ - (instancetype)initBackgroundSession:(NSString*)identifier {
 */
 - (id)copyWithZone:(NSZone*)zone {
     NSURLSessionConfiguration* copy = [[[self class] allocWithZone:zone] init];
-    copy.identifier = _identifier;
+    copy.identifier = [_identifier copy];
```
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSURLSessionConfiguration.mm]: Bad! This is going through the property setter, and the property is declared as taking a copy already.
This will 1) make an unnecessary copy and 2) leak it.

**Comment by aballway** [comment]
ping

**Comment by DHowett-MSFT** [comment]
:shipit:

**Comment by bbowman** [comment]
:shipit:
