### PR TITLE
Fix #2514 by keeping UIActionSheet alive until it's dismissed

### LINKED ISSUE #2514: AV in XamlCatalog's UIActionSheet sample after the switch to Cpp/WinRT
Repro Steps:

1. Launch XamlCatalog.
2. Go into the UIActionSheet scene and click on one of the tests.

0:007:x86> .lastevent
Last event: 5260.413c: Access violation - code c0000005 (first chance)
  debugger time: Thu Apr 13 15:37:46.459 2017 (UTC - 7:00)
0:007:x86> r
eax=000000e0 ebx=1242b1d8 ecx=000000e0 edx=00f8e000 esi=00000000 edi=11cf9e38
eip=02e95d06 esp=0837f664 ebp=0837f678 iopl=0         nv up ei pl nz na po nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00010202
UIKit!XamlControls::XamlContentDialogPressedIndex+0x26:
02e95d06 8b08            mov     ecx,dword ptr [eax]  ds:002b:000000e0=????????
0:007:x86> kn
 # ChildEBP RetAddr  
00 0837f678 02dec5d1 UIKit!XamlControls::XamlContentDialogPressedIndex+0x26 [d:\build\agent9\_work\10\s\frameworks\uikit\xamlcontrols.mm @ 74] 
01 0837f69c 02dec299 UIKit!std::allocator<std::_List_node<std::pair<UUIView * const,UUIViewController *>,void *> >::allocate+0x62e1 [d:\build\agent9\_work\10\s\frameworks\uikit\uiactionsheet.mm @ 255] 
02 0837f6cc 0642373f UIKit!winrt::impl::async_operation_completed_handler<enum winrt::Windows::UI::Xaml::Controls::ContentDialogResult,objcwinrt::impl::callback<,UIActionSheet> >::abi_Invoke+0x49 [d:\build\agent9\_work\10\s\packages\cppwinrt\2017.3.31.1\build\native\include\winrt/internal/../base.h @ 8144] 
03 0837f708 06424b54 windows_ui_xaml!Microsoft::WRL::AsyncBase<Windows::Foundation::IAsyncOperationCompletedHandler<enum Windows::UI::Xaml::Controls::ContentDialogResult>,Microsoft::WRL::Details::Nil,1,Microsoft::WRL::AsyncCausalityOptions<&DirectUI::ContentDialogShowAsyncOperationName,&GUID_CAUSALITY_WINDOWS_PLATFORM_ID,2> >::FireCompletion+0x8f [sdk\inc\wrl\async.h @ 765] 
04 (Inline) -------- windows_ui_xaml!DirectUI::DXamlAsyncBaseImpl<Windows::Foundation::IAsyncOperationCompletedHandler<enum Windows::UI::Xaml::Controls::ContentDialogResult>,Windows::Foundation::IAsyncOperation<enum Windows::UI::Xaml::Controls::ContentDialogResult>,Microsoft::WRL::AsyncCausalityOptions<&DirectUI::ContentDialogShowAsyncOperationName,&GUID_CAUSALITY_WINDOWS_PLATFORM_ID,2>,Microsoft::WRL::Details::Nil,1>::CoreFireCompletionImpl+0x17 [onecoreuap\windows\dxaml\xcp\dxaml\lib\dxamlasyncbase.h @ 82] 
05 (Inline) -------- windows_ui_xaml!DirectUI::ContentDialogShowAsyncOperation::CoreFireCompletion+0x1f [onecoreuap\windows\dxaml\xcp\dxaml\lib\contentdialog_partial.h @ 84] 
06 0837f744 06424e62 windows_ui_xaml!DirectUI::ContentDialog::OnFinishedClosing+0x190 [onecoreuap\windows\dxaml\xcp\dxaml\lib\contentdialog_partial.cpp @ 1716] 
07 0837f758 064240d6 windows_ui_xaml!DirectUI::ContentDialog::OnPopupClosed+0x92 [onecoreuap\windows\dxaml\xcp\dxaml\lib\contentdialog_partial.cpp @ 1666] 
08 0837f79c 05d978ba windows_ui_xaml!DirectUI::ClassMemberEventHandler<DirectUI::ContentDialog,Windows::UI::Xaml::Controls::IContentDialog,Windows::Foundation::IEventHandler<IInspectable *>,IInspectable,IInspectable>::Invoke+0x96 [onecoreuap\windows\dxaml\xcp\dxaml\lib\joltclasses.h @ 661] 
09 0837f7e8 05d97796 windows_ui_xaml!DirectUI::CEventSourceBase<DirectUI::IUntypedEventSource,Windows::Foundation::IEventHandler<IInspectable *>,IInspectable,IInspectable>::Raise+0xa7 [onecoreuap\windows\dxaml\xcp\dxaml\lib\joltclasses.h @ 273] 
0a 0837f810 05d7e3a4 windows_ui_xaml!DirectUI::CEventSourceBase<DirectUI::IUntypedEventSource,Windows::Foundation::IEventHandler<IInspectable *>,IInspectable,IInspectable>::UntypedRaise+0x36 [onecoreuap\windows\dxaml\xcp\dxaml\lib\joltclasses.h @ 246] 
0b 0837f840 05d370fe windows_ui_xaml!DirectUI::DependencyObject::FireEvent+0xc0 [onecoreuap\windows\dxaml\xcp\dxaml\lib\dependencyobject.cpp @ 3324] 
0c 0837f888 05d36cea windows_ui_xaml!DirectUI::DXamlCore::FireEvent+0x24e [onecoreuap\windows\dxaml\xcp\dxaml\lib\dxamlcore.cpp @ 1793] 
0d (Inline) -------- windows_ui_xaml!AgCoreCallbacks::FireEvent+0x22 [onecoreuap\windows\dxaml\xcp\dxaml\lib\fxcallbacks.cpp @ 72] 
0e (Inline) -------- windows_ui_xaml!CFxCallbacks::JoltHelper_FireEvent+0x22 [onecoreuap\windows\dxaml\xcp\dxaml\lib\fxcallbacks.cpp @ 970] 
0f 0837f8b8 05d36bfa windows_ui_xaml!CCoreServices::CLR_FireEvent+0xda [onecoreuap\windows\dxaml\xcp\core\dll\xcpcore.cpp @ 3557] 
10 0837f8d8 05d38274 windows_ui_xaml!CommonBrowserHost::CLR_FireEvent+0x1a [onecoreuap\windows\dxaml\xcp\control\common\shared\commonbrowserhost.hpp @ 755] 
11 0837f93c 05d37cfe windows_ui_xaml!CControlBase::ScriptCallback+0x1f4 [onecoreuap\windows\dxaml\xcp\control\common\shared\controlbase.cpp @ 306] 
12 0837f9bc 05d379ea windows_ui_xaml!CXcpDispatcher::OnScriptCallback+0x1fe [onecoreuap\windows\dxaml\xcp\win\shared\xcpwindow.cpp @ 1240] 
13 0837f9dc 05d376b8 windows_ui_xaml!CXcpDispatcher::OnWindowMessage+0xaa [onecoreuap\windows\dxaml\xcp\win\shared\xcpwindow.cpp @ 1092] 
14 (Inline) -------- windows_ui_xaml!CXcpDispatcher::ProcessMessage+0x7c [onecoreuap\windows\dxaml\xcp\win\shared\xcpwindow.cpp @ 816] 
15 0837fa0c 766a2b5b windows_ui_xaml!CXcpDispatcher::WindowProc+0xb8 [onecoreuap\windows\dxaml\xcp\win\shared\xcpwindow.cpp @ 746] 
16 0837fa38 766950f3 USER32!_InternalCallWinProc+0x2b [d:\rs2.public.x86fre\internal\onecoreuapwindows\private\lib\i386\Core\ntuser\client\callproc.asm @ 116] 
17 (Inline) -------- USER32!InternalCallWinProc+0x1b [internal\onecoreuapwindows\private\inc\core\ntuser\client\callproc.h @ 81] 
18 0837fb20 76694a82 USER32!UserCallWinProcCheckWow+0x2d3 [windows\core\ntuser\client\clmsg.c @ 233] 
19 0837fb94 76694850 USER32!DispatchMessageWorker+0x222 [windows\core\ntuser\client\clmsg.c @ 3094] 
1a 0837fba0 083c140d USER32!DispatchMessageW+0x10 [internal\onecoreuapwindows\private\inc\core\ntuser\client\cltxt.h @ 1039] 
1b 0837fbe4 083bf403 Windows_UI!Windows::UI::Core::CDispatcher::ProcessMessage+0xbd [onecoreuap\windows\advcore\winrt\onecoreiwindow\corewindow\common\dispatcher.cpp @ 315] 
1c 0837fc70 083c1304 Windows_UI!Windows::UI::Core::CDispatcher::WaitAndProcessMessagesInternal+0xa3 [onecoreuap\windows\advcore\winrt\onecoreiwindow\corewindow\common\dispatcher.cpp @ 1766] 
1d 0837fcdc 05e8b2bb Windows_UI!Windows::UI::Core::CDispatcher::ProcessEvents+0x64 [onecoreuap\windows\advcore\winrt\onecoreiwindow\corewindow\common\dispatcher.cpp @ 569] 
1e (Inline) -------- windows_ui_xaml!CJupiterWindow::RunCoreWindowMessageLoop+0x4f [onecoreuap\windows\dxaml\xcp\dxaml\lib\jupiterwindow.cpp @ 1234] 
1f (Inline) -------- windows_ui_xaml!CJupiterControl::RunMessageLoop+0x66 [onecoreuap\windows\dxaml\xcp\dxaml\lib\jupitercontrol.cpp @ 907] 
20 (Inline) -------- windows_ui_xaml!DirectUI::DXamlCore::RunMessageLoop+0x74 [onecoreuap\windows\dxaml\xcp\dxaml\lib\dxamlcore.cpp @ 2062] 
21 0837fd20 68425f5d windows_ui_xaml!DirectUI::FrameworkView::Run+0x8b [onecoreuap\windows\dxaml\xcp\dxaml\lib\frameworkview_partial.cpp @ 100] 
22 0837fd34 6844e9c4 twinapi_appcore!Windows::ApplicationModel::Core::CoreApplicationView::Run+0x3d [onecoreuap\shell\coreapplication\application\lib\coreapplicationview.cpp @ 1696] 
23 0837fd64 76f97b3d twinapi_appcore!<lambda_0e4e0932c1ca7581c6ab87e21eafe60e>::operator()+0xc9 [onecoreuap\shell\coreapplication\application\lib\coreapplicationview.cpp @ 1149] 
24 0837fdec 741c8744 SHCORE!_WrapperThreadProc+0xdd [onecoreuap\shell\shcore\libs\thread\thread.cpp @ 321] 
25 0837fe00 7716587d KERNEL32!BaseThreadInitThunk+0x24 [base\win32\client\thread.c @ 64] 
26 0837fe48 7716584d ntdll_77100000!__RtlUserThreadStart+0x2f [minkernel\ntdll\rtlstrt.c @ 997] 
27 0837fe58 00000000 ntdll_77100000!_RtlUserThreadStart+0x1b [minkernel\ntdll\rtlstrt.c @ 914]

### PR DESCRIPTION
**Pull request by bviglietta**
Fixes #2514
UIActionSheet's Show completion handler should hold a strong reference to the UIActionSheet so that it isn't destroyed before the user can interact with it.

### CODE REVIEW

**Comment by bviglietta** [comment]
@jaredhms is added to the review. #Closed

File: Frameworks/UIKit/UIActionSheet.mm [hunk 1]
```diff
@@ -110,10 +110,12 @@ - (void)_UIActionSheet_initInternal:(const FrameworkElement&)xamlElement {
         objcwinrt::callback([weakSelf] (const Controls::ContentDialog&, const Controls::ContentDialogOpenedEventArgs&) {
             __strong UIActionSheet* strongSelf = weakSelf;
 
-            strongSelf->_isContentDialogVisible = YES;
+            if (strongSelf != nil) {
```
Comment (jaredhms) [inline Frameworks/UIKit/UIActionSheet.mm]: > != nil [](start = 26, length = 7)

nit: Much prefer a simple boolean comparison for pointers: 'if (strongSelf)' ...

**Comment by jaredhms** [comment]
:shipit:
