### PR TITLE
Protecting UIButton's CGSize calculations against nil receivers; more…

### LINKED ISSUE #2066: [TypographyInsight] Crash selecting "Kerning" tile - release only
Install TypeographyInsight from release drop share
Open TypeographyInsight app
Select the "Kerning" tile

Expected Result:
Page explaining kerning appears

Actual Result:
App crashes

### PR DESCRIPTION
**Pull request by jaredhms**
… fallout from #1965 and #1365.  Fixes #2066.

### CODE REVIEW

File: Frameworks/UIKit/UIButton.mm [hunk 1]
```diff
@@ -371,21 +371,32 @@ - (CGRect)contentRectForBounds:(CGRect)bounds {
...
+        // No image, so we return zero for the entire content rect
         return CGRectZero;
     }
 
-    imageSize = self.currentImage.size;
+    // Grab the size of the current title
+    // TODO: Should we be asking our label for this?
+    NSString* currentTitle = self.currentTitle;
+    CGSize titleSize = CGSizeZero;
+    if (currentTitle) {
```
Comment (oliversa-msft) [inline Frameworks/UIKit/UIButton.mm]: >currentTitle [](start = 8, length = 12)

[currentTitle length] > 0?

Comment (jaredhms) [inline Frameworks/UIKit/UIButton.mm]: not sure, and i think the safest approach is to stick to functional equivalence just to be safe

---
In reply to: [103035505](https://github.com/Microsoft/WinObjC/pull/2094#discussion_r103035505) [](ancestors = 103035505)

File: Frameworks/UIKit/UIButton.mm [hunk 2]
```diff
@@ -404,19 +415,34 @@ - (CGRect)imageRectForContentRect:(CGRect)contentRect {
...
+    // Note: #1365 All size calculations here must check for nil, 
+    // as we cannot assume getting a size from nil will return CGSizeZero
+    /////////////////////////////////////////////////////////////////////
 
-    if ([self currentTitle].length == 0) {
+    // Grab the size of the current title
+    // TODO: Should we be asking our label for this?
+    NSString* currentTitle = self.currentTitle;
+    CGSize titleSize = CGSizeZero;
+    if (currentTitle && currentTitle.length > 0) {
```
Comment (DHowett-MSFT) [inline Frameworks/UIKit/UIButton.mm]: per oliver's comment; `nil.length` is 0, so this is a redundant check

Comment (jaredhms) [inline Frameworks/UIKit/UIButton.mm]: i know, but if we don't leave the explicit nil check, someone may forget next time they come through here?

---
In reply to: [103035907](https://github.com/Microsoft/WinObjC/pull/2094#discussion_r103035907) [](ancestors = 103035907)

File: Frameworks/UIKit/UIButton.mm (hunk 1 above)
Comment (oliversa-msft) [inline Frameworks/UIKit/UIButton.mm]: Are you saying we should *not* do the same check like below: currentTitle && currentTitle.length > 0?

---
In reply to: [103035505](https://github.com/Microsoft/WinObjC/pull/2094#discussion_r103035505) [](ancestors = 103035505)

Comment (jaredhms) [inline Frameworks/UIKit/UIButton.mm]: i'm saying, 'i don't know'; do we have tests to validate this behavior?  I just went through and kept the existing functionality.  The other functions check the length, and this one doesn't, because that's how it worked previously.

---
In reply to: [103035705](https://github.com/Microsoft/WinObjC/pull/2094#discussion_r103035705) [](ancestors = 103035705,103035505)

**Comment by oliversa-msft** [comment]
:shipit:
