### PR TITLE
Fix some NSArray/NSMutableArray issues

### LINKED ISSUE #2771: [NSMutableArray removeObject:] does not remove all occurrences of an object in the array.
`[NSMutableArray removeObject:]` currently only removes the first occurrence of an object instance in the array. As per the reference platform, this method should remove all occurrences of an object instance in the array.

### PR DESCRIPTION
**Pull request by DHowett-MSFT**
* `removeObject:inRange:` was originally finding the first instance of the
  object in the range, and then doing an array-wide search-and-remove
  every time it found one. This was very clearly wrong.
  This method was also augmented to do batch removals where possible.
* `removeObject:` is supposed to remove every instance of the found object.
  It wasn't doing so. Fixes #2771.
* `removeObjectIdenticalTo:` is supposed to remove every instance of the
  found object. It also wasn't doing so.
* `removeObjectIdenticalTo:inRange:` wasn't implemented.
* `exchangeObjectAtIndex:withObjectAtIndex:` was not using its CF
  optimized implementation.
* Methods that mutated ranges were not bounds-checking those ranges.

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/winobjc/2773)

### CODE REVIEW

File: Frameworks/Foundation/NSMutableArray.mm [hunk 1]
```diff
@@ -157,46 +158,59 @@ - (void)exchangeObjectAtIndex:(NSUInteger)atIndex withObjectAtIndex:(NSUInteger)
...
  @Status Interoperable
 */
-- (void)removeObjectIdenticalTo:(NSObject*)objAddr {
-    int idx = [self indexOfObjectIdenticalTo:objAddr];
-    if (idx != NSNotFound) {
-        [self removeObjectAtIndex:idx];
+- (void)removeObjectsInRange:(NSRange)range {
+    NS_COLLECTION_VALIDATE_RANGE(range, self.count);
+
+    for (NSUInteger i = range.location + range.length; i > range.location; i--) {
```
Comment (ms-jihua) [inline Frameworks/Foundation/NSMutableArray.mm]: nit: --i

File: Frameworks/Foundation/NSCFCollectionSupport.h [hunk 2]
```diff
@@ -38,4 +38,16 @@ CFHashCode _NSCFCallbackHash(const void* value);
         }                                                                                                        \
     } while (false)
 
+#define NS_COLLECTION_VALIDATE_RANGE(range, count)                                                 \
+    do {                                                                                           \
+        if (range.location + range.length > (count)) {                                             \
```
Comment (aballway) [inline Frameworks/Foundation/NSCFCollectionSupport.h]: nit: save `count` to a local so it won't be expanded twice

File: Frameworks/Foundation/NSCFCollectionSupport.h [hunk 3]
```diff
@@ -38,4 +38,16 @@ CFHashCode _NSCFCallbackHash(const void* value);
...
+            [NSException raise:NSInvalidArgumentException                                          \
+                        format:@"*** %s: Range {%lu, %lu} out of bounds; legal range is {0, %lu}", \
+                               __PRETTY_FUNCTION__,                                                \
+                               (unsigned long)range.location,                                      \
```
Comment (aballway) [inline Frameworks/Foundation/NSCFCollectionSupport.h]: nit: no

File: Frameworks/Foundation/NSCFCollectionSupport.h [hunk 4]
```diff
@@ -38,4 +38,16 @@ CFHashCode _NSCFCallbackHash(const void* value);
...
+                               (unsigned long)range.length,                                        \
```
Comment (aballway) [inline Frameworks/Foundation/NSCFCollectionSupport.h]: nit: no

File: Frameworks/Foundation/NSCFCollectionSupport.h [hunk 5]
```diff
@@ -38,4 +38,16 @@ CFHashCode _NSCFCallbackHash(const void* value);
...
+                               (unsigned long)(count)];                                            \
```
Comment (aballway) [inline Frameworks/Foundation/NSCFCollectionSupport.h]: nit: no

File: Frameworks/Foundation/NSCFArray.mm [hunk 6]
```diff
@@ -84,7 +85,9 @@ - (NSUInteger)count {
 - (id)objectAtIndex:(NSUInteger)index {
     if (index >= CFArrayGetCount((CFArrayRef)self)) {
         [NSException raise:@"Array out of bounds"
-                    format:@"objectAtIndex: index > count (%lu > %lu), throwing exception\n", (unsigned long)index, (unsigned long)CFArrayGetCount((CFArrayRef)self)];
+                    format:@"objectAtIndex: index > count (%lu > %lu), throwing exception\n",
+                           (unsigned long)index,
```
Comment (aballway) [inline Frameworks/Foundation/NSCFArray.mm]: nit: no

File: Frameworks/Foundation/NSCFArray.mm [hunk 7]
```diff
@@ -84,7 +85,9 @@ - (NSUInteger)count {
...
+                           (unsigned long)CFArrayGetCount((CFArrayRef)self)];
```
Comment (aballway) [inline Frameworks/Foundation/NSCFArray.mm]: nit: no

File: Frameworks/Foundation/NSMutableArray.mm [hunk 8]
```diff
@@ -157,46 +158,59 @@ - (void)exchangeObjectAtIndex:(NSUInteger)atIndex withObjectAtIndex:(NSUInteger)
...
-        id curObj = [self objectAtIndex:i];
-
-        if ([curObj isEqual:objAddr]) {
-            [self removeObject:curObj];
+- (void)removeObject:(NSObject*)object inRange:(NSRange)range {
+    NS_COLLECTION_VALIDATE_RANGE(range, self.count);
+    // NSIndexSet can coalesce adjacent ranges. Combined with an efficient removeObjectsInRange:
+    // this can remove large swaths of objects more efficiently than individual mutation.
+    NSMutableIndexSet* indexes = [NSMutableIndexSet indexSet];
+    NSUInteger max = std::min(self.count, range.location + range.length);
```
Comment (aballway) [inline Frameworks/Foundation/NSMutableArray.mm]: nit: range is already validated, so this is unnecessary

File: Frameworks/Foundation/NSMutableArray.mm [hunk 9]
```diff
@@ -157,46 +158,59 @@ - (void)exchangeObjectAtIndex:(NSUInteger)atIndex withObjectAtIndex:(NSUInteger)
...
 */
-- (void)removeObject:(NSObject*)objAddr inRange:(NSRange)range {
-    for (int i = range.location + range.length - 1; i >= (int)range.location; i--) {
-        id curObj = [self objectAtIndex:i];
-
-        if ([curObj isEqual:objAddr]) {
-            [self removeObject:curObj];
+- (void)removeObject:(NSObject*)object inRange:(NSRange)range {
+    NS_COLLECTION_VALIDATE_RANGE(range, self.count);
+    // NSIndexSet can coalesce adjacent ranges. Combined with an efficient removeObjectsInRange:
```
Comment (aballway) [inline Frameworks/Foundation/NSMutableArray.mm]: removeObjectsInRange doesn't seem especially optimized. Would it be better to just remove them directly here rather than making an IndexSet, iterating and adding indexes to said index set, then iterating over the index set to remove the objects?

File: tests/unittests/Foundation/NSArrayTests.mm [hunk 10]
```diff
@@ -726,3 +727,74 @@ static unsigned long int objectIndexInArray(NSArray* array, int value, int start
     indexes = [NSIndexSet indexSetWithIndexesInRange:NSMakeRange(11, 11)];
     EXPECT_ANY_THROW([arr enumerateObjectsAtIndexes:indexes options:0 usingBlock:block]);
 }
+
```
Comment (aballway) [inline tests/unittests/Foundation/NSArrayTests.mm]: just for sanity sake, can you add a test with a range w/ 0 length?

File: Frameworks/Foundation/NSMutableArray.mm [hunk 11]
```diff
@@ -157,46 +158,59 @@ - (void)exchangeObjectAtIndex:(NSUInteger)atIndex withObjectAtIndex:(NSUInteger)
...
+    [self removeObjectIdenticalTo:object inRange:NSRange{ 0, self.count }];
+}
+
+/**
+ @Status Interoperable
+*/
+- (void)removeObjectIdenticalTo:(id)object inRange:(NSRange)range {
+    NS_COLLECTION_VALIDATE_RANGE(range, self.count);
+    NSMutableIndexSet* indexes = [NSMutableIndexSet indexSet];
+    NSUInteger max = std::min(self.count, range.location + range.length);
```
Comment (aballway) [inline Frameworks/Foundation/NSMutableArray.mm]: same as above

**Comment by DHowett-MSFT** [comment]
@aballway updated to address concerns

File: Frameworks/Foundation/NSMutableArray.mm [hunk 12]
```diff
@@ -154,49 +155,53 @@ - (void)exchangeObjectAtIndex:(NSUInteger)atIndex withObjectAtIndex:(NSUInteger)
...
 
 /**
  @Status Interoperable
 */
-- (void)removeObjectsInRange:(NSRange)range {
-    for (int i = range.location + range.length - 1; i >= (int)range.location; i--) {
-        [self removeObjectAtIndex:i];
-    }
+- (void)removeObjectIdenticalTo:(id)object inRange:(NSRange)range {
+    [self _removeObject:object inRange:range withComparator:[](id left, id right) -> bool { return right == left; }];
```
Comment (aballway) [inline Frameworks/Foundation/NSMutableArray.mm]: nit: is the `-> bool` necessary?

File: Frameworks/Foundation/NSMutableArray.mm [hunk 13]
```diff
@@ -154,49 +155,53 @@ - (void)exchangeObjectAtIndex:(NSUInteger)atIndex withObjectAtIndex:(NSUInteger)
...
 }
 
-/**
- @Status Interoperable
-*/
-- (void)removeObject:(NSObject*)objAddr {
-    if (objAddr == nil) {
-        TraceVerbose(TAG, L"objAddr = nil!");
-    }
+using _NSObjectComparator = bool (*)(id, id);
```
Comment (aballway) [inline Frameworks/Foundation/NSMutableArray.mm]: nit: this is only used once right? maybe just use directly.

File: Frameworks/Foundation/NSCFArray.mm (hunk 6 above)
Comment (aballway) [inline Frameworks/Foundation/NSCFArray.mm]: would still prefer these changed <3

File: Frameworks/Foundation/NSMutableArray.mm (hunk 13 above)
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSMutableArray.mm]: This seems cleaner.

File: Frameworks/Foundation/NSMutableArray.mm (hunk 12 above)
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSMutableArray.mm]: Alas, yes. `[x isEqual:y]` returns BOOL. Functions that return one/the other aren't implicitly convertible.
