### PR TITLE
getNetworkConnectivityLevel can throw under some circumstances.  Handle

### LINKED ISSUE #1786: Crash in +[SCNetworkReachability _checkGlobalReachability]
We’re seeing multiple crashes like the following.

Any idea why `-[WNCConnectionProfile getNetworkConnectivityLevel]` might be throwing an exception here? Should this be wrapped in a try/catch?

```
CPP_EXCEPTION_e06d7363_ObjCUWP_Windows_Networking.dll!-[WNCConnectionProfile_getNetworkConnectivityLevel]

0	kernelbase	RaiseException	0x62
1	vcruntime140_app	_CxxThrowException	0x65
2	libobjc2	objc_exception_throw	0x4BA
3	objcuwp_windows_networking	wil::details::ReportFailure	0x153
4	objcuwp_windows_networking	wil::details::ReportFailure_Hr	0x24
5	objcuwp_windows_networking	wil::details::in1diag5::_Objc_Throw_Hr	0x20
6	objcuwp_windows_networking	-[WNCConnectionProfile getNetworkConnectivityLevel]	0x6B
7	systemconfiguration	+[SCNetworkReachability _checkGlobalReachability]	0x25
8	systemconfiguration	+[SCNetworkReachability _networkStatusChanged]	0x17
9	systemconfiguration	__35+[SCNetworkReachability initialize]_block_invoke	0x13
10	objcuwp_windows_networking	WNCNetworkStatusChangedEventHandler_shim::Invoke	0x3D
11	windows_networking_connectivity	Windows::Internal::Details::GitInvokeHelper_Windows::Networking::Connectivity::INetworkStatusChangedEventHandler,Windows::Internal::GitPtr,1_::Invoke	0x48
12	windows_networking_connectivity	Microsoft::WRL::InvokeTraits_-2_::InvokeDelegates__lambda_5ea70f5f51dc6110b429d66ede34b4e1_,Windows::Networking::Connectivity::INetworkStatusChangedEventHandler_	0x46
13	windows_networking_connectivity	Microsoft::WRL::EventSource_Windows::Networking::Connectivity::INetworkStatusChangedEventHandler,Microsoft::WRL::InvokeModeOptions_-2_ _::DoInvoke__lambda_5ea70f5f51dc6110b429d66ede34b4e1_ _	0x43
14	windows_networking_connectivity	Windows::Networking::Connectivity::CEventDispatcher::_InvokeListeners	0x34
15	windows_networking_connectivity	Windows::Networking::Connectivity::CEventDispatcher::_InvokeListenersCallback	0x46
16	ntdll	TppWorkpExecuteCallback	0x153
17	ntdll	TppWorkerThread	0x396
18	kernel32	BaseThreadInitThunk	0x24
19	ntdll	__RtlUserThreadStart	0x2F
20	ntdll	_RtlUserThreadStart
```

### PR DESCRIPTION
**Pull request by rajsesh-msft**
these and treat the connection status as 'not connected'.

Fixes #1786

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/winobjc/1795)

### CODE REVIEW

File: Frameworks/SystemConfiguration/SCNetworkReachability.mm [hunk 1]
```diff
@@ -134,15 +134,19 @@ + (void)_testAllReachabilityObjects {
...
+            if (internetConnectionProfile.isWwanConnectionProfile) {
+                newFlags |= kSCNetworkReachabilityFlagsIsWWAN;
+            }
+            _globalReachableFlags = newFlags;
+        } else {
+            _globalReachableFlags = 0;
         }
-        _globalReachableFlags = newFlags;
-    } else {
+    } @catch (NSException* exception) {
```
Comment (DHowett-MSFT) [inline Frameworks/SystemConfiguration/SCNetworkReachability.mm]: This will probably fail on ARM, due to our slightly busted exception handling. `@catch(...)` will sidestep the issue at the cost of some clarity.

Comment (rajsesh-msft) [inline Frameworks/SystemConfiguration/SCNetworkReachability.mm]: Bummer given other places have this too.  I've opened #1796 to track other instances of this.

Comment (ashvarma) [inline Frameworks/SystemConfiguration/SCNetworkReachability.mm]: Do we have a compiler bug/task that's tracking this? +Wes

---
In reply to: [97645904](https://github.com/Microsoft/WinObjC/pull/1795#discussion_r97645904) [](ancestors = 97645904)
