### PR TITLE
Fix [NSString stringByAddingPercentEscapesUsingEncoding:] not working.

### LINKED ISSUE #943: [NSString stringByAddingPercentEscapesUsingEncoding:] not working.
[NSString stringByAddingPercentEscapesUsingEncoding:] doesn't seem to correctly percent escape some strings.

For example:
```
NSString *escapedString = [@"claesström" stringByAddingPercentEscapesUsingEncoding:NSUTF8StringEncoding];
```
returns `claesström` but should return `claesstr%C3%B6m`.

### PR DESCRIPTION
**Pull request by MSFTFox**
This deprecated API was working incorrectly. A fix has been added
using modified Core Foundation percent encoding APIs. New tests
have been added.

Fix #943

### CODE REVIEW

File: Frameworks/Foundation/NSString.mm [hunk 1]
```diff
@@ -1427,36 +1427,25 @@ - (NSString*)stringByPaddingToLength:(NSUInteger)newLength withString:(NSString*
     return mutableCopy;
 }
 
+NSString* s_percentEncodedFormat = @"%%%s%X";
+const int s_oneByte = 16;
```
Comment (rajsesh-msft) [inline Frameworks/Foundation/NSString.mm]: >s_oneByte [](start = 10, length = 9)

ugh? These dont need to be here.

File: Frameworks/CoreFoundation/URL.subproj/CFURL.c [hunk 2]
```diff
@@ -1407,14 +1416,16 @@ CF_EXPORT CFStringRef CFURLCreateStringByAddingPercentEscapes(CFAllocatorRef all
                         // surrogate pair conversion failed
                         break;
                     }
-                } else {
+                }
```
Comment (rajsesh-msft) [inline Frameworks/CoreFoundation/URL.subproj/CFURL.c]: >} [](start = 16, length = 1)

these are incorrect line breaks we prefer } else {

File: Frameworks/Foundation/NSString.mm (hunk 1 above)
Comment (MSFTFox) [inline Frameworks/Foundation/NSString.mm]: Yup, left over from testing various fixes to this API. Forgot to remove.

---
In reply to: [77075166](https://github.com/Microsoft/WinObjC/pull/946#discussion_r77075166) [](ancestors = 77075166)

File: Frameworks/CoreFoundation/URL.subproj/CFURL.c (hunk 2 above)
Comment (MSFTFox) [inline Frameworks/CoreFoundation/URL.subproj/CFURL.c]: Formatter messed things up somehow. Fixed.

---
In reply to: [77075978](https://github.com/Microsoft/WinObjC/pull/946#discussion_r77075978) [](ancestors = 77075978)

File: Frameworks/CoreFoundation/URL.subproj/CFURL.c [hunk 3]
```diff
@@ -1323,8 +1323,17 @@ static Boolean _stringContainsCharacter(CFStringRef string, UniChar ch) {
     return false;
 }
 
+// WINOBJC : A function for creating percent escapes based on character sets instead of strings has been added. This is used for stringByAddingPercentEscapesUsingEncoding which operates on a valid set of
```
Comment (ms-jihua) [inline Frameworks/CoreFoundation/URL.subproj/CFURL.c]: Please break these into shorter lines - I know clang isn't enabled on this file, but it's good practice nonetheless.

**Comment by ms-jihua** [comment]
:shipit:

File: Frameworks/CoreFoundation/URL.subproj/CFURL.c (hunk 3 above)
Comment (MSFTFox) [inline Frameworks/CoreFoundation/URL.subproj/CFURL.c]: Oh woops, I have a bad habit of letting the formatter handle my comments.

---
In reply to: [77091827](https://github.com/Microsoft/WinObjC/pull/946#discussion_r77091827) [](ancestors = 77091827)

File: Frameworks/CoreFoundation/URL.subproj/CFURL.c [hunk 4]
```diff
@@ -1323,8 +1323,17 @@ static Boolean _stringContainsCharacter(CFStringRef string, UniChar ch) {
...
+// the URLFragmentAllowedCharacterSet. Converting a character set to a string is expensive, but converting a string to a character set is not. Lookup in a character set is also significantly more efficient.
+// As such, an extra function for using character sets has been added instead, and the string version has been modified to use this.
+
 // Note: charactersToLeaveUnescaped and legalURLCharactersToBeEscaped only work for characters which can be represented as a single UTF16 codepoint.
 CF_EXPORT CFStringRef CFURLCreateStringByAddingPercentEscapes(CFAllocatorRef allocator, CFStringRef originalString, CFStringRef charactersToLeaveUnescaped, CFStringRef legalURLCharactersToBeEscaped, CFStringEncoding encoding) {
+    return CFURLCreateStringByAddingPercentEscapesWithCharacterSets(allocator, originalString, CFCharacterSetCreateWithCharactersInString(allocator, charactersToLeaveUnescaped), CFCharacterSetCreateWithCharactersInString(allocator, legalURLCharactersToBeEscaped), encoding);
```
Comment (DHowett-MSFT) [inline Frameworks/CoreFoundation/URL.subproj/CFURL.c]: >CFCharacterSetCreateWithCharactersInString [](start = 95, length = 42)

These character sets have to be CFReleased after you're done using them.

File: Frameworks/CoreFoundation/URL.subproj/CFURL.c [hunk 5]
```diff
@@ -1387,32 +1396,32 @@ CF_EXPORT CFStringRef CFURLCreateStringByAddingPercentEscapes(CFAllocatorRef all
...
-                        for ( currByte = bytes; currByte < endPtr; currByte++ ) {
+                        for (currByte = bytes; currByte < endPtr; currByte++) {
                             charBuffer[charBufferIndex++] = '%';
                             charBuffer[charBufferIndex++] = hexchars[*currByte >> 4];
                             charBuffer[charBufferIndex++] = hexchars[*currByte & 0x0f];
                         }
                         idx++; // We consumed 2 characters, not 1
-                    }
-                    else {
+                    } else {
```
Comment (DHowett-MSFT) [inline Frameworks/CoreFoundation/URL.subproj/CFURL.c]: >        } else { [](start = 12, length = 16)

Please do not reformat CoreFoundation files; return lines 1398-1414 to their original state.

Comment (DHowett-MSFT) [inline Frameworks/CoreFoundation/URL.subproj/CFURL.c]: also 1424-1436

---
In reply to: [77097021](https://github.com/Microsoft/WinObjC/pull/946#discussion_r77097021) [](ancestors = 77097021)

File: Frameworks/CoreFoundation/URL.subproj/CFURL.h [hunk 6]
```diff
@@ -406,6 +406,9 @@ CFStringRef CFURLCreateStringByReplacingPercentEscapesUsingEncoding(CFAllocatorR
 CF_EXPORT
 CFStringRef CFURLCreateStringByAddingPercentEscapes(CFAllocatorRef allocator, CFStringRef originalString, CFStringRef charactersToLeaveUnescaped, CFStringRef legalURLCharactersToBeEscaped, CFStringEncoding encoding) CF_DEPRECATED(10_0, 10_11, 2_0, 9_0, "Use [NSString stringByAddingPercentEncodingWithAllowedCharacters:] instead, which always uses the recommended UTF-8 encoding, and which encodes for a specific URL component or subcomponent (since each URL component or subcomponent has different rules for what characters are valid).");
 
+// WINOBJC : An additional method for using character sets has been added for efficiency.
```
Comment (DHowett-MSFT) [inline Frameworks/CoreFoundation/URL.subproj/CFURL.h]: >/ WINOBJC : An additional method for using character sets has been added for efficiency. [](start = 1, length = 88)

You can word this in a less circuitous manner.

```
WINOBJC: Add a function for escaping strings with character sets.
```

Comment (DHowett-MSFT) [inline Frameworks/CoreFoundation/URL.subproj/CFURL.h]: (There's no need for passive voice.0

---
In reply to: [77097076](https://github.com/Microsoft/WinObjC/pull/946#discussion_r77097076) [](ancestors = 77097076)

File: Frameworks/Foundation/NSString.mm [hunk 7]
```diff
@@ -1429,34 +1429,19 @@ - (NSString*)stringByPaddingToLength:(NSUInteger)newLength withString:(NSString*
 
 /**
  @Status Interoperable
+ @Notes This API was deprecated in favor of stringByAddingPercentEncodingWithAllowedCharacters. APIs to decode anything other than
+ UTF8StringEncoding is unsupported both here and on the reference platform.
```
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSString.mm]: >UTF8StringEncoding [](start = 1, length = 18)

"APIs ... is unsupported"

File: tests/unittests/Foundation/NSStringTests.m [hunk 8]
```diff
@@ -607,4 +607,37 @@ void testUrlCharacterSetEncoding(NSString* decodedString, NSString* encodedStrin
...
+    originalString = @"claesström";
+    expectedEscapedString = @"claesstr%C3%B6m";
+
+    escapedString = [originalString stringByAddingPercentEscapesUsingEncoding:NSUTF8StringEncoding];
+
+    EXPECT_OBJCEQ(expectedEscapedString, escapedString);
+    EXPECT_OBJCEQ(originalString, escapedString.stringByRemovingPercentEncoding);
+    EXPECT_OBJCEQ(originalString, [escapedString stringByReplacingPercentEscapesUsingEncoding:NSUTF8StringEncoding]);
+
+    // Removing percent encoding is unsupported on the reference platform for anything other than UTF8 which is why the reference platform
```
Comment (DHowett-MSFT) [inline tests/unittests/Foundation/NSStringTests.m]: >which is why [](start = 103, length = 12)

I do not think that we can say with certainty that that is _why_ they deprecated it.

**Comment by DHowett-MSFT** [comment]
:clock1:

**Comment by rajsesh-msft** [comment]
:shipit:

File: Frameworks/CoreFoundation/URL.subproj/CFURL.c [hunk 9]
```diff
@@ -1387,7 +1404,7 @@ CF_EXPORT CFStringRef CFURLCreateStringByAddingPercentEscapes(CFAllocatorRef all
             }
             else {
                 // FIXME: once CFString supports finding glyph boundaries walk by glyph boundaries instead of by unichars
-                if ( encoding == kCFStringEncodingUTF8 && CFCharacterSetIsSurrogateHighCharacter(ch) && idx + 1 < length && CFCharacterSetIsSurrogateLowCharacter(__CFStringGetCharacterFromInlineBufferQuick(&buf, idx+1)) ) {
```
Comment (DHowett-MSFT) [inline Frameworks/CoreFoundation/URL.subproj/CFURL.c]: >kCFStringEncodingUTF8 [](start = 33, length = 21)

Please do not reformat CoreFoundation files; return line 1406 to its original state.
