### PR TITLE
Fixing a crash when calling CGContextAddPath with a NULL path

### LINKED ISSUE #966: CGContextAddPath crashes with NULL path parameter
CGContextAddPath will crash when a null path parameter is passed in.  On iOS is does not crash and the Apple documentation implies that a null input value is ok.

### PR DESCRIPTION
**Pull request by pittmab**
The Apple docs for CGContextAddPath imply that passing a NULL path does nothing and is a valid API call.

Fix #966

### CODE REVIEW

File: Frameworks/CoreGraphics/CGContext.mm [hunk 1]
```diff
@@ -452,6 +452,11 @@ void CGContextFillEllipseInRect(CGContextRef ctx, CGRect rct) {
  @Status Interoperable
 */
 void CGContextAddPath(CGContextRef ctx, CGPathRef path) {
+    // The Apple SDK docs imply that passing a NULL path is valid
+	if (!path) {
```
Comment (aballway) [inline Frameworks/CoreGraphics/CGContext.mm]: >	 [](start = 0, length = 1)

nit: spaces, not tabs

File: Frameworks/CoreGraphics/CGContext.mm [hunk 2]
```diff
@@ -452,6 +452,11 @@ void CGContextFillEllipseInRect(CGContextRef ctx, CGRect rct) {
...
+        return;
+	}
```
Comment (aballway) [inline Frameworks/CoreGraphics/CGContext.mm]: nit: this would be better with the work in the if rather than preemptively returning, especially since it's void

**Comment by aballway** [comment]
:clock1:

File: Frameworks/CoreGraphics/CGContext.mm (hunk 1 above)
Comment (pittmab) [inline Frameworks/CoreGraphics/CGContext.mm]: Updated to use spaces.

File: Frameworks/CoreGraphics/CGContext.mm (hunk 2 above)
Comment (pittmab) [inline Frameworks/CoreGraphics/CGContext.mm]: Updated the code to reflect your preferences.  Thanks

Comment (pittmab) [inline Frameworks/CoreGraphics/CGContext.mm]: @aballway I have updated the code to reflect your comments.  Thanks

**Comment by rajsesh-msft** [comment]
:shipit:
