### PR TITLE
Fix various test failures in NS*URLResponse

### LINKED ISSUE #780: NSURLResponse.canBeArchived, NSHTTPURLResponse.canBeArchived fail on OSX
[ RUN      ] NSURLResponse.canBeArchived
Foundation/ReferenceFoundation/TestNSURLResponse.mm:330: Failure
Value of: actual
  Actual: <NSURLResponse: 0x7fae98c7dbd0> { URL: test }
Expected: expected
Which is: <NSURLResponse: 0x7fae98c84a20> { URL: test }
[  FAILED  ] NSURLResponse.canBeArchived (1 ms)

[ RUN      ] NSHTTPURLResponse.canBeArchived
Foundation/ReferenceFoundation/TestNSURLResponse.mm:341: Failure
Value of: actual
  Actual: <NSHTTPURLResponse: 0x7fae9b2410a0> { URL: https://www.swift.org } { status code: 200, headers {
    "Content-Type" = "text/HTML; charset=ISO-8859-4";
} }
Expected: expected
Which is: <NSHTTPURLResponse: 0x7fae9b222d60> { URL: https://www.swift.org } { status code: 200, headers {
    "Content-Type" = "text/HTML; charset=ISO-8859-4";
} }
[  FAILED  ] NSHTTPURLResponse.canBeArchived (1 ms)

### LINKED ISSUE #781: NSHTTPURLResponse suggested filename tests fail on OSX
[ RUN      ] NSHTTPURLResponse.SuggestedFilename_3
Foundation/ReferenceFoundation/TestNSURLResponse.mm:265: Failure
Value of: response.suggestedFilename
  Actual: ;.ext
Expected: @"_.ext"
Which is: _.ext
[  FAILED  ] NSHTTPURLResponse.SuggestedFilename_3 (0 ms)
[ RUN      ] NSHTTPURLResponse.SuggestedFilename_4
Foundation/ReferenceFoundation/TestNSURLResponse.mm:273: Failure
Value of: response.suggestedFilename
  Actual: wrong.ext
Expected: @"fname.ext"
Which is: fname.ext
[  FAILED  ] NSHTTPURLResponse.SuggestedFilename_4 (0 ms)

### PR DESCRIPTION
**Pull request by DHowett-MSFT**
* For NS*URLResponse, add parallel archival tests that work on OS X but don't use isEqual:. Fixes #780.
* Fix the NS*URLResponse suggested filename tests and regressions.

    `;` is a valid filename character on Windows, and it is valid on OS X.
Fixes #781.

    All our suggested filename tests had invalid MIME types. Now that they
are valid, we've been revealed to be ignoring it. Ref #832.

* Fix the NSURLResponse test names.
* The reference platform takes the _first_ filename from Disposition. Match it.
Ref #781.

### CODE REVIEW

File: Frameworks/Foundation/NSHTTPURLResponse.mm [hunk 1]
```diff
@@ -85,7 +85,7 @@ - (id)initWithURL:(NSURL*)url statusCode:(NSInteger)statusCode HTTPVersion:(NSSt
 
         // Parse the filename from the Content-Disposition header field.
         NSString* contentDisposition = [allHeaderFields objectForKey:@"Content-Disposition"];
-        NSRange filenameTagPosition = [contentDisposition rangeOfString:@"filename=" options:NSBackwardsSearch];
```
Comment (ms-jihua) [inline Frameworks/Foundation/NSHTTPURLResponse.mm]: >NSBackwardsSearch [](start = 93, length = 17)

? shouldn't this be more efficient as backwards?

Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSHTTPURLResponse.mm]: The reference platform appears to pull the first filename, not the last one, in case there is more than one.

Comment (ms-jihua) [inline Frameworks/Foundation/NSHTTPURLResponse.mm]: Got it.

---
In reply to: [73768171](https://github.com/Microsoft/WinObjC/pull/835#discussion_r73768171) [](ancestors = 73768171)

File: tests/unittests/Foundation/ReferenceFoundation/TestNSURLResponse.mm [hunk 2]
```diff
@@ -71,21 +71,35 @@
...
-TEST(NSURLResponse, SuggestedFilename) {
+// Disabled pending GH#832; we do not respect the incoming MIME type when generating filenames. OS X does.
+OSX_DISABLED_TEST(NSURLResponse, SuggestedFilename) {
     NSURL* url = [NSURL URLWithString:@"a/test/name.extension"];
-    NSURLResponse* res = [[[NSURLResponse alloc] initWithURL:url MIMEType:@"txt" expectedContentLength:0 textEncodingName:nil] autorelease];
+    NSURLResponse* res = [[[NSURLResponse alloc] initWithURL:url MIMEType:@"text/plain" expectedContentLength:0 textEncodingName:nil] autorelease];
     ASSERT_OBJCEQ(@"name.extension", res.suggestedFilename);
 }
 
-TEST(NSURLResponse, SuggestedFilename_2) {
```
Comment (ms-jihua) [inline tests/unittests/Foundation/ReferenceFoundation/TestNSURLResponse.mm]: >_2 [](start = 37, length = 2)

Er, keep these original names (this is ReferenceFoundation)

Comment (ms-jihua) [inline tests/unittests/Foundation/ReferenceFoundation/TestNSURLResponse.mm]: (I know they're not very good names, but)

---
In reply to: [73769571](https://github.com/Microsoft/WinObjC/pull/835#discussion_r73769571) [](ancestors = 73769571)

**Comment by mnithish** [comment]
:shipit:

File: tests/unittests/Foundation/ReferenceFoundation/TestNSURLResponse.mm (hunk 2 above)
Comment (DHowett-MSFT) [inline tests/unittests/Foundation/ReferenceFoundation/TestNSURLResponse.mm]: I totally didn't realize these were in ReferenceFoundation!
That worries me, since the tests were largely incorrect for OS X..:(

Comment (ms-jihua) [inline tests/unittests/Foundation/ReferenceFoundation/TestNSURLResponse.mm]: Yeaahhh same D:

---
In reply to: [73769649](https://github.com/Microsoft/WinObjC/pull/835#discussion_r73769649) [](ancestors = 73769649)

Comment (DHowett-MSFT) [inline tests/unittests/Foundation/ReferenceFoundation/TestNSURLResponse.mm]: That means the reference foundation tests also ignored MIME types ... oh boy

File: tests/unittests/Foundation/ReferenceFoundation/TestNSURLResponse.mm [hunk 3]
```diff
@@ -71,21 +71,35 @@
...
+// Disabled pending GH#832; we do not respect the incoming MIME type when generating filenames. OS X does.
+OSX_DISABLED_TEST(NSURLResponse, SuggestedFilename_QueryParameter) {
     NSURL* url = [NSURL URLWithString:@"a/test/name.extension?foo=bar"];
-    NSURLResponse* res = [[[NSURLResponse alloc] initWithURL:url MIMEType:@"txt" expectedContentLength:0 textEncodingName:nil] autorelease];
+    NSURLResponse* res = [[[NSURLResponse alloc] initWithURL:url MIMEType:@"text/plain" expectedContentLength:0 textEncodingName:nil] autorelease];
     ASSERT_OBJCEQ(@"name.extension", res.suggestedFilename);
 }
 
-TEST(NSURLResponse, SuggestedFilename_3) {
+TEST(NSURLResponse, SuggestedFilename_MatchingMIME) {
```
Comment (ms-jihua) [inline tests/unittests/Foundation/ReferenceFoundation/TestNSURLResponse.mm]: Move to the non-referenceFoundation test file?

File: tests/unittests/Foundation/ReferenceFoundation/TestNSURLResponse.mm [hunk 4]
```diff
@@ -319,9 +333,34 @@
 }
 
 // Archival
-TEST(NSURLResponse, canBeArchived) {
+TEST(NSURLResponse, CanBeArchived) {
```
Comment (ms-jihua) [inline tests/unittests/Foundation/ReferenceFoundation/TestNSURLResponse.mm]: Move these into non-ReferenceFoundation tests?

**Comment by DHowett-MSFT** [comment]
@ms-jihua Reference platform tests _mostly_ restored!

File: tests/unittests/Foundation/ReferenceFoundation/TestNSURLResponse.mm [hunk 5]
```diff
@@ -71,21 +75,23 @@
...
+OSX_DISABLED_TEST(NSURLResponse, SuggestedFilename) {
     NSURL* url = [NSURL URLWithString:@"a/test/name.extension"];
-    NSURLResponse* res = [[[NSURLResponse alloc] initWithURL:url MIMEType:@"txt" expectedContentLength:0 textEncodingName:nil] autorelease];
+    NSURLResponse* res = [[[NSURLResponse alloc] initWithURL:url MIMEType:@"text/plain" expectedContentLength:0 textEncodingName:nil] autorelease];
     ASSERT_OBJCEQ(@"name.extension", res.suggestedFilename);
 }
 
-TEST(NSURLResponse, SuggestedFilename_2) {
+// Disabled pending GH#832; we do not respect the incoming MIME type when generating filenames. OS X does.
+OSX_DISABLED_TEST(NSURLResponse, SuggestedFilename_QueryParameter) {
```
Comment (ms-jihua) [inline tests/unittests/Foundation/ReferenceFoundation/TestNSURLResponse.mm]: >SuggestedFilename_QueryParameter [](start = 33, length = 32)

Still a few name changes remaining.

**Comment by ms-jihua** [comment]
:shipit:

File: tests/unittests/Foundation/ReferenceFoundation/TestNSURLResponse.mm (hunk 5 above)
Comment (DHowett-MSFT) [inline tests/unittests/Foundation/ReferenceFoundation/TestNSURLResponse.mm]: Whoops! The revert fell over where I did both a name change and a disable.

**Comment by aballway** [comment]
:shipit:
