### PR TITLE
Fix (and update) UIGraphicsFunctions.

### LINKED ISSUE #1642: UIGraphicsFunctions are broken in CGD2D
It also needs a little cleanup.

### PR DESCRIPTION
**Pull request by DHowett-MSFT**
Fixes #1642.

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/winobjc/1681)

### CODE REVIEW

File: Frameworks/UIKit/UIGraphicsFunctions.mm [hunk 1]
```diff
@@ -101,63 +126,91 @@ void UIGraphicsBeginImageContext(CGSize size) {
...
-void UIRectClip(CGRect clip) {
-    CGContextRef ctx = UIGraphicsGetCurrentContext();
+void UIRectFrame(CGRect rect) {
+    UIRectFrameUsingBlendMode(rect, kCGBlendModeCopy);
+}
 
-    CGContextClipToRect(ctx, clip);
+/**
+ @Status Caveat
+ @Notes Blend modes are not implemented.
```
Comment (rajsesh-msft) [inline Frameworks/UIKit/UIGraphicsFunctions.mm]: Since these caveats are already present in CG, we don't need to specify it again here.  I would mark these as interoperable with notes that we support all blend modes that CG supports.

File: Frameworks/UIKit/UIGraphicsFunctions.mm [hunk 2]
```diff
@@ -22,72 +22,97 @@
...
+    std::lock_guard<std::mutex> lock(s_contextStackMutex);
+    return s_contextStack.top().context.get();
 }
 
 /**
- @Status Caveat
- @Notes opaque parameter not supported
+ @Status Interoperable
 */
 void UIGraphicsBeginImageContextWithOptions(CGSize size, BOOL opaque, float scale) {
```
Comment (rajsesh-msft) [inline Frameworks/UIKit/UIGraphicsFunctions.mm]: How are these methods tested?

File: Frameworks/UIKit/UIGraphicsFunctions.mm [hunk 3]
```diff
@@ -22,72 +22,97 @@
...
 }
 
 /**
  @Status Interoperable
 */
 void UIGraphicsPopContext() {
-    if (_currentCGContextDepth <= 0) {
-        assert(0);
+    std::lock_guard<std::mutex> lock(s_contextStackMutex);
+    if (s_contextStack.size() == 0) {
```
Comment (aballway) [inline Frameworks/UIKit/UIGraphicsFunctions.mm]: nit: .empty()

File: Frameworks/UIKit/UIGraphicsFunctions.mm [hunk 4]
```diff
@@ -22,72 +22,97 @@
...
-    CGContextRef newCtx = _CGBitmapContextCreateWithFormat((int)(size.width * scale), (int)(size.height * scale), _ColorARGB);
-    newCtx->scale = scale;
-    CGContextTranslateCTM(newCtx, 0.0f, size.height * scale);
-    CGContextScaleCTM(newCtx, scale, scale);
-    CGContextScaleCTM(newCtx, 1.0f, -1.0f);
 
-    UIGraphicsPushContext(newCtx);
-#endif
+    CGSize scaledSize{
+        size.width * scale, size.height * scale,
```
Comment (aballway) [inline Frameworks/UIKit/UIGraphicsFunctions.mm]: worth making a operator*(CGSize, CGFloat) for this?

File: Frameworks/UIKit/UIGraphicsFunctions.mm [hunk 5]
```diff
@@ -22,72 +22,97 @@
...
+                              scaledSize.width,
+                              scaledSize.height,
+                              8, // 32bpp (8 bits per component)
+                              scaledSize.width * 4, // Stride for RGBA/RGBX
+                              rgbColorSpace.get(),
+                              (opaque ? kCGImageAlphaNoneSkipLast : kCGImageAlphaPremultipliedLast) | kCGBitmapByteOrder32Little);
+
+    // Apply the UIKit ULO transform (and shadow projection transform)
+    CGContextTranslateCTM(context, 0.0f, size.height * scale);
+    CGContextScaleCTM(context, scale, scale);
```
Comment (aballway) [inline Frameworks/UIKit/UIGraphicsFunctions.mm]: nit: scale, -scale

File: Frameworks/UIKit/UIGraphicsFunctions.mm [hunk 6]
```diff
@@ -22,72 +22,97 @@
...
+    _CGContextSetShadowProjectionTransform(context, CGAffineTransformMakeScale(1.0, -1.0));
+
+    {
+        std::lock_guard<std::mutex> lock(s_contextStackMutex);
+
+        s_contextStack.emplace(context, _UIGraphicsContextTypeImage, size, scale);
+    }
+
+    // This context is owned by the context stack.
+    CGContextRelease(context);
```
Comment (aballway) [inline Frameworks/UIKit/UIGraphicsFunctions.mm]: keep context in a unique_cf? nothing should fail terribly in here but would keep consistent with usage

File: Frameworks/UIKit/UIGraphicsFunctions.mm [hunk 7]
```diff
@@ -101,63 +126,91 @@ void UIGraphicsBeginImageContext(CGSize size) {
...
 */
 UIImage* UIGraphicsGetImageFromCurrentImageContext() {
-    return nil;
-    // TODO(DH) GH#1124 Revisit when we have support for CGImage+IWICBitmap
-#if 0
-    id ret = [UIImage imageWithCGImage:CGBitmapContextGetImage(UIGraphicsGetCurrentContext())
-                                 scale:UIGraphicsGetCurrentContext()->scale
-                           orientation:UIImageOrientationUp];
+    std::lock_guard<std::mutex> lock(s_contextStackMutex);
+    if (s_contextStack.size() == 0) {
```
Comment (aballway) [inline Frameworks/UIKit/UIGraphicsFunctions.mm]: nit: same as above

File: Frameworks/UIKit/UIGraphicsFunctions.mm [hunk 8]
```diff
@@ -101,63 +126,91 @@ void UIGraphicsBeginImageContext(CGSize size) {
...
+    }
+
+    _UIGraphicsContextRecord& topRecord = s_contextStack.top();
+    if (topRecord.type != _UIGraphicsContextTypeImage) {
+        TraceError(TAG, L"UIGraphicsGetImageFromCurrentImageContext(): the top context is not an image context.");
+        return nil;
+    }
 
+    CGContextRef context = topRecord.context.get();
+    id ret = [UIImage imageWithCGImage:CGBitmapContextGetImage(context) scale:topRecord.scale orientation:UIImageOrientationUp];
```
Comment (aballway) [inline Frameworks/UIKit/UIGraphicsFunctions.mm]: nit: just return here

File: Frameworks/UIKit/UIGraphicsFunctions.mm [hunk 9]
```diff
@@ -101,63 +126,91 @@ void UIGraphicsBeginImageContext(CGSize size) {
...
-    CGContextRef ctx = UIGraphicsGetCurrentContext();
+    std::lock_guard<std::mutex> lock(s_contextStackMutex);
+    if (s_contextStack.size() == 0) {
+        TraceError(TAG, L"UIGraphicsEndImageContext(): the context stack was empty.");
+        return;
+    }
+
+    _UIGraphicsContextRecord& topRecord = s_contextStack.top();
+    if (topRecord.type != _UIGraphicsContextTypeImage) {
+        return;
```
Comment (aballway) [inline Frameworks/UIKit/UIGraphicsFunctions.mm]: please flip this 😢

**Comment by DHowett-MSFT** [comment]
@rajsesh-msft Addressed the annotation concerns. These functions are used heavily in UIKit and QuartzCore. Validation was performed with Canabalt and Islandwood News.

Since many of them require contexts (and some of them require non-bitmap contexts) and our UI testing infrastructure is not up to par, it is difficult to unit test these functions.

**Comment by MSFTFox** [comment]
:shipit:
