### PR TITLE
Reimplement NSNotificationCenter (and NSNotification)

### LINKED ISSUE #2391: NSNotificationCenter is not thread safe.
NSNotificationCenter is not thread safe, removing, adding and notifying observers from different threads results in a crash. 

On the reference platform NSNotificationCenter is thread safe.

### PR DESCRIPTION
**Pull request by DHowett-MSFT**
This pull request guts and reimplements both **NSNotificationCenter** and **NSNotification**.

NSNotification is supposed to be a class cluster. It it was empirically observed that non-concrete instances could still encode/decode, but would fail with abstract invocation exceptions on the property getter.

NSNotificationCenter is vastly improved. It:
* Uses sets for quick lookup, since notification order bears no guarantees
* Maintains a set of all receivers (for quick name-free removal)
* Maintains a mapping from notification name to interested receivers (for quick dispatch)
* Now supports enqueuing notification blocks on queues
* Fulfills the contractual obligations of `addObserverForName:object:queue:usingBlock:`
* Has no caveats
* Is thread-safe
* Is tested

Fixes #2391.

### CODE REVIEW

File: tests/unittests/Foundation/NSNotificationTests.mm [hunk 1]
```diff
@@ -15,7 +15,54 @@
...
+// Avoid "property access result unused" warnings by _consume-ing the value of a property accessor.
+template <typename... T>
+static inline void _consume(T&&...) {
+}
+
+TEST(NSNotification, CanCreate) {
+    EXPECT_OBJCNE(nil, [NSNotification notificationWithName:@"name" object:nil userInfo:nil]);
+}
+
+@interface BadNSNotificationSubclass : NSNotification
```
Comment (DHowett-MSFT) [inline tests/unittests/Foundation/NSNotificationTests.mm]: I know, these `^M`s aren't great. The entire file has them, though!

Comment (DHowett-MSFT) [inline tests/unittests/Foundation/NSNotificationTests.mm]: I will cap this review with a reformat, but I don't want to churn unchanged lines.

File: Frameworks/Foundation/NSNotificationCenter.mm [hunk 2]
```diff
@@ -14,227 +14,289 @@
...
         }
-        [observer release];
+    } else {
+        // Slow path: remove these observers from every name table.
+        NSArray<NSString*>* copiedAllKeys = [[_observers allKeys] copy];
+        for (NSString* key in copiedAllKeys) {
+            StrongId<NSMutableSet<_NSNotificationReceiver*>> nameReceivers = [_observers objectForKey:key];
+            [nameReceivers minusSet:receivers];
+            if ([nameReceivers count] == 0) {
+                [_observers removeObjectForKey:name];
```
Comment (aballway) [inline Frameworks/Foundation/NSNotificationCenter.mm]: name is nil?

File: Frameworks/Foundation/NSNotificationCenter.mm [hunk 3]
```diff
@@ -14,227 +14,289 @@
...
+        [nameReceivers minusSet:receivers];
+
+        if ([nameReceivers count] == 0) {
+            // This can release nameReceivers; it will be retained for the scope of this method.
+            [_observers removeObjectForKey:name];
         }
-        [observer release];
+    } else {
+        // Slow path: remove these observers from every name table.
+        NSArray<NSString*>* copiedAllKeys = [[_observers allKeys] copy];
```
Comment (aballway) [inline Frameworks/Foundation/NSNotificationCenter.mm]: nit: prefer StrongId and just cast for the loop

File: Frameworks/Foundation/NSNotificationCenter.mm [hunk 4]
```diff
@@ -14,227 +14,289 @@
...
+    std::vector<StrongId<_NSNotificationReceiver>> validReceivers{ 0 };
+    @synchronized(self) {
+        NSMutableSet<_NSNotificationReceiver*>* receivers = [self _receiverSetForNotificationName:name createIfMissing:NO];
+        if (!receivers) {
+            return;
+        }
+
+        NSObject* sender = [notification object];
+        validReceivers.reserve([receivers count]);
+        for (_NSNotificationReceiver* receiver in receivers) {
```
Comment (aballway) [inline Frameworks/Foundation/NSNotificationCenter.mm]: objectsPassingTest seems to fit the bill better

File: Frameworks/Foundation/NSNotificationCenter.mm [hunk 5]
```diff
@@ -14,227 +14,289 @@
...
+    }
+}
+
+- (void)_addObserver:(id)observer selector:(SEL)selector name:(NSString*)name object:(id)object withOwningReference:(BOOL)owningReference {
+    if (!name || !observer || !selector) {
         return;
     }
 
-    NSNotificationReceiver* newObserver = [NSNotificationReceiver new];
+    _NSNotificationReceiver* newReceiver = [_NSNotificationReceiver new];
```
Comment (aballway) [inline Frameworks/Foundation/NSNotificationCenter.mm]: nit: StrongId?

File: Frameworks/Foundation/NSNotificationCenter.mm [hunk 6]
```diff
@@ -14,227 +14,289 @@
...
+
+    newReceiver->observer = observer; // If owningReference, observer bears a +1 internal retain count.
```
Comment (aballway) [inline Frameworks/Foundation/NSNotificationCenter.mm]: nit: this could be rolled into a factory method

File: Frameworks/Foundation/NSNotificationCenter.mm [hunk 7]
```diff
@@ -14,227 +14,289 @@
...
-    newObserver->valid = true;
-
-    [arrayForObservers(self, name, true) addObject:newObserver];
-    [newObserver release];
-
-    return newObserver->object;
+    // The documentation states that this method returns an opaque object that acts as the observer, and
+    // the returned observer should be able to be removed with `removeObserver:`.
+    // To make that work, we must register this observer object just like a normal observer.
+    _NSNotificationBlockObserver* blockObserver = [[_NSNotificationBlockObserver alloc] initWithBlock:block queue:queue];
```
Comment (aballway) [inline Frameworks/Foundation/NSNotificationCenter.mm]: should this be autoreleased?

File: tests/unittests/Foundation/NSNotificationTests.mm (hunk 1 above)
Comment (aballway) [inline tests/unittests/Foundation/NSNotificationTests.mm]: Idk these are pretty great imo.  gives the file some much needed texture

File: tests/unittests/Foundation/NSNotificationTests.mm [hunk 8]
```diff
@@ -15,7 +15,54 @@
 //******************************************************************************
 
 #include <TestFramework.h>
+#import <Starboard/SmartTypes.h>
 #import <Foundation/Foundation.h>
+
+// Avoid "property access result unused" warnings by _consume-ing the value of a property accessor.
+template <typename... T>
+static inline void _consume(T&&...) {
```
Comment (aballway) [inline tests/unittests/Foundation/NSNotificationTests.mm]: nit: would prefer an old fashioned macro to disable/enable warnings for this file

File: tests/unittests/Foundation/NSNotificationTests.mm [hunk 9]
```diff
@@ -15,7 +15,54 @@
...
+- (id)init {
+    // NSNotification subclasses are barred from calling [super init].
+    return self;
+}
+@end
+
+TEST(NSNotification, InvalidSubclassThrows) {
+    EXPECT_ANY_THROW([BadNSNotificationSubclass notificationWithName:@"name" object:nil userInfo:nil]);
+
+    BadNSNotificationSubclass* bad = [[BadNSNotificationSubclass alloc] init];
```
Comment (aballway) [inline tests/unittests/Foundation/NSNotificationTests.mm]: nit: StrongId?

File: tests/unittests/Foundation/NSNotificationTests.mm [hunk 10]
```diff
@@ -15,7 +15,54 @@
...
+    EXPECT_ANY_THROW(_consume(bad.userInfo));
+    EXPECT_ANY_THROW(_consume(bad.object));
+
+    [bad release];
+}
+
+TEST(NSNotification, CanEncodeAndDecode) {
+    NSNotification* notification = [NSNotification notificationWithName:@"Name1" object:@"Object1" userInfo:@{ @"Key1" : @"Value1" }];
+    NSData* data = nil;
+    ASSERT_NO_THROW(data = [NSKeyedArchiver archivedDataWithRootObject:notification]);
```
Comment (aballway) [inline tests/unittests/Foundation/NSNotificationTests.mm]: 👍

File: tests/unittests/Foundation/NSNotificationTests.mm [hunk 11]
```diff
@@ -28,5 +75,404 @@ - (void)dealloc {
...
 
 TEST(NSNotificationCenter, PostNotificationFromDealloc) {
-    TestObjectA* obj = [[TestObjectA new] autorelease];
+    @autoreleasepool {
+        TestObjectA* obj = [[TestObjectA new] autorelease];
+    }
+}
+
+TEST(NSNotificationCenter, BlockRegistrationDeregistration) {
+    static NSString* s_TestNotificationName = @(GetTestFullName().c_str());
```
Comment (aballway) [inline tests/unittests/Foundation/NSNotificationTests.mm]: https://i.imgur.com/X4PnV.gif

File: tests/unittests/Foundation/NSNotificationTests.mm [hunk 12]
```diff
@@ -28,5 +75,404 @@ - (void)dealloc {
...
+        }
+    });
+
+    dispatch_semaphore_signal(sem);
+    dispatch_semaphore_signal(sem); // Trigger starts
+
+    dispatch_group_wait(group, DISPATCH_TIME_FOREVER); // Wait for completion.
+
+    EXPECT_LT(0, observer.totalHits);
+    ASSERT_GE(100 * 100, observer.totalHits);
```
Comment (aballway) [inline tests/unittests/Foundation/NSNotificationTests.mm]: super nit: short comment about what this number represents/why testing

File: tests/unittests/Foundation/NSNotificationTests.mm [hunk 13]
```diff
@@ -28,5 +75,404 @@ - (void)dealloc {
...
+        }
+    });
+
+    dispatch_semaphore_signal(sem);
+    dispatch_semaphore_signal(sem);
+    dispatch_semaphore_signal(sem); // Trigger starts
+
+    dispatch_group_wait(group, DISPATCH_TIME_FOREVER); // Wait for completion.
+
+    // Between 0 and 10000 notifications should have fired; this stress test simply proves that we can manipulate the three states
```
Comment (aballway) [inline tests/unittests/Foundation/NSNotificationTests.mm]: oh here it is. Copy this lil fella above

File: Frameworks/Foundation/NSNotification.mm [hunk 14]
```diff
@@ -33,54 +51,98 @@ + (NSNotification*)notificationWithName:(NSString*)name object:(id)obj userInfo:
...
 - (instancetype)initWithCoder:(NSCoder*)decoder {
-    UNIMPLEMENTED();
-    return StubReturn();
+    Class notificationClass = [self class];
+    [self release];
+
+    NSString* name = [decoder decodeObjectForKey:s_NSNotificationKeyName];
+    id object = [decoder decodeObjectForKey:s_NSNotificationKeyObject];
+    NSDictionary* userInfo = [decoder decodeObjectForKey:s_NSNotificationKeyUserInfo];
+    return [[notificationClass alloc] initWithName:name object:object userInfo:userInfo];
```
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSNotification.mm]: Nah; self is simply a local that's used for the scope of this method.
`[self release]` is common in class clusters; we need to discard the instance of the toplevel class that could have been allocated and replace it with one from a factory.

Optimization opportunity: Since we know that `[self alloc]` returns an `_NSConcreteNotification`, we could set the members directly. **However**: this method gets called for all NSNotification subclasses that don't override it... so we can't do that.

File: Frameworks/Foundation/NSNotificationCenter.mm [hunk 15]
```diff
@@ -14,227 +14,289 @@
...
+@interface _NSNotificationBlockObserver : NSObject {
+    // Unlike _NSNotificationReceiver below, this object owns strong references to block and queue.
+    // Block notifications are commonly implemented with a weak handle to its owner since the block
+    // can itself cause a retain cycle.
+    StrongId<void (^)(NSNotification* note)> _block;
+    StrongId<NSOperationQueue> _queue;
 }
 @end
+@implementation _NSNotificationBlockObserver
+- (instancetype)initWithBlock:(void (^)(NSNotification* note))block queue:(NSOperationQueue*)queue {
```
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSNotificationCenter.mm]: It doesn't really matter; it's visible to clang, and that's all that matters.

File: Frameworks/Foundation/NSNotificationCenter.mm (hunk 2 above)
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSNotificationCenter.mm]: good catch! 💢

File: Frameworks/Foundation/NSNotificationCenter.mm (hunk 4 above)
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSNotificationCenter.mm]: Not in this case. We want strict control over the lifetimes of these receivers, and we don't want to vend them into an autorelease pool. `objectsPassingTest:` will vend them into an autorelease pool.

File: Frameworks/Foundation/NSNotificationCenter.mm (hunk 5 above)
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSNotificationCenter.mm]: I am very sad that StrongId requires a two-step init for consuming a +1 reference.

File: Frameworks/Foundation/NSNotificationCenter.mm (hunk 6 above)
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSNotificationCenter.mm]: It could, sure.

File: Frameworks/Foundation/NSNotificationCenter.mm (hunk 7 above)
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSNotificationCenter.mm]: no. I'll document this better, but `withOwningReference:YES` below consumes it.

File: tests/unittests/Foundation/NSNotificationTests.mm (hunk 8 above)
Comment (DHowett-MSFT) [inline tests/unittests/Foundation/NSNotificationTests.mm]: I have a sudden aversion to blanket disabling this warning, but I don't know why.

File: tests/unittests/Foundation/NSNotificationTests.mm (hunk 13 above)
Comment (DHowett-MSFT) [inline tests/unittests/Foundation/NSNotificationTests.mm]: r+

**Comment by DHowett-MSFT** [comment]
@aballway You should give me the :x: so I can then go dismiss it out of anger :grin:

File: Frameworks/Foundation/NSNotificationCenter.mm [hunk 16]
```diff
@@ -209,22 +209,31 @@ - (void)postNotificationName:(NSString*)name object:(NSObject*)sender userInfo:(
  @Status Interoperable
 */
 - (void)postNotification:(NSNotification*)notification {
+    if (!notification) {
```
Comment (aballway) [inline Frameworks/Foundation/NSNotificationCenter.mm]: nit: THROW_NS_IF_NULL

File: Frameworks/Foundation/NSNotificationCenter.mm [hunk 17]
```diff
@@ -240,12 +249,15 @@ - (void)postNotification:(NSNotification*)notification {
 
 - (void)_addObserver:(id)observer selector:(SEL)selector name:(NSString*)name object:(id)object withOwningReference:(BOOL)owningReference {
     if (!name || !observer || !selector) {
+        if (owningReference) {
```
Comment (aballway) [inline Frameworks/Foundation/NSNotificationCenter.mm]: 👍

File: Frameworks/Foundation/NSNotificationCenter.mm [hunk 18]
```diff
@@ -14,227 +14,307 @@
...
+    [_allReceivers minusSet:receivers];
 
-        if (!observer->valid) {
-            [observer release];
-            continue;
+    // ... and the name lookup tables.
+    if (name) {
+        // Fast path: remove these observers from the provided name's table.
+        StrongId<NSMutableSet<_NSNotificationReceiver*>> nameReceivers = [self _receiverSetForNotificationName:name createIfMissing:NO];
+        if (!nameReceivers) {
```
Comment (rajsesh-msft) [inline Frameworks/Foundation/NSNotificationCenter.mm]: >nameReceivers [](start = 13, length = 13)

at this point, _observers cannot contain "name" notifications, correct? might be worth asserting here.

File: Frameworks/Foundation/NSNotificationCenter.mm [hunk 19]
```diff
@@ -14,227 +14,307 @@
...
-        if (!observer->block) {
-            [observer->object performSelector:observer->selector withObject:notification];
-        } else {
-            observer->block(notification);
+        [nameReceivers minusSet:receivers];
+
+        if ([nameReceivers count] == 0) {
+            // This can release nameReceivers; it will be retained for the scope of this method.
+            [_observers removeObjectForKey:name];
         }
```
Comment (rajsesh-msft) [inline Frameworks/Foundation/NSNotificationCenter.mm]: nit:  code block repeated once the nameReceivers are found in the if and else part.

File: Frameworks/Foundation/NSNotificationCenter.mm (hunk 18 above)
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSNotificationCenter.mm]: It shouldn't happen, but it's also not catastrophic if it does. It'd mean that `@synchronized` is terribly broken, but we'd have farther-reaching consequences if that were true.

File: Frameworks/Foundation/NSNotificationCenter.mm (hunk 19 above)
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSNotificationCenter.mm]: I'd like to keep these separate; if the name-free removals are a performance issue, there're some opportunities we can take that don't apply to the other codepath.
