### PR TITLE
NSURLSession should throw for creating tasks with nil request or resume data

### LINKED ISSUE #1844: [x86] [ARM] WOCCatalog Foundation Tests - In URL Session, clicking Resume crashes the app
Latest master build - with 1701 payload

### PR DESCRIPTION
**Pull request by aballway**
Fixes #1844

### CODE REVIEW

**Comment by DHowett-MSFT** [comment]
Test this on the reference platform. :clock1130:

**Comment by aballway** [comment]
It passes :D

---
In reply to: [275760658](https://github.com/Microsoft/WinObjC/pull/1860#issuecomment-275760658) [](ancestors = 275760658)

File: Frameworks/Foundation/NSURLSession.mm [hunk 1]
```diff
@@ -33,6 +33,21 @@
 
 #import <StubReturn.h>
 
+#define THROW_IF_NULL_REQUEST(request)                                         \
```
Comment (msft-Jeyaram) [inline Frameworks/Foundation/NSURLSession.mm]: >THROW_IF_NULL_REQUEST [](start = 8, length = 21)

shocking, AJ using macros.

File: Frameworks/Foundation/NSURLSession.mm [hunk 2]
```diff
@@ -33,6 +33,21 @@
...
+          exceptionWithName:NSInvalidArgumentException                         \
+                     reason:[NSString                                          \
+                                stringWithFormat:@"*** %@ Cannot create data " \
+                                                 @"task without request or "   \
+                                                 @"resume data",               \
+                                                 NSStringFromSelector(_cmd)]   \
+                   userInfo:nil];                                              \
+    }                                                                          \
+}                                                                              \
+  while (false)
```
Comment (msft-Jeyaram) [inline Frameworks/Foundation/NSURLSession.mm]: >false [](start = 9, length = 5)

nit: 0 to be in par

File: tests/UnitTests/Foundation/NSURLSessionTests.mm [hunk 3]
```diff
@@ -0,0 +1,36 @@
...
+// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
+// THE SOFTWARE.
+//
+//******************************************************************************
+
+#import <Foundation/Foundation.h>
+#import <TestFramework.h>
+#import <Starboard/SmartTypes.h>
+
+TEST(NSURLSession, ShouldThrowForNilRequest) {
```
Comment (msft-Jeyaram) [inline tests/UnitTests/Foundation/NSURLSessionTests.mm]: test these on OSX 10.12 please.

Comment (msft-Jeyaram) [inline tests/UnitTests/Foundation/NSURLSessionTests.mm]: Which version did you already test on?

---
In reply to: [98281815](https://github.com/Microsoft/WinObjC/pull/1860#discussion_r98281815) [](ancestors = 98281815)

File: tests/UnitTests/Foundation/NSURLSessionTests.mm [hunk 4]
```diff
@@ -0,0 +1,36 @@
...
+// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
+// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
+// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
+// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
+// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
+// THE SOFTWARE.
+//
+//******************************************************************************
+
+#import <Foundation/Foundation.h>
```
Comment (msft-Jeyaram) [inline tests/UnitTests/Foundation/NSURLSessionTests.mm]: nit: the whole Foundation?

File: Frameworks/Foundation/NSURLSession.mm (hunk 1 above)
Comment (msft-Jeyaram) [inline Frameworks/Foundation/NSURLSession.mm]: i have the urge to say, since this macro is internal to this function it should have some signature indication that.

File: tests/UnitTests/Foundation/NSURLSessionTests.mm (hunk 3 above)
Comment (aballway) [inline tests/UnitTests/Foundation/NSURLSessionTests.mm]: 10.11
