### PR TITLE
Fix annotations in the headers.

### LINKED ISSUE #2555: foundation and core graphics headers have incorrect annotation macros
Overriding Interoperable status for NSOrderedSet::-indexOfObject:inSortedRange:options:usingComparator: method due to STUB_METHOD attribute.
Overriding Interoperable status for NSOrderedSet::-indexOfObjectAtIndexes:options:passingTest: method due to STUB_METHOD attribute.
Overriding Interoperable status for NSOrderedSet::-indexOfObjectPassingTest: method due to STUB_METHOD attribute.
Overriding Interoperable status for NSOrderedSet::-indexesOfObjectsPassingTest: method due to STUB_METHOD attribute.
Overriding Interoperable status for NSOrderedSet::-sortedArrayUsingComparator: method due to STUB_METHOD attribute.
Overriding status for NSOrderedSet::description property due to STUB_PROPERTY attribute.
Overriding Caveat status for NSURL::+URLByResolvingBookmarkData:options:relativeToURL:bookmarkDataIsStale:error: method due to STUB_METHOD attribute.
Overriding Caveat status for NSURL::-initByResolvingBookmarkData:options:relativeToURL:bookmarkDataIsStale:error: method due to STUB_METHOD attribute.
Overriding Interoperable status for CGContextGetPathCurrentPoint method due to STUB_METHOD attribute.
Overriding Interoperable status for CGContextPathContainsPoint method due to STUB_METHOD attribute.
Overriding Interoperable status for CGContextShowText method due to STUB_METHOD attribute.
Overriding Interoperable status for CGGradientGetTypeID method due to STUB_METHOD attribute.
Overriding Interoperable status for CGPathAddRects method due to STUB_METHOD attribute.
Overriding Interoperable status for CGPatternGetTypeID method due to STUB_METHOD attribute.

### PR DESCRIPTION
**Pull request by rajsesh-msft**
Fix annotations in foundation and CG headers.

Fixes #2555

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/winobjc/2556)

### CODE REVIEW

File: include/CoreGraphics/CGContext.h [hunk 1]
```diff
@@ -193,11 +193,11 @@ COREGRAPHICS_EXPORT void CGContextStrokeEllipseInRect(CGContextRef c, CGRect rec
 COREGRAPHICS_EXPORT void CGContextStrokeLineSegments(CGContextRef c, const CGPoint* points, size_t count);
 COREGRAPHICS_EXPORT bool CGContextIsPathEmpty(CGContextRef c);
 
-COREGRAPHICS_EXPORT CGPoint CGContextGetPathCurrentPoint(CGContextRef c) STUB_METHOD;
```
Comment (msft-Jeyaram) [inline include/CoreGraphics/CGContext.h]: Does this mean these APIs don't have tests? The compiler would have warned the usage of these if they were marked stub.

Comment (rajsesh-msft) [inline include/CoreGraphics/CGContext.h]: @msft-Jeyaram good question.  The answer is - very likely yes.  At least CGContextGetPathCurrentPoint for example - but it is a very thin wrapper around a different API - CGPathGetCurrentPoint.
