### PR TITLE
making NSCompoundPredicate tests compatible with reference platform

### LINKED ISSUE #747: NSCompoundPredicate.ArchiveAndUnarchiveObject fails on OSX
[ RUN      ] NSCompoundPredicate.ArchiveAndUnarchiveObject
unknown file: Failure
Unknown C++ exception thrown in the test body.
[  FAILED  ] NSCompoundPredicate.ArchiveAndUnarchiveObject (1 ms)

### PR DESCRIPTION
**Pull request by msft-Jeyaram**
It seems as on reference platform predicate classes are not concrete instance, thus doing an alloc/init will not return a copy-able object.
Since our backing implementation is different, it gives us the freedom to do the that.

Changing the test to be compatible with the reference platform.

fix #747 #704

### CODE REVIEW

**Comment by ms-jihua** [comment]
:shipit:

File: tests/unittests/Foundation/NSCompoundPredicateTests.m [hunk 1]
```diff
@@ -18,20 +18,17 @@
 #import <Foundation/Foundation.h>
 
 TEST(NSCompoundPredicate, Init) {
-    NSCompoundPredicate* compoundPredicate = [[NSCompoundPredicate alloc] init];
+    NSCompoundPredicate* compoundPredicate = [NSCompoundPredicate notPredicateWithSubpredicate:[NSPredicate predicateWithFormat:@"1<3"]];
```
Comment (DHowett-MSFT) [inline tests/unittests/Foundation/NSCompoundPredicateTests.m]: >"1<3 [](start = 129, length = 4)

Is `TRUE` a valid predicate? If so, it might be better to use it.

**Comment by DHowett-MSFT** [comment]
:shipit:

**Comment by rajsesh-msft** [comment]
:shipit:

**Comment by msft-Jeyaram** [comment]
In CI Build

**Comment by msft-Jeyaram** [comment]
CI Build passed.
