### PR TITLE
Fix Affine Transform in CGPath

### LINKED ISSUE #1179: Fix Affine Transform in CGPath
Affine Transform is broken for a few methods that require access to the individual figures of a D2DGeometry. This includes the function CGPathAddPath.

### PR DESCRIPTION
**Pull request by MSFTFox**
Implement the CGPathCreateMutableCopyByTransformingPath API which allows CGContext to properly transform any paths in conjunction with the User-To-Device transform. Unit tests show identical output.

Fixes #1179

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/winobjc/1550)

### CODE REVIEW

File: Frameworks/CoreGraphics/CGPath.mm [hunk 1]
```diff
@@ -754,21 +754,34 @@ CGPathRef CGPathCreateCopyByStrokingPath(
...
- @Status Stub
- @Notes
+ @Status Interoperable
 */
 CGMutablePathRef CGPathCreateMutableCopyByTransformingPath(CGPathRef path, const CGAffineTransform* transform) {
-    UNIMPLEMENTED();
-    return StubReturn();
+    RETURN_NULL_IF(!path);
+
+    if (transform) {
```
Comment (DHowett-MSFT) [inline Frameworks/CoreGraphics/CGPath.mm]: nit: fold these together? `if (transform && !CGAffine...`

File: Frameworks/CoreGraphics/CGPath.mm [hunk 2]
```diff
@@ -754,21 +754,34 @@ CGPathRef CGPathCreateCopyByStrokingPath(
...
+        if (CGAffineTransformEqualToTransform(*transform, CGAffineTransformIdentity)) {
+            return CGPathCreateMutableCopy(path);
+        }
+
+        CGMutablePathRef transformedPath = CGPathCreateMutable();
+        path->ClosePath();
+
+        FAIL_FAST_IF_FAILED(transformedPath->AddGeometryToPathWithTransformation(path->GetPathGeometry().Get(), transform));
```
Comment (DHowett-MSFT) [inline Frameworks/CoreGraphics/CGPath.mm]: It bothers me a bit that GetPathGeometry returns a `ComPtr<ID2D1Geometry>`; it's an unnecessary +1/-1/+1 for this case (and an unnecessary +1/-1 for every other case where you call it (!)

File: Frameworks/CoreGraphics/CGPath.mm [hunk 3]
```diff
@@ -754,21 +754,34 @@ CGPathRef CGPathCreateCopyByStrokingPath(
 }
 
 /**
- @Status Stub
- @Notes
+ @Status Caveat
```
Comment (rajsesh-msft) [inline Frameworks/CoreGraphics/CGPath.mm]: I think this should be interoperable.  It would be a caveat if ref plat created mutable copy and we didn't.
