### PR TITLE
Fix NSAttributedString tests on OSX

### LINKED ISSUE #739: NSAttributedString tests fail on OSX
We seem to have gotten a lot of ranges incorrect:

[ RUN      ] NSAttributedString.CoalesceOverlapAfter
Foundation/NSAttributedStringTests.mm:32: Failure
Value of: outRange.length
  Actual: 2
Expected: expectedLength
Which is: 3
[  FAILED  ] NSAttributedString.CoalesceOverlapAfter (0 ms)
[ RUN      ] NSAttributedString.CoalesceAdjacentAfter
Foundation/NSAttributedStringTests.mm:32: Failure
Value of: outRange.length
  Actual: 2
Expected: expectedLength
Which is: 4
[  FAILED  ] NSAttributedString.CoalesceAdjacentAfter (0 ms)
[ RUN      ] NSAttributedString.CoalesceOverlapBefore
Foundation/NSAttributedStringTests.mm:32: Failure
Value of: outRange.length
  Actual: 1
Expected: expectedLength
Which is: 3
[  FAILED  ] NSAttributedString.CoalesceOverlapBefore (0 ms)
[ RUN      ] NSAttributedString.CoalesceAdjacentBefore
Foundation/NSAttributedStringTests.mm:32: Failure
Value of: outRange.length
  Actual: 2
Expected: expectedLength
Which is: 4
[  FAILED  ] NSAttributedString.CoalesceAdjacentBefore (1 ms)
[ RUN      ] NSAttributedString.CoalesceComplex
Foundation/NSAttributedStringTests.mm:32: Failure
Value of: outRange.length
  Actual: 2
Expected: expectedLength
Which is: 6
[  FAILED  ] NSAttributedString.CoalesceComplex (1 ms)

[ RUN      ] NSAttributedString.OverwriteAfter
Foundation/NSAttributedStringTests.mm:32: Failure
Value of: outRange.length
  Actual: 1
Expected: expectedLength
Which is: 2
[  FAILED  ] NSAttributedString.OverwriteAfter (1 ms)
[ RUN      ] NSAttributedString.OverwriteBefore
Foundation/NSAttributedStringTests.mm:32: Failure
Value of: outRange.length
  Actual: 1
Expected: expectedLength
Which is: 2
[  FAILED  ] NSAttributedString.OverwriteBefore (0 ms)

[ RUN      ] NSAttributedString.EnumerateAttribute
Foundation/NSAttributedStringTests.mm:551: Failure
Value of: timesEnumerated
  Actual: 1
Expected: 0
[  FAILED  ] NSAttributedString.EnumerateAttribute (0 ms)
[ RUN      ] NSAttributedString.EnumerateAttributeAndChangeLength
[       OK ] NSAttributedString.EnumerateAttributeAndChangeLength (0 ms)
[ RUN      ] NSAttributedString.EnumerateAttributes
Foundation/NSAttributedStringTests.mm:696: Failure
Value of: timesEnumerated
  Actual: 1
Expected: 0
[  FAILED  ] NSAttributedString.EnumerateAttributes (0 ms)

### PR DESCRIPTION
**Pull request by ms-jihua**
- Disabled Coalesce and Overwrite tests on OSX: these occur immediately on iOS, but not on OSX
  - Corrected [NSAttributedString enumerate...] behavior to match OSX/iOS, updated enumeration tests

Fixes #739

### CODE REVIEW

File: tests/unittests/Foundation/NSAttributedStringTests.mm [hunk 1]
```diff
@@ -547,8 +554,10 @@ void assertAttributeAt(
                      options:NSAttributedStringEnumerationReverse
                   usingBlock:^void(NSDictionary* val, NSRange range, BOOL* stop) {
                       ++timesEnumerated;
+                      ASSERT_EQ(0, [val count]);
+                      ASSERT_TRUE(NSEqualRanges(NSMakeRange(1, 3), range));
                   }];
-    ASSERT_EQ(0, timesEnumerated);
```
Comment (mnithish) [inline tests/unittests/Foundation/NSAttributedStringTests.mm]: >ASSERT_EQ(0, timesEnumerated); [](start = 4, length = 30)

Interesting, how did this test pass until now?

Comment (ms-jihua) [inline tests/unittests/Foundation/NSAttributedStringTests.mm]: Our implementation of enumerateAttribute was incorrect - it did not enumerate over ranges where there were no attributes. That was corrected in this CR.

---
In reply to: [73620275](https://github.com/Microsoft/WinObjC/pull/819#discussion_r73620275) [](ancestors = 73620275)

Comment (mnithish) [inline tests/unittests/Foundation/NSAttributedStringTests.mm]: Ah started looking at the tests first

---
In reply to: [73620370](https://github.com/Microsoft/WinObjC/pull/819#discussion_r73620370) [](ancestors = 73620370,73620275)

**Comment by rajsesh-msft** [comment]
:shipit:
