### PR TITLE
Fix edge condition in lineFragmentRectForProposedRect

### LINKED ISSUE #1123: NSTextContainer lineFragmentRectForProposedRect remainingRect
lineFragmentRectForProposedRect: does not handle the edge case of multiple exclusion paths properly when computing the remainingRect.

### LINKED ISSUE #1143: CGD2D - _CGPathFitRect and CTFramesetterCreateFrame Broken
As a part of the work with CGPath some functions have broken since they try to access information inside of the CGPath which is being removed. These functions should be re-enabled or replaced as a part of the CGPath work.

### PR DESCRIPTION
**Pull request by aballway**
Handle case where multiple exclusion zones are on the same line and overlap.  Also removes ScanlineCalculator and _CGPathFitRect.

Fixes #1123
Fixes #1143 

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/winobjc/1398)

### CODE REVIEW

File: Frameworks/UIKit/NSTextContainer.mm [hunk 1]
```diff
@@ -75,25 +119,69 @@ - (CGRect)lineFragmentRectForProposedRect:(CGRect)proposed
...
+
+            // TODO 1394: Convert to CGPathContainsPoint for CGD2D
+            // Find the leftmost and rightmost points of the exclusion zone intersecting the same horizontal region as the proposed rect
+            lineIntersection.origin.x = __GetXPositionIntersectingZone(lineIntersection, _exclusionContexts[i].get(), padding);
+            lineIntersection.size.width =
+                __GetXPositionIntersectingZone({ { lineIntersection.origin.x + lineIntersection.size.width, lineIntersection.origin.y },
+                                                 lineIntersection.size },
+                                               _exclusionContexts[i].get(),
+                                               -padding) -
+                lineIntersection.origin.x;
```
Comment (memontic-ms) [inline Frameworks/UIKit/NSTextContainer.mm]: Please help clang

**Comment by rajsesh-msft** [comment]
How are you testing any of this works?

**Comment by aballway** [comment]
Currently just through the text layout in WOCCatalog.  I'll add some unit tests :D

---
In reply to: [261048109](https://github.com/Microsoft/WinObjC/pull/1398#issuecomment-261048109) [](ancestors = 261048109)

File: build/CoreGraphics/dll/CoreGraphics.def [hunk 2]
```diff
@@ -233,6 +233,7 @@ LIBRARY CoreGraphics
         CGContextSetDirty
         CGContextGetBacking
         CGContextDrawGlyphRun
+        CGContextIsPointInPath
```
Comment (aballway) [inline build/CoreGraphics/dll/CoreGraphics.def]: It's an existing function, and will be removed with the CGD2D changes

---
In reply to: [88314147](https://github.com/Microsoft/WinObjC/pull/1398#discussion_r88314147) [](ancestors = 88314147)

File: Frameworks/UIKit/NSLayoutManager.mm [hunk 3]
```diff
@@ -128,17 +127,16 @@ - (void)__layoutAllText {
...
+            woc::unique_cf<CGPathRef> path{ CGPathCreateWithRect(CGRectMake(0, 0, rect.size.width, lineHeight), nullptr) };
+            woc::unique_cf<CTFrameRef> frame{
+                CTFramesetterCreateFrame(framesetter.get(), { stringIndex, lastIndex - stringIndex }, path.get(), nullptr)
+            };
 
             // Create line to fit as much text as possible in given rect
-            CTLineRef fitLine = static_cast<CTLineRef>([[[static_cast<NSArray*>(CTFrameGetLines(frame)) firstObject] retain] autorelease]);
-            CFRelease(frame);
+            woc::unique_cf<CTLineRef> fitLine{ static_cast<CTLineRef>(
+                [[static_cast<NSArray*>(CTFrameGetLines(frame.get())) firstObject] retain]) };
```
Comment (msft-Jeyaram) [inline Frameworks/UIKit/NSLayoutManager.mm]: in all honestly this looks gruesome to read. uh with all those static_casts :(

File: Frameworks/UIKit/NSTextContainer.mm [hunk 4]
```diff
@@ -75,25 +119,69 @@ - (CGRect)lineFragmentRectForProposedRect:(CGRect)proposed
...
-    if (_exclusionPaths != nil) {
-        for (UIBezierPath* path in(NSArray*)_exclusionPaths) {
-            CGRect shapeRect = _CGPathFitRect(path.CGPath, ret, _size, self.lineFragmentPadding);
-            ret = CGRectIntersection(shapeRect, ret);
+    std::vector<CGRect> exclusionRectsForHorizontal{};
+    for (size_t i = 0; i < _exclusionPathBoundingRects.size(); ++i) {
+        // If our proposed area doesn't intersect the bounding box of the exclusion zone at all, no need to compare against it
+        if (proposed.origin.y < _exclusionPathBoundingRects[i].origin.y + _exclusionPathBoundingRects[i].size.height &&
+            proposed.origin.y + proposed.size.height > _exclusionPathBoundingRects[i].origin.y &&
+            proposed.origin.x < _exclusionPathBoundingRects[i].origin.x + _exclusionPathBoundingRects[i].size.width) {
```
Comment (msft-Jeyaram) [inline Frameworks/UIKit/NSTextContainer.mm]: parenthesis (which would make this so much easier to read)

File: Frameworks/UIKit/NSTextContainer.mm [hunk 5]
```diff
@@ -75,25 +119,69 @@ - (CGRect)lineFragmentRectForProposedRect:(CGRect)proposed
...
+            CGRect lineIntersection{ { _exclusionPathBoundingRects[i].origin.x, proposed.origin.y },
+                                     { _exclusionPathBoundingRects[i].size.width, proposed.size.height } };
```
Comment (msft-Jeyaram) [inline Frameworks/UIKit/NSTextContainer.mm]: new line between, hard to read with everything clumped.

File: Frameworks/UIKit/NSTextContainer.mm [hunk 6]
```diff
@@ -75,25 +119,69 @@ - (CGRect)lineFragmentRectForProposedRect:(CGRect)proposed
                             remainingRect:(CGRect*)remainingRect {
     CGRect totalRect = CGRectMake(0, 0, _size.width, _size.height);
     CGRect ret = CGRectIntersection(proposed, totalRect);
+    if ([_exclusionPaths count] == 0L || ret.size.width <= 0) {
+        return ret;
+    }
+
+    CGFloat padding = self.lineFragmentPadding;
```
Comment (msft-Jeyaram) [inline Frameworks/UIKit/NSTextContainer.mm]: > self.lineFragmentPadding; [](start = 21, length = 26)

you have a mix usage of accessing though self and direct access via _xxxxx
standardize.

**Comment by msft-Jeyaram** [comment]
:clock1:

File: Frameworks/UIKit/NSTextContainer.mm [hunk 7]
```diff
@@ -75,25 +119,69 @@ - (CGRect)lineFragmentRectForProposedRect:(CGRect)proposed
...
+    std::sort(exclusionRectsForHorizontal.begin(), exclusionRectsForHorizontal.end(), [](CGRect a, CGRect b) {
+        return a.origin.x < b.origin.x;
+    });
+    ret = __FirstPossibleRectForProposed(ret, exclusionRectsForHorizontal, padding, _size.width);
+
+    if (remainingRect) {
+        CGFloat newXPosition = ret.origin.x + ret.size.width + 2 * padding;
+        if (newXPosition < _size.width) {
+            *remainingRect =
+                __FirstPossibleRectForProposed(CGRectMake(newXPosition, ret.origin.y, _size.width - newXPosition, ret.size.height),
```
Comment (aballway) [inline Frameworks/UIKit/NSTextContainer.mm]: It's in UIKit, and is a private (should be static whoops) helper

File: Frameworks/UIKit/NSTextContainer.mm [hunk 8]
```diff
@@ -75,25 +119,69 @@ - (CGRect)lineFragmentRectForProposedRect:(CGRect)proposed
...
+                                               exclusionRectsForHorizontal,
+                                               padding,
+                                               _size.width);
         }
     }
```
Comment (aballway) [inline Frameworks/UIKit/NSTextContainer.mm]: It's just two ifs... and I prefer this to early returns anyways

File: Frameworks/UIKit/NSTextContainer.mm [hunk 9]
```diff
@@ -75,25 +119,69 @@ - (CGRect)lineFragmentRectForProposedRect:(CGRect)proposed
...
+    // Sort by X origin to prevent skipping possible areas not covered by an exclusion zone
+    std::sort(exclusionRectsForHorizontal.begin(), exclusionRectsForHorizontal.end(), [](CGRect a, CGRect b) {
+        return a.origin.x < b.origin.x;
+    });
+    ret = __FirstPossibleRectForProposed(ret, exclusionRectsForHorizontal, padding, _size.width);
+
+    if (remainingRect) {
+        CGFloat newXPosition = ret.origin.x + ret.size.width + 2 * padding;
+        if (newXPosition < _size.width) {
+            *remainingRect =
```
Comment (aballway) [inline Frameworks/UIKit/NSTextContainer.mm]: remainingRect is zeroed out in the beginning of the method, but looking at it again it makes more sense to do so here

File: Frameworks/UIKit/NSTextContainer.mm (hunk 8 above)
Comment (msft-Jeyaram) [inline Frameworks/UIKit/NSTextContainer.mm]: yes it's two ifs and rather than going with preference, we should look at code readability.
Most of this code is already heavy and it would make sense reduce the clutter. 

---
In reply to: [88341543](https://github.com/Microsoft/WinObjC/pull/1398#discussion_r88341543) [](ancestors = 88341543)

Comment (aballway) [inline Frameworks/UIKit/NSTextContainer.mm]: I think that adding another return here would make it harder to parse, I prefer it in a sense that I find it easier to read and understand what the code is doing.

File: Frameworks/UIKit/NSTextContainer.mm (hunk 7 above)
Comment (msft-Jeyaram) [inline Frameworks/UIKit/NSTextContainer.mm]: >__FirstPossibleRectForProposed [](start = 16, length = 30)

reading this makes me think that it's defined in here. given __ usually means very restricted internal usage.
More appropriate would be _xxFirstPoxxx

File: Frameworks/UIKit/NSTextContainer.mm (hunk 5 above)
Comment (aballway) [inline Frameworks/UIKit/NSTextContainer.mm]: unfortunately clang format is really opinionated about there not being a newline here :/ Added a comment for readability

File: Frameworks/UIKit/NSTextContainer.mm (hunk 7 above)
Comment (aballway) [inline Frameworks/UIKit/NSTextContainer.mm]: It is defined in this file

File: Frameworks/UIKit/NSLayoutManager.mm [hunk 10]
```diff
@@ -128,15 +127,13 @@ - (void)__layoutAllText {
...
-            CGPathRelease(path);
+            woc::unique_cf<CGPathRef> path{ CGPathCreateWithRect(CGRectMake(0, 0, rect.size.width, lineHeight), nullptr) };
+            woc::unique_cf<CTFrameRef> frame{
+                CTFramesetterCreateFrame(framesetter.get(), { stringIndex, lastIndex - stringIndex }, path.get(), nullptr)
+            };
 
             // Create line to fit as much text as possible in given rect
-            CTLineRef fitLine = static_cast<CTLineRef>([[[static_cast<NSArray*>(CTFrameGetLines(frame)) firstObject] retain] autorelease]);
-            CFRelease(frame);
+            CTLineRef fitLine = (CTLineRef)CFArrayGetValueAtIndex(CTFrameGetLines(frame.get()), 0);
```
Comment (ms-jihua) [inline Frameworks/UIKit/NSLayoutManager.mm]: >(CTLineRef) [](start = 32, length = 11)

would keep this static_cast still

File: Frameworks/UIKit/NSTextContainer.mm [hunk 11]
```diff
@@ -62,38 +78,120 @@ - (NSArray*)exclusionPaths {
     return _exclusionPaths;
 }
 
+// Finds the first viable region for the proposed rect given the exclusion areas based upon x positions
+// Assumes writing direction is left to right, exclusionLines is sorted and preprocessed for y positions, and all inputs are valid
```
Comment (ms-jihua) [inline Frameworks/UIKit/NSTextContainer.mm]: >Assumes writing direction is left to right [](start = 3, length = 42)

What's the plan for eventually dealing with this? It's not clear to me atm whether this section will be removed/fixed once CGD2D comes in

Comment (aballway) [inline Frameworks/UIKit/NSTextContainer.mm]: This would not be resolved with CGD2D changes, it would need to be a separate task.

Comment (rajsesh-msft) [inline Frameworks/UIKit/NSTextContainer.mm]: Please create an issue for this.

File: Frameworks/UIKit/NSTextContainer.mm [hunk 12]
```diff
@@ -62,38 +78,121 @@ - (NSArray*)exclusionPaths {
...
+        if (path.origin.x + path.size.width > proposed.origin.x) {
+            proposed.origin.x = (path.origin.x + path.size.width) + padding;
+            proposed.size.width = maxWidth - proposed.origin.x;
+        }
+    }
+
+    return proposed;
+}
+
+// Finds the first point at which the given rect intersects the given exclusionContext, moving by delta each iteration
```
Comment (ms-jihua) [inline Frameworks/UIKit/NSTextContainer.mm]: >moving by delta each iteration [](start = 88, length = 30)

is there a more efficient way to do this? this current implementation seems incredibly expensive.

File: Frameworks/UIKit/NSTextContainer.mm [hunk 13]
```diff
@@ -17,12 +17,19 @@
...
 
+#include <vector>
+#include <algorithm>
+
+static constexpr CGFloat c_defaultPadding = 5.0f;
 @implementation NSTextContainer {
     CGSize _size;
     NSLayoutManager* _layoutManager;
     StrongId<NSArray> _exclusionPaths;
+    // TODO 1394: Remove for CGD2D
```
Comment (ms-jihua) [inline Frameworks/UIKit/NSTextContainer.mm]: nit: doesn't matter too much since these'll eventually be removed, but if the counts of these two vectors are expected to stay the same, it's good to put in an enforcement mechanism for that (ie: use one vector, or even an std::map)

I would just add a comment noting that assumption in this case, since we'll eventually remove this

File: Frameworks/CoreGraphics/CGPath.mm [hunk 14]
```diff
@@ -888,182 +888,4 @@ CFTypeID CGPathGetTypeID() {
 bool CGPathIsRect(CGPathRef path, CGRect* rect) {
     UNIMPLEMENTED();
     return StubReturn();
-}
-
-class ScanlineCalculator {
```
Comment (aballway) [inline Frameworks/CoreGraphics/CGPath.mm]: Yea this was from the old implementation

File: Frameworks/UIKit/NSTextContainer.mm (hunk 12 above)
Comment (aballway) [inline Frameworks/UIKit/NSTextContainer.mm]: Not that I'm aware, and this gives similar performance to previous implementation and reference platform

File: tests/unittests/UIKit/NSTextContainerTests.mm [hunk 15]
```diff
@@ -0,0 +1,65 @@
...
+
+TEST(NSTextContainer, LineFragmentRectForProposedRect) {
+    NSTextContainer* textContainer = [[[NSTextContainer alloc] initWithSize:CGSizeMake(1000, FLT_MAX)] autorelease];
+    textContainer.exclusionPaths = @[
+        [UIBezierPath bezierPathWithRect:CGRectMake(100, 0, 100, 100)],
+        [UIBezierPath bezierPathWithRect:CGRectMake(300, 0, 200, 150)],
+        [UIBezierPath bezierPathWithRect:CGRectMake(700, 0, 150, 300)]
+    ];
+
+    CGRect remaining = CGRectInfinite;
```
Comment (ms-jihua) [inline tests/unittests/UIKit/NSTextContainerTests.mm]: can you add some comments about your intentions with each of these test cases?

File: Frameworks/UIKit/NSTextContainer.mm [hunk 16]
```diff
@@ -62,38 +78,121 @@ - (NSArray*)exclusionPaths {
...
-        for (UIBezierPath* path in(NSArray*)_exclusionPaths) {
-            CGRect shapeRect = _CGPathFitRect(path.CGPath, ret, _size, self.lineFragmentPadding);
-            ret = CGRectIntersection(shapeRect, ret);
+    std::vector<CGRect> exclusionRectsForHorizontal{};
+    for (size_t i = 0; i < _exclusionPathBoundingRects.size(); ++i) {
+        CGRect boundingRect = _exclusionPathBoundingRects[i];
+        // If our proposed area doesn't intersect the bounding box of the exclusion zone at all, no need to compare against it
+        if ((proposed.origin.y < boundingRect.origin.y + boundingRect.size.height) &&
+            (proposed.origin.y + proposed.size.height > boundingRect.origin.y) &&
+            (proposed.origin.x < boundingRect.origin.x + boundingRect.size.width)) {
```
Comment (ms-jihua) [inline Frameworks/UIKit/NSTextContainer.mm]: >proposed.origin.x < boundingRect.origin.x + boundingRect.size.width [](start = 13, length = 67)

what if proposed.origin.x + proposed.size.width > boundingRect.origin.x? (just wondering why there are two lines for y and only one for x)

File: Frameworks/UIKit/NSTextContainer.mm (hunk 12 above)
Comment (ms-jihua) [inline Frameworks/UIKit/NSTextContainer.mm]: I mean like, even if you're not wanting to do line intersections or whatever (would probably be a lot faster though), you can, off the top of my head:
- not calculate rect.origin.x + delta three times
- do a binary search instead of a linear search

how long do you expect this function to stick around? is it worth investing into a faster implementation at this/a later time?

---
In reply to: [90086723](https://github.com/Microsoft/WinObjC/pull/1398#discussion_r90086723) [](ancestors = 90086723)

File: Frameworks/UIKit/NSTextContainer.mm (hunk 16 above)
Comment (ms-jihua) [inline Frameworks/UIKit/NSTextContainer.mm]: CGRectIntersectsRect?

---
In reply to: [90091646](https://github.com/Microsoft/WinObjC/pull/1398#discussion_r90091646) [](ancestors = 90091646)

**Comment by DHowett-MSFT** [comment]
:shipit:
