### PR TITLE
Fix #580, add support for concurrent NSOperation subclass

### LINKED ISSUE #580: Add support for custom concurrent NSOperation subclasses.
The current implementation of NSOperation/Queue only supports subclasses that override `-(void)main`
 and does not work with custom concurrent NSOperation subclasses that override `-(void)start`.

Take the following example NSOperation subclass which wraps a couple of async operations. The way this should work is when the operation is done,  it's complete block is executed, it's removed from it's queue, and any dependant operations are lined up for execution. This operation does not executed as expected with the current implementation.

```
@interface MyOperation : NSOperation

@property (assign, getter = isExecuting) BOOL executing;
@property (assign, getter = isFinished, readonly) BOOL finished;

@end

@implementation MyOperation

@synthesize executing = _executing;
@synthesize finished = _finished;

- (void)setExecuting:(BOOL)executing
{
	[self willChangeValueForKey:@"isExecuting"];
	[self willChangeValueForKey:@"isFinished"];
	
	_executing = executing;
	_finished = !executing;
	
	[self didChangeValueForKey:@"isExecuting"];
	[self didChangeValueForKey:@"isFinished"];
}

- (BOOL)isExecuting
{
	return _executing;
}

- (BOOL)isFinished
{
	return _finished;
}

- (void)start
{	
	if (self.isCancelled)
		return;
	
	self.executing = YES;
	[self doSomething];
}

- (void)doSomething
{
	// Do some async task.
	dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_LOW, 0), ^{
        
		// Do another async task
		dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_LOW, 0), ^{
			// Do some async task.
			self.executing = NO;
		});
    });
}

@end
```

This is an important feature of NSOperation/Queue as it allows you to group multiple async tasks into a single operation. It would be great if support for this could be added.

### PR DESCRIPTION
**Pull request by jofre-ms**
This change redesigns NSOperation for subclassability as documented for the reference platform, and adds a test to verify that the subclass no longer deadlocks in waitUntilFinished.

### CODE REVIEW

File: Frameworks/Foundation/NSOperation.mm [hunk 1]
```diff
@@ -1,115 +1,112 @@
...
         pthread_mutexattr_t attr;
-
         pthread_mutexattr_init(&attr);
         pthread_mutexattr_settype(&attr, PTHREAD_MUTEX_RECURSIVE);
-        pthread_mutex_init(&finishLock, &attr);
+        pthread_mutex_init(&_finishLock, &attr);
         pthread_mutexattr_destroy(&attr);
-    }
+        pthread_mutex_init(&_dependenciesLock, NULL);
+        pthread_mutex_init(&_completionBlockLock, NULL);
```
Comment (msft-Jeyaram) [inline Frameworks/Foundation/NSOperation.mm]: we talked earlier about using NSLock and yep it's not going to be efficient as just using raw pthreads since it objc_msgSend will add addition overhead.

Although pthreads are fine, we have allot going on here, it's easier to forget to set/destroy something. Since we support C++ on these files, we should go ahead and use std::mutex, recursive mutex, etc. 

This would make the code much cleaner to maintain and read, also avoid pitfalls that we might encounter in the future maintenance.  Going forward we should use them.

File: Frameworks/Foundation/NSOperation.mm [hunk 2]
```diff
@@ -1,115 +1,112 @@
...
-#include <pthread.h>
-#include <string.h>
-struct NSOperationPriv {
-    NSOperationQueuePriority priority;
-    id dependencies;
-    void (^completionBlock)(void);
+@implementation NSOperation {
+    StrongId<NSMutableArray> _dependencies;
+    void (^_completionBlock)(void);
+    pthread_cond_t _finishCondition;
```
Comment (mnithish) [inline Frameworks/Foundation/NSOperation.mm]: Can we use NSCondition please?

File: Frameworks/Foundation/NSOperation.mm [hunk 3]
```diff
@@ -1,115 +1,112 @@
...
-    if (priv->dependencies == nil) {
-        priv->dependencies = [[NSMutableArray alloc] init];
+    pthread_mutex_lock(&_dependenciesLock);
+    int count = [_dependencies count];
+
+    for (int i = 0; i < count; i++) {
+        id op = [_dependencies objectAtIndex:i];
+
+        if (![op isFinished]) {
+            pthread_mutex_unlock(&_dependenciesLock);
```
Comment (mnithish) [inline Frameworks/Foundation/NSOperation.mm]: let us use std:: functions here and make the code a bit simpler to maintain with RAII

File: Frameworks/Foundation/NSOperation.mm [hunk 4]
```diff
@@ -1,115 +1,112 @@
...
+// THE SOFTWARE.
+//
+//******************************************************************************
 
 #include "Starboard.h"
 #include "StubReturn.h"
 #include "Foundation/NSOperation.h"
-#include "Foundation/NSString.h"
-#include "Foundation/NSMutableArray.h"
-#include "LoggingNative.h"
```
Comment (msft-Jeyaram) [inline Frameworks/Foundation/NSOperation.mm]: use angular brackets <>

File: Frameworks/Foundation/NSOperation.mm [hunk 5]
```diff
@@ -1,115 +1,112 @@
...
 
 static const wchar_t* TAG = L"NSOperation";
```
Comment (mnithish) [inline Frameworks/Foundation/NSOperation.mm]: nit: not used

**Comment by msft-Jeyaram** [comment]
:clock1:

File: Frameworks/Foundation/NSOperation.mm [hunk 6]
```diff
@@ -131,139 +128,109 @@ - (void)setThreadPriority:(double)priority {
  @Status Interoperable
 */
 - (void)setCompletionBlock:(void (^)(void))block {
-    id oldBlock = priv->completionBlock;
-    priv->completionBlock = [block copy];
-    [oldBlock release];
+    pthread_mutex_lock(&_completionBlockLock);
+    [_completionBlock autorelease];
```
Comment (mnithish) [inline Frameworks/Foundation/NSOperation.mm]: Curious: why should this be not release?

File: Frameworks/Foundation/NSOperation.mm [hunk 7]
```diff
@@ -131,139 +128,109 @@ - (void)setThreadPriority:(double)priority {
...
+    }
 
-        [self _setFinished:YES
-            andPerformUnderLock:^{
-                if (execute) {
-                    priv->executing = 0;
-                    [self didChangeValueForKey:@"isExecuting"];
-                }
-            }];
+    THROW_NS_IF(E_INVALIDARG, (_executing || ![self isReady]));
```
Comment (mnithish) [inline Frameworks/Foundation/NSOperation.mm]: interesting this would be the behavior on the reference platform

File: Frameworks/Foundation/NSOperation.mm (hunk 6 above)
Comment (jofre-ms) [inline Frameworks/Foundation/NSOperation.mm]: I think it's unnecessary. I'll change back to release.

---
In reply to: [69351630](https://github.com/Microsoft/WinObjC/pull/602#discussion_r69351630) [](ancestors = 69351630)

File: Frameworks/Foundation/NSOperation.mm (hunk 7 above)
Comment (jofre-ms) [inline Frameworks/Foundation/NSOperation.mm]: From the documentation "If the operation is currently executing or is not ready to execute, this method [start] throws an NSInvalidArgumentException exception."

---
In reply to: [69351761](https://github.com/Microsoft/WinObjC/pull/602#discussion_r69351761) [](ancestors = 69351761)

File: Frameworks/Foundation/NSOperation.mm [hunk 8]
```diff
@@ -131,139 +128,109 @@ - (void)setThreadPriority:(double)priority {
...
-        priv->completionBlock();
-        [priv->completionBlock release];
-        priv->completionBlock = nil;
+    pthread_mutex_unlock(&_finishLock);
+    
+    if (completion) {
+        completion();
     }
+
+    [completion release];
```
Comment (mnithish) [inline Frameworks/Foundation/NSOperation.mm]: This is not thread safe... theoretically  _completionBlock could get a new value and retain the new value while you are executing these statements

File: tests/unittests/Foundation/NSOperationTests.mm [hunk 9]
```diff
@@ -59,3 +62,102 @@
...
+}
+
+- (BOOL)isFinished
+{
+    return _finished;
+}
+
+- (void)start
+{
+    if (self.isCancelled)
```
Comment (mnithish) [inline tests/unittests/Foundation/NSOperationTests.mm]: nit: braces to follow coding convention

File: tests/unittests/Foundation/NSOperationTests.mm [hunk 10]
```diff
@@ -59,3 +62,102 @@
...
+
+@implementation MyOperation
+
+@synthesize executing = _executing;
+@synthesize finished = _finished;
+
+- (void)setExecuting:(BOOL)executing
+{
+    [self willChangeValueForKey:@"isExecuting"];
+    [self willChangeValueForKey:@"isFinished"];
```
Comment (mnithish) [inline tests/unittests/Foundation/NSOperationTests.mm]: Add some KVO tests around these?

File: Frameworks/Foundation/NSOperation.mm (hunk 8 above)
Comment (mnithish) [inline Frameworks/Foundation/NSOperation.mm]: Sorry... missed the fact this is a local block. Thanks for explaining John

---
In reply to: [69352631](https://github.com/Microsoft/WinObjC/pull/602#discussion_r69352631) [](ancestors = 69352631)

File: Frameworks/Foundation/NSOperation.mm [hunk 11]
```diff
@@ -1,115 +1,112 @@
...
+    pthread_mutex_t _finishLock;
+    pthread_mutex_t _dependenciesLock;
+    pthread_mutex_t _completionBlockLock;
+}
 
-    pthread_cond_t finishCondition;
-    pthread_mutex_t finishLock;
+@synthesize cancelled = _cancelled;
+@synthesize executing = _executing;
+@synthesize finished = _finished;
```
Comment (mnithish) [inline Frameworks/Foundation/NSOperation.mm]: Can we STUB concurrent and asynchronous properties in the header file or implement them if we plan to complete the implementation for this class?

File: tests/unittests/Foundation/NSOperationTests.mm [hunk 12]
```diff
@@ -59,3 +62,102 @@
...
+{
+    // Do some async task.
+    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_LOW, 0), ^{
+
+        // Do another async task
+        dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_LOW, 0), ^{
+            // Do some async task.
+            self.executing = NO;
+        });
+    });
```
Comment (mnithish) [inline tests/unittests/Foundation/NSOperationTests.mm]: Shouldn't these be implemented in -main to test the real usage of this class?

File: tests/unittests/Foundation/NSOperationTests.mm [hunk 13]
```diff
@@ -59,3 +62,102 @@
...
+{
+    return _executing;
+}
+
+- (BOOL)isFinished
+{
+    return _finished;
+}
+
+- (void)start
```
Comment (mnithish) [inline tests/unittests/Foundation/NSOperationTests.mm]: Can we also have a test that does not override start but implements main?

File: Frameworks/Foundation/NSOperation.mm [hunk 14]
```diff
@@ -131,139 +128,109 @@ - (void)setThreadPriority:(double)priority {
...
+    if (shouldExecute) {
+        [self willChangeValueForKey:@"isExecuting"];
+        _executing = YES;
+        [self didChangeValueForKey:@"isExecuting"];
+    }
+    pthread_mutex_unlock(&_finishLock);
+    
+    if (shouldExecute) {
+        NSAutoreleasePool* pool = [NSAutoreleasePool new];
+        [self main];
```
Comment (mnithish) [inline Frameworks/Foundation/NSOperation.mm]: try-catch? From iOS documentation - "You should never allow exceptions to propagate out of your main method." Might be worth checking the reference platform as they jump around talking about OS X in the same line

File: tests/unittests/Foundation/NSOperationTests.mm (hunk 10 above)
Comment (jofre-ms) [inline tests/unittests/Foundation/NSOperationTests.mm]: I don't think it's necessary to test the test class MyOperation, but I'll add KVO tests for the base class.

---
In reply to: [69353346](https://github.com/Microsoft/WinObjC/pull/602#discussion_r69353346) [](ancestors = 69353346)

File: Frameworks/Foundation/NSOperation.mm [hunk 15]
```diff
@@ -1,115 +1,112 @@
...
+    pthread_mutex_unlock(&_dependenciesLock);
 }
 
 /**
  @Status Interoperable
 */
-- (NSOperationQueuePriority)queuePriority {
-    return priv->priority;
-}
+- (BOOL)isReady {
```
Comment (mnithish) [inline Frameworks/Foundation/NSOperation.mm]: From documentation -  "you must generate KVO notifications for the isReady key path whenever the ready state of your operation object changes."

File: Frameworks/Foundation/NSOperation.mm (hunk 7 above)
Comment (mnithish) [inline Frameworks/Foundation/NSOperation.mm]: Ah looks like NSOperation can be called directly without being added to a NSOperationQueue. Interesting...

---
In reply to: [69352263](https://github.com/Microsoft/WinObjC/pull/602#discussion_r69352263) [](ancestors = 69352263,69351761)

File: tests/unittests/Foundation/NSOperationTests.mm [hunk 16]
```diff
@@ -59,3 +62,102 @@
...
+    [queue addOperation:operation];
+
+    [operation waitUntilFinished];
+
+    ASSERT_TRUE([operation isFinished]);
+    ASSERT_FALSE([operation isExecuting]);
+    ASSERT_NO_THROW([operation release]);
+}
+
+TEST(NSOperation, NSOperationMultipleWaiters) {
```
Comment (mnithish) [inline tests/unittests/Foundation/NSOperationTests.mm]: Tests around dependencies?

File: Frameworks/Foundation/NSOperation.mm (hunk 14 above)
Comment (jofre-ms) [inline Frameworks/Foundation/NSOperation.mm]: According to the preceding sentence in the documentation, this is the correct behavior. " In OS X v10.6 and later, exceptions are allowed to propagate beyond this [start] method. You should never allow exceptions to propagate out of your main method."

---
In reply to: [69355325](https://github.com/Microsoft/WinObjC/pull/602#discussion_r69355325) [](ancestors = 69355325)

File: Frameworks/Foundation/NSOperation.mm [hunk 17]
```diff
@@ -131,139 +128,109 @@ - (void)setThreadPriority:(double)priority {
...
+    pthread_mutex_lock(&_completionBlockLock);
+    [_completionBlock autorelease];
+    _completionBlock = [block copy];
+    pthread_mutex_unlock(&_completionBlockLock);
 }
 
 /**
  @Status Interoperable
 */
 - (void (^)(void))completionBlock {
```
Comment (mnithish) [inline Frameworks/Foundation/NSOperation.mm]: What does it mean to add support to observe this property? According to the document this is an observable property

File: Frameworks/Foundation/NSOperation.mm [hunk 18]
```diff
@@ -277,35 +244,35 @@ - (void)main {
...
+
+    pthread_mutex_unlock(&_finishLock);
 }
 
 /**
  @Status Interoperable
 */
-- (id)dependencies {
-    return priv->dependencies;
+- (NSArray*)dependencies {
```
Comment (mnithish) [inline Frameworks/Foundation/NSOperation.mm]: What does it mean to add support to observe this property? According to the document this is an observable property

File: Frameworks/Foundation/NSOperation.mm [hunk 19]
```diff
@@ -131,139 +128,109 @@ - (void)setThreadPriority:(double)priority {
...
 
 /**
  @Status Interoperable
 */
 - (BOOL)isExecuting {
-    return priv->executing != 0;
+    return _executing;
 }
 
 /**
```
Comment (mnithish) [inline Frameworks/Foundation/NSOperation.mm]: Implement isAsynchronous and return NO and isConcurrent and return NO

File: Frameworks/Foundation/NSOperation.mm [hunk 20]
```diff
@@ -131,139 +128,109 @@ - (void)setThreadPriority:(double)priority {
...
+    if (didExecute) {
+        _executing = NO;
+        [self didChangeValueForKey:@"isExecuting"];
     }
 
-    if (newValue == 1) {
-        pthread_cond_broadcast(&priv->finishCondition);
-    }
+    pthread_mutex_lock(&_completionBlockLock);
+    void (^completion)(void) = [_completionBlock retain];
```
Comment (jofre-ms) [inline Frameworks/Foundation/NSOperation.mm]: "In iOS 8 and later and OS X v10.10 and later, this property is set to nil after the completion block begins executing."

File: Frameworks/Foundation/NSOperation.mm (hunk 18 above)
Comment (jofre-ms) [inline Frameworks/Foundation/NSOperation.mm]: [self willChangeValueForKey:@"dependencies"];
    [self didChangeValueForKey:@"dependencies"];
added to addDependency and removeDependency

---
In reply to: [69357321](https://github.com/Microsoft/WinObjC/pull/602#discussion_r69357321) [](ancestors = 69357321)

**Comment by mnithish** [comment]
:clock1:

File: Frameworks/Foundation/NSOperation.mm (hunk 17 above)
Comment (jofre-ms) [inline Frameworks/Foundation/NSOperation.mm]: needs
    [self willChangeValueForKey:@"completionBlock"];
    [self didChangeValueForKey:@"completionBlock"];


---
In reply to: [69357300](https://github.com/Microsoft/WinObjC/pull/602#discussion_r69357300) [](ancestors = 69357300)

File: Frameworks/Foundation/NSOperation.mm (hunk 15 above)
Comment (jofre-ms) [inline Frameworks/Foundation/NSOperation.mm]: This will need a test as well

---
In reply to: [69355570](https://github.com/Microsoft/WinObjC/pull/602#discussion_r69355570) [](ancestors = 69355570)

File: Frameworks/Foundation/NSOperation.mm (hunk 11 above)
Comment (jofre-ms) [inline Frameworks/Foundation/NSOperation.mm]: queuePriority is used in NSOperationQueue and cannot be stub. I'm adding a "caveat" implementation that always returns NSOperationQueuePriorityNormal for that property. qualityOfService will be STUB and concurrent/asynchronous return NO.

---
In reply to: [69354091](https://github.com/Microsoft/WinObjC/pull/602#discussion_r69354091) [](ancestors = 69354091)

File: Frameworks/Foundation/NSOperation.mm [hunk 21]
```diff
@@ -131,139 +128,109 @@ - (void)setThreadPriority:(double)priority {
...
 }
 
 /**
  @Status Interoperable
 */
 - (void)cancel {
-    if (priv->cancelled == 0) {
-        pthread_mutex_lock(&priv->finishLock);
+    if (_cancelled == NO) {
+        pthread_mutex_lock(&_finishLock);
```
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSOperation.mm]: Is it safe to do this outside of lock?

File: Frameworks/Foundation/NSOperation.mm (hunk 18 above)
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSOperation.mm]: Depending on how this works, you might have to use `{did|will}ChangeValuesAtIndexes: forKey:`

---
In reply to: [69358159](https://github.com/Microsoft/WinObjC/pull/602#discussion_r69358159) [](ancestors = 69358159,69357321)

File: Frameworks/Foundation/NSOperation.mm [hunk 22]
```diff
@@ -277,35 +244,35 @@ - (void)main {
...
+    return copy;
 }
 
 /**
  @Status Interoperable
 */
 - (void)dealloc {
-    assert(!priv->completionBlock);
-    delete priv;
+    [self removeObserver:self forKeyPath:@"isFinished" context:NULL];
```
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSOperation.mm]: nit: prefer nullptr over NULL.

File: Frameworks/Foundation/NSOperation.mm (hunk 11 above)
Comment (jofre-ms) [inline Frameworks/Foundation/NSOperation.mm]: Actually queuePriority can just be auto-synthesized

---
In reply to: [69614305](https://github.com/Microsoft/WinObjC/pull/602#discussion_r69614305) [](ancestors = 69614305,69354091)

File: Frameworks/Foundation/NSOperation.mm [hunk 23]
```diff
@@ -277,35 +244,35 @@ - (void)main {
...
+    pthread_cond_destroy(&_finishCondition);
+    pthread_mutex_destroy(&_finishLock);
+    pthread_mutex_destroy(&_dependenciesLock);
+    pthread_mutex_destroy(&_completionBlockLock);
+    [_completionBlock release];
```
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSOperation.mm]: `_completionBlock` can be a `StrongId<void(^)()>` if you want to dispense with the formalities.

File: Frameworks/Foundation/NSOperation.mm (hunk 18 above)
Comment (jofre-ms) [inline Frameworks/Foundation/NSOperation.mm]: Discussed offline. This matches the ref platform

---
In reply to: [69615177](https://github.com/Microsoft/WinObjC/pull/602#discussion_r69615177) [](ancestors = 69615177,69358159,69357321)

Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSOperation.mm]: It looks like the reference platform dispatches full change notifications and not indexed ones.

---
In reply to: [69615177](https://github.com/Microsoft/WinObjC/pull/602#discussion_r69615177) [](ancestors = 69615177,69358159,69357321)

File: Frameworks/Foundation/NSOperation.mm [hunk 24]
```diff
@@ -77,41 +61,88 @@ + (BOOL)automaticallyNotifiesObserversForKey:(NSString*)key {
...
-+ (id)allocWithZone:(NSZone*)zone {
-    NSOperation* ret = [super allocWithZone:zone];
+- (void)_checkReady {
+    bool newReady = YES;
 
-    ret->priv = new NSOperationPriv();
+    // If cancelled, skip this logic and set _ready to YES. Otherwise check dependencies.
+    if (![self isCancelled]) {
+        _dependenciesLock.lock();
+        int count = [_dependencies count];
```
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSOperation.mm]: nit: prefer std::lock_guard for scope-guarded mutex use

File: Frameworks/Foundation/NSOperation.mm [hunk 25]
```diff
@@ -77,41 +61,88 @@ + (BOOL)automaticallyNotifiesObserversForKey:(NSString*)key {
     return NO;
 }
 
-/**
- @Status Interoperable
-*/
-+ (id)allocWithZone:(NSZone*)zone {
-    NSOperation* ret = [super allocWithZone:zone];
+- (void)_checkReady {
```
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSOperation.mm]: Is this safe for possibly concurrent access?

File: Frameworks/Foundation/NSOperation.mm [hunk 26]
```diff
@@ -77,41 +61,88 @@ + (BOOL)automaticallyNotifiesObserversForKey:(NSString*)key {
...
+    if (_ready != newReady) {
+        [self willChangeValueForKey:@"isReady"];
+        _ready = newReady;
+        [self didChangeValueForKey:@"isReady"];
+    }
+}
+
+- (void)observeValueForKeyPath:(NSString*)keyPath ofObject:(id)object change:(NSDictionary*)change context:(void*)context {
+    if ([keyPath isEqualToString:@"isFinished"]) {
+        if (object == self) {
```
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSOperation.mm]: If you use context on registration for isFinished, you can avoid a string compare.

File: Frameworks/Foundation/NSOperation.mm [hunk 27]
```diff
@@ -77,41 +61,88 @@ + (BOOL)automaticallyNotifiesObserversForKey:(NSString*)key {
...
 /**
  @Status Interoperable
 */
-- (void)setQueuePriority:(NSOperationQueuePriority)priority {
-    priv->priority = priority;
+- (void)removeDependency:(NSOperation*)operation {
+    [self willChangeValueForKey:@"dependencies"];
+    _dependenciesLock.lock();
+    [operation removeObserver:self forKeyPath:@"isFinished" context:NULL];
+    [_dependencies removeObject:operation];
```
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSOperation.mm]: What happens here if you remove a dependency that this operation doesn't have?

File: Frameworks/Foundation/NSOperation.mm (hunk 6 above)
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSOperation.mm]: If you set op.completionBlock = op.completionBlock, you will likely destroy the block here./

---
In reply to: [69352043](https://github.com/Microsoft/WinObjC/pull/602#discussion_r69352043) [](ancestors = 69352043,69351630)

File: tests/unittests/Foundation/NSOperationTests.mm [hunk 28]
```diff
@@ -59,3 +62,256 @@
...
+@end
+
+TEST(NSOperation, NSOperationConcurrentSubclass) {
+    NSOperationQueue* queue = [[NSOperationQueue new] autorelease];
+
+    NSOperation* operation = [MyConcurrentOperation new];
+
+    [operation setCompletionBlock:^{
+        [operation waitUntilFinished]; // Should not deadlock, but we cannot test this
+        ASSERT_TRUE([operation isFinished]);
```
Comment (DHowett-MSFT) [inline tests/unittests/Foundation/NSOperationTests.mm]: We can somewhat test deadlocks -- by having a watchdog thread. In the worst case, the test runs until the watchdog fails it, but then we need to abort the test run completely since we can't recover.

File: Frameworks/Foundation/NSOperation.mm (hunk 24 above)
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSOperation.mm]: I'm upgrading this from a nit -- we should definitely use `lock_guard` and `unique_lock` everywhere. `std::condition_variable_any` actually can take a `unique_lock`, as well.

---
In reply to: [69623694](https://github.com/Microsoft/WinObjC/pull/602#discussion_r69623694) [](ancestors = 69623694)

**Comment by DHowett-MSFT** [comment]
:clock1:

File: Frameworks/Foundation/NSOperation.mm (hunk 21 above)
Comment (jofre-ms) [inline Frameworks/Foundation/NSOperation.mm]: moved the scope of the lock outside of the if statement

---
In reply to: [69615071](https://github.com/Microsoft/WinObjC/pull/602#discussion_r69615071) [](ancestors = 69615071)

File: Frameworks/Foundation/NSOperation.mm (hunk 6 above)
Comment (jofre-ms) [inline Frameworks/Foundation/NSOperation.mm]: switched to strongId

---
In reply to: [69624034](https://github.com/Microsoft/WinObjC/pull/602#discussion_r69624034) [](ancestors = 69624034,69352043,69351630)

File: Frameworks/Foundation/NSOperation.mm (hunk 24 above)
Comment (jofre-ms) [inline Frameworks/Foundation/NSOperation.mm]: why?

---
In reply to: [69624996](https://github.com/Microsoft/WinObjC/pull/602#discussion_r69624996) [](ancestors = 69624996,69623694)

File: Frameworks/Foundation/NSOperation.mm (hunk 25 above)
Comment (jofre-ms) [inline Frameworks/Foundation/NSOperation.mm]: Needs another lock

---
In reply to: [69623776](https://github.com/Microsoft/WinObjC/pull/602#discussion_r69623776) [](ancestors = 69623776)

File: Frameworks/Foundation/NSOperation.mm (hunk 27 above)
Comment (jofre-ms) [inline Frameworks/Foundation/NSOperation.mm]: On the reference platform, nothing happens. I'll add a test.

---
In reply to: [69623943](https://github.com/Microsoft/WinObjC/pull/602#discussion_r69623943) [](ancestors = 69623943)

File: Frameworks/Foundation/NSOperation.mm (hunk 11 above)
Comment (mnithish) [inline Frameworks/Foundation/NSOperation.mm]: setQueuePriority should spew a warning saying only NSOperationQueuePriorityNormal is supported and have a CAVEAT keyword

---
In reply to: [69615276](https://github.com/Microsoft/WinObjC/pull/602#discussion_r69615276) [](ancestors = 69615276,69614305,69354091)

File: Frameworks/Foundation/NSOperation.mm [hunk 29]
```diff
@@ -131,139 +166,123 @@ - (void)setThreadPriority:(double)priority {
...
-        pthread_cond_broadcast(&priv->finishCondition);
+    if (didExecute) {
+        _executing = NO;
+        [self didChangeValueForKey:@"isExecuting"];
     }
 
-    pthread_mutex_unlock(&priv->finishLock);
+    _completionBlockLock.lock();
+    void (^completion)(void) = [_completionBlock retain];
+    [self setCompletionBlock:nil];
```
Comment (mnithish) [inline Frameworks/Foundation/NSOperation.mm]: Question: Does this need to trigger KVO events or should it silently set it to nil?

File: tests/unittests/Foundation/NSOperationTests.mm [hunk 30]
```diff
@@ -59,3 +62,264 @@
...
+    }];
+
+    [queue addOperation:operation];
+    [operation waitUntilFinished];
+
+    ASSERT_TRUE([operation isFinished]);
+    ASSERT_FALSE([operation isExecuting]);
+    ASSERT_TRUE([operation didWork]);
```
Comment (mnithish) [inline tests/unittests/Foundation/NSOperationTests.mm]: didWork needs to be reset after every successful test else the following test check is not really valid

File: Frameworks/Foundation/NSOperation.mm (hunk 29 above)
Comment (jofre-ms) [inline Frameworks/Foundation/NSOperation.mm]: I checked the reference platform and it sets silently. I'll make the change here.

---
In reply to: [69660196](https://github.com/Microsoft/WinObjC/pull/602#discussion_r69660196) [](ancestors = 69660196)

File: Frameworks/Foundation/NSOperation.mm (hunk 11 above)
Comment (jofre-ms) [inline Frameworks/Foundation/NSOperation.mm]: The current implementation for queue priority, which is just auto-synthesized, is sufficiently interoperable

---
In reply to: [69659816](https://github.com/Microsoft/WinObjC/pull/602#discussion_r69659816) [](ancestors = 69659816,69615276,69614305,69354091)

File: Frameworks/Foundation/NSOperation.mm [hunk 31]
```diff
@@ -131,139 +166,123 @@ - (void)setThreadPriority:(double)priority {
...
-        id op = [priv->dependencies objectAtIndex:i];
-
-        if (![op isFinished]) {
-            return NO;
-        }
-    }
-    return YES;
+- (BOOL)isCancelled {
+    std::lock_guard<std::recursive_mutex> lock(_finishLock);
+    return _cancelled;
```
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSOperation.mm]: Cancelled is guarded by the finish lock, but finished and executing aren't guarded by anything?

File: Frameworks/Foundation/NSOperation.mm [hunk 32]
```diff
@@ -131,139 +166,123 @@ - (void)setThreadPriority:(double)priority {
...
+    if (shouldExecute) {
+        [self willChangeValueForKey:@"isExecuting"];
+        _executing = YES;
+        [self didChangeValueForKey:@"isExecuting"];
+    }
+    _finishLock.unlock();
+    
+    if (shouldExecute) {
+        NSAutoreleasePool* pool = [NSAutoreleasePool new];
+        [self main];
```
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSOperation.mm]: NSOperatinQueue nigh-unto guarantees that operations run with their own pools -- do we have to make another one?

File: Frameworks/Foundation/NSOperation.mm [hunk 33]
```diff
@@ -131,139 +166,123 @@ - (void)setThreadPriority:(double)priority {
...
-    // is cancelled.
-    if (newValue == 1 && priv->completionBlock) {
-        priv->completionBlock();
-        [priv->completionBlock release];
-        priv->completionBlock = nil;
+    _finishLock.unlock();
+    
+    if (completion) {
+        completion();
     }
```
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSOperation.mm]: Does completion fire even if it did not execute (and was cancelled)?

File: Frameworks/Foundation/NSOperation.mm [hunk 34]
```diff
@@ -277,35 +296,37 @@ - (void)main {
...
 */
 - (void)dealloc {
-    assert(!priv->completionBlock);
-    delete priv;
-    [super dealloc];
-}
+    _dependenciesLock.lock();
+    int count = [_dependencies count];
+    for (int i = 0; i < count; i++) {
+        id op = [_dependencies objectAtIndex:i];
```
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSOperation.mm]: This is likely better written as `for(NSOperation* op in _dependencies)`, as it can be optimized.

File: tests/unittests/Foundation/NSOperationTests.mm (hunk 28 above)
Comment (jofre-ms) [inline tests/unittests/Foundation/NSOperationTests.mm]: I don't think it's worth changing to this design, although it would be better to have a watchdog thread. We can still detect the regression.

---
In reply to: [69624529](https://github.com/Microsoft/WinObjC/pull/602#discussion_r69624529) [](ancestors = 69624529)

File: Frameworks/Foundation/NSOperation.mm (hunk 33 above)
Comment (jofre-ms) [inline Frameworks/Foundation/NSOperation.mm]: Yes

---
In reply to: [69819051](https://github.com/Microsoft/WinObjC/pull/602#discussion_r69819051) [](ancestors = 69819051)

Comment (jofre-ms) [inline Frameworks/Foundation/NSOperation.mm]: "A finished operation may finish either because it was cancelled or because it successfully completed its task. You should take that fact into account when writing your block code."

---
In reply to: [69831586](https://github.com/Microsoft/WinObjC/pull/602#discussion_r69831586) [](ancestors = 69831586,69819051)

File: Frameworks/Foundation/NSOperation.mm (hunk 32 above)
Comment (jofre-ms) [inline Frameworks/Foundation/NSOperation.mm]: NSOperation support being invoked "manually" - that is, outside of the Queue by user code. We still need an autorelease pool in that case.

---
In reply to: [69818876](https://github.com/Microsoft/WinObjC/pull/602#discussion_r69818876) [](ancestors = 69818876)

File: Frameworks/Foundation/NSOperation.mm (hunk 31 above)
Comment (jofre-ms) [inline Frameworks/Foundation/NSOperation.mm]: I don't think the lock is needed for the accessor. Removing.

---
In reply to: [69818734](https://github.com/Microsoft/WinObjC/pull/602#discussion_r69818734) [](ancestors = 69818734)

File: Frameworks/Foundation/NSOperation.mm [hunk 35]
```diff
@@ -131,139 +162,122 @@ - (void)setThreadPriority:(double)priority {
...
+    return _executing;
 }
 
 /**
  @Status Interoperable
 */
-- (BOOL)isExecuting {
-    return priv->executing != 0;
+- (BOOL)isConcurrent {
+    return NO;
```
Comment (mnithish) [inline Frameworks/Foundation/NSOperation.mm]: Just noticed the changelist subject reads "add support for _concurrent_ NSOperation subclass"

Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSOperation.mm]: It's the _subclass_ that's concurrent; NSOperation has to have the machinery to support both even though it is itself nonconcurrent.

File: Frameworks/Foundation/NSOperation.mm [hunk 36]
```diff
@@ -131,139 +162,122 @@ - (void)setThreadPriority:(double)priority {
...
-        pthread_cond_broadcast(&priv->finishCondition);
+    if (didExecute) {
+        _executing = NO;
+        [self didChangeValueForKey:@"isExecuting"];
     }
 
-    pthread_mutex_unlock(&priv->finishLock);
+    _completionBlockLock.lock();
+    void (^completion)(void) = [_completionBlock retain];
+    _completionBlock = nil;
```
Comment (rajsesh-msft) [inline Frameworks/Foundation/NSOperation.mm]: >_completionBlock [](start = 4, length = 16)

dont need to notify change here?

Comment (rajsesh-msft) [inline Frameworks/Foundation/NSOperation.mm]: will be lot simpler to use completion = self.completionBlock
self.completionBlock = nil;
completion();


---
In reply to: [69981681](https://github.com/Microsoft/WinObjC/pull/602#discussion_r69981681) [](ancestors = 69981681)

File: Frameworks/Foundation/NSOperation.mm [hunk 37]
```diff
@@ -131,139 +162,122 @@ - (void)setThreadPriority:(double)priority {
...
-    int newValue = finished ? 1 : 0;
-    pthread_mutex_lock(&priv->finishLock);
+    THROW_NS_IF(E_INVALIDARG, (_executing || ![self isReady]));
+    
+    _finishLock.lock();
+    BOOL shouldExecute = !_cancelled; // Note: in the cancelled case, [self main] is not called but isFinished will still be observable
+    if (shouldExecute) {
+        [self willChangeValueForKey:@"isExecuting"];
+        _executing = YES;
+        [self didChangeValueForKey:@"isExecuting"];
```
Comment (rajsesh-msft) [inline Frameworks/Foundation/NSOperation.mm]: can you move this to setExecution() and reuse it?

File: Frameworks/Foundation/NSOperation.mm [hunk 38]
```diff
@@ -77,41 +64,85 @@ + (BOOL)automaticallyNotifiesObserversForKey:(NSString*)key {
     return NO;
 }
 
-/**
- @Status Interoperable
-*/
-+ (id)allocWithZone:(NSZone*)zone {
-    NSOperation* ret = [super allocWithZone:zone];
+- (void)_checkReady {
```
Comment (rajsesh-msft) [inline Frameworks/Foundation/NSOperation.mm]: >_checkReady [](start = 8, length = 11)

_checkReady can be changed to O(1) instead of O(N) by keeping the ready count.  since you are observing dependencies and their 'finished' state, incrementing/decrementing the counter should do the trick.

Comment (rajsesh-msft) [inline Frameworks/Foundation/NSOperation.mm]: Sycned up offline with John. Since this is an urgent fix, will follow-up on this separately.  #624

---
In reply to: [69982783](https://github.com/Microsoft/WinObjC/pull/602#discussion_r69982783) [](ancestors = 69982783)

**Comment by rajsesh-msft** [comment]
:shipit:
