### PR TITLE
Fixing more UIKit memory leaks

### LINKED ISSUE #1858: UIKit.Xaml controls (UIKit.Button, UIKit.Label, etc.) are leaked
We have a leak in the Create* path for our UIKit.Xaml controls.  Fix+tests coming soon.

### LINKED ISSUE #1859: UIButton leaks after recent switch to ARC
Pre-ARC we were using __block for our 'weakSelf' variable.  Post-ARC we need to use __weak.  Fix + test coming soon.

### PR DESCRIPTION
**Pull request by jaredhms**
Oops; accidentally deleted the branch; re-submitting PR.  

Fixing a leak in the Create* path for our UIKit.Xaml controls, and a leak in UIButton's use of 'weakSelf'.

Fixes #1858.
Fixes #1859 .

### CODE REVIEW

**Comment by oliversa-msft** [comment]
:shipit:

File: tests/functionaltests/Tests/UIKitTests/UIButtonTests.mm [hunk 1]
```diff
@@ -38,6 +38,63 @@
...
+-(void)dealloc {
+    _event->Set();
+    [super dealloc];
+}
+@end
+
+TEST(UIButton, CheckForLeaks) {
+    Microsoft::WRL::WeakRef weakXamlElement;
+    {
+        __block UIButtonWithControlsViewController* buttonVC = [[UIButtonWithControlsViewController alloc] init];
```
Comment (oliversa-msft) [inline tests/functionaltests/Tests/UIKitTests/UIButtonTests.mm]: >__block [](start = 8, length = 7)

I might have missed this before but do you really need __block here. I am under the impression, it should be retained correctly.

**Comment by yiyang-msft** [comment]
:shipit:

File: Frameworks/UIKit/XamlControls.mm [hunk 2]
```diff
@@ -27,7 +27,9 @@
 // Button
 ////////////////////////////////////////////////////////////////////////////////////
 WXCButton* CreateButton() {
-    ComPtr<IInspectable> inspectable(XamlCreateButton());
+    ComPtr<IInspectable> inspectable;
+    // Use Attach for transfer-ownership semantics, else we +1 and leak
+    inspectable.Attach(XamlCreateButton());
```
Comment (rajsesh-msft) [inline Frameworks/UIKit/XamlControls.mm]: Your real problem is the XamlCreateButton api design.  If it returned HRESULT and an out pointer, you have to try hard to leak it.  With the current model, it is easy to mess it up.

Comment (jaredhms) [inline Frameworks/UIKit/XamlControls.mm]: I suppose an out param would make it a bit more difficult to leak.

---
In reply to: [98310272](https://github.com/Microsoft/WinObjC/pull/1863#discussion_r98310272) [](ancestors = 98310272)
