### PR TITLE
Fix 2618 by forcing RTObjCInterop library to be included

### LINKED ISSUE #2618: Sample Apps Fail to launch after C++/winrt switchover
KERNELBASE!RaiseException+0x62
VCRUNTIME140_APP!_CxxThrowException+0x65
UIKit!winrt::impl::throw_hresult+0x2de
UIKit!winrt::Windows::Foundation::IUnknown::as<winrt::Windows::UI::Xaml::Controls::Button>+0x56
UIKit!-[UIButton _initUIButton]+0x92
UIKit!-[UIButton initWithFrame:]+0x93
UIKit!initControls+0x67
UIKit!-[UIBarButtonItem initWithTitle:style:target:action:]+0xa2
UIKit!-[UINavigationBar initWithCoder:]+0x181
UIKit!constructObject+0x1aa
UIKit!idForItem+0x49
UIKit!-[UINibUnarchiver decodeObjectForKey:]+0x2d
UIKit!-[UINavigationController initWithCoder:]+0x28
UIKit!constructObject+0x1aa
UIKit!idForItem+0x49
UIKit!-[UINibUnarchiver decodeObjectForKey:]+0x2d
UIKit!-[UIRuntimeOutletConnection initWithCoder:]+0x36

Seen in AddressBookSample

### PR DESCRIPTION
**Pull request by bviglietta**
Fixes #2618, #2619
The RTObjCInterop library is needed even if projections aren't being used, because UI elements sometimes get manipulated as RTObjects. This change ensures that RTObjCInterop.dll is included in the app package.

### CODE REVIEW

File: Frameworks/UIKit/ForceInclusion.mm [hunk 1]
```diff
@@ -47,6 +48,7 @@ void ForceInclusion() {
     [UISwitch class];
     [UISlider class];
     [UIProxyObject class];
+    [RTObject class];
```
Comment (bbowman) [inline Frameworks/UIKit/ForceInclusion.mm]: @bviglietta  Should they be treated as something else? It doesn't make sense for them to be used as RTObject if they aren't actually one right?

Comment (bviglietta) [inline Frameworks/UIKit/ForceInclusion.mm]: Well, they really are RTObjects, after we convert them to RTObjects. But you're right that there isn't a lot of reason to do this. One thing that I'd like to do in the near future is eliminate any continued use of RTObject (primarily in the xamlElement property on UIViews) and instead dynamically load the appropriately-typed projection classes as they're needed.
