### PR TITLE
Fixing internal naming conventions in CoreGraphics

### LINKED ISSUE #1301: Convert CG private APIs to use proper naming convention

### PR DESCRIPTION
**Pull request by MSFTFox**
Remove any unused Core Graphics internal APIs as well as normalize naming conventions across files.

Fix #1301

### CODE REVIEW

File: Frameworks/CoreGraphics/CGColor.mm [hunk 1]
```diff
@@ -24,22 +24,22 @@
...
 
-static IWLazyClassLookup _LazyUIColor("UIColor");
+static IWLazyClassLookup __LazyUIColor("UIColor");
 
 /**
  @Status Caveat
  @Notes Limited constants supported
 */
-CGColorRef CGColorGetConstantColor(CFStringRef name) {
+CGColorRef _CGColorGetConstantColor(CFStringRef name) {
```
Comment (DHowett-MSFT) [inline Frameworks/CoreGraphics/CGColor.mm]: This is a public API! It's even annotated with a Status!

Comment (DHowett-MSFT) [inline Frameworks/CoreGraphics/CGColor.mm]: (It's also in a public header. 😛)

File: Frameworks/CoreGraphics/CGPattern.mm [hunk 2]
```diff
@@ -192,7 +192,7 @@ void CGPatternRelease(CGPatternRef pattern) {
 /**
  @Status Interoperable
 */
-CGPatternRef CGPatternCreateFromImage(CGImageRef img) {
+CGPatternRef _CGPatternCreateFromImage(CGImageRef img) {
```
Comment (DHowett-MSFT) [inline Frameworks/CoreGraphics/CGPattern.mm]: If this is private, please unannotate it or mark it `@Public No`

File: Frameworks/QuartzCore/CALayer.mm [hunk 3]
```diff
@@ -1688,7 +1669,7 @@ - (void)setShadowColor:(CGColorRef)color {
 */
 - (CGColorRef)shadowColor {
     UNIMPLEMENTED();
-    return CGColorGetConstantColor((CFStringRef) @"BLACK");
+    return _CGColorGetConstantColor((CFStringRef) @"BLACK");
```
Comment (DHowett-MSFT) [inline Frameworks/QuartzCore/CALayer.mm]: While you're here, please change this to `kCGColorBlack`

File: Frameworks/QuartzCore/CAShapeLayer.mm [hunk 4]
```diff
@@ -229,7 +229,7 @@ - (instancetype)init {
         _shapeImage.delegate = self;
 
         [self addSublayer:_shapeImage];
-        _fillColor = (CGColorRef)CGColorGetConstantColor((CFStringRef) @"BLACK");
+        _fillColor = (CGColorRef)_CGColorGetConstantColor((CFStringRef) @"BLACK");
```
Comment (DHowett-MSFT) [inline Frameworks/QuartzCore/CAShapeLayer.mm]: While you're here, please change this to `kCGColorBlack`

File: Frameworks/include/CGContextInternal.h [hunk 5]
```diff
@@ -31,19 +31,17 @@
 COREGRAPHICS_EXPORT CGContextRef _CGContextCreateWithD2DRenderTarget(ID2D1RenderTarget* renderTarget);
 COREGRAPHICS_EXPORT void _CGContextSetShadowProjectionTransform(CGContextRef context, CGAffineTransform transform);
 COREGRAPHICS_EXPORT void _CGContextDrawImageRect(CGContextRef ctx, CGImageRef img, CGRect src, CGRect dst);
-COREGRAPHICS_EXPORT void CGContextClearToColor(CGContextRef ctx, float r, float g, float b, float a);
+COREGRAPHICS_EXPORT void _CGContextClearToColor(CGContextRef ctx, float r, float g, float b, float a);
```
Comment (DHowett-MSFT) [inline Frameworks/include/CGContextInternal.h]: You removed this function; no need to keep it in the header!

File: include/CoreGraphics/CGColor.h [hunk 6]
```diff
@@ -32,7 +32,7 @@ COREGRAPHICS_EXPORT CGColorRef CGColorCreate(CGColorSpaceRef space, const CGFloa
 COREGRAPHICS_EXPORT CGColorRef CGColorCreateWithPattern(CGColorSpaceRef colorSpace, CGPatternRef pattern, const CGFloat* components);
 COREGRAPHICS_EXPORT CGColorRef CGColorCreateCopy(CGColorRef color);
 COREGRAPHICS_EXPORT CGColorRef CGColorCreateCopyWithAlpha(CGColorRef color, CGFloat alpha);
-COREGRAPHICS_EXPORT CGColorRef CGColorGetConstantColor(CFStringRef name);
+COREGRAPHICS_EXPORT CGColorRef _CGColorGetConstantColor(CFStringRef name);
```
Comment (DHowett-MSFT) [inline include/CoreGraphics/CGColor.h]: Public header!

**Comment by msft-Jeyaram** [comment]
> #if 0

@duhowett@microsoft.com  
I recall you disabled them, looks like these aren't enabled?

---
Refers to: Frameworks/UIKit/UIColor.mm:510 in 3459877. [](commit_id = 3459877d843832935a3d898b6942398def507a78, deletion_comment = False)

**Comment by DHowett-MSFT** [comment]
@msft-Jeyaram nah that wasn't me: look at how the code is formatted! clang-format skips `#if 0` blocks; evidence says this is from before we all joined :smile:

File: Frameworks/CoreGraphics/CGColor.mm (hunk 1 above)
Comment (rajsesh-msft) [inline Frameworks/CoreGraphics/CGColor.mm]: 😮

File: include/CoreGraphics/CGPattern.h [hunk 7]
```diff
@@ -41,7 +41,7 @@ typedef CF_ENUM(CFIndex, CGPatternTiling) {
 };
 
 // Starboard-only:
-COREGRAPHICS_EXPORT CGPatternRef CGPatternCreateFromImage(CGImageRef img); // TODO: need to move out this maybe to UIKit ???
+COREGRAPHICS_EXPORT CGPatternRef _CGPatternCreateFromImage(CGImageRef img); // TODO: need to move out this maybe to UIKit ???
```
Comment (aballway) [inline include/CoreGraphics/CGPattern.h]: If this is supposed to be private put this in a private header

File: Frameworks/CoreGraphics/CGColor.mm (hunk 1 above)
Comment (MSFTFox) [inline Frameworks/CoreGraphics/CGColor.mm]: Well I guess I should move it from the "; private exports below" section of the def then. :P

File: Frameworks/QuartzCore/CALayer.mm [hunk 8]
```diff
@@ -535,15 +535,7 @@ - (void)display {
...
-        if (priv->_backgroundColor == nil || (int)[static_cast<UIColor*>(priv->_backgroundColor) _type] == solidBrush) {
-            CGContextClearToColor(drawContext,
-                                  priv->backgroundColor.r,
-                                  priv->backgroundColor.g,
-                                  priv->backgroundColor.b,
-                                  priv->backgroundColor.a);
-        } else {
-            CGContextClearToColor(drawContext, 0, 0, 0, 0);
-
+        if (priv->_backgroundColor != nil && (int)[static_cast<UIColor*>(priv->_backgroundColor) _type] != solidBrush) {
```
Comment (ms-jihua) [inline Frameworks/QuartzCore/CALayer.mm]: nit: add some parens?
