### PR TITLE
Fix cases where NSDictionary setObject:forKey: was given nil objects

### LINKED ISSUE #1713: Several regressions caused by hardening [NSCFDictionary setObject:forKey:]
IWHouse crashes on launch, and one of the CoreAnimation functional tests are failing (although it looks like the latter crash would crash any app that uses CALayer animations).  

It looks like CALayer _removeAnimation: _intentionally_ passes nil as 'object'; is this expected to throw on the reference platform?

`
vcruntime140_app.dll!_CxxThrowException(void * pExceptionObject, const _s__ThrowInfo * pThrowInfo) Line 131	C++
 	LIBOBJC2.DLL!objc_exception_throw(void * object) Line 134	C++
>	FOUNDATION.DLL!-[NSCFDictionary setObject:forKey:](NSCFDictionary * self, objc_selector * _cmd, id * object, id * key) Line 115	Objective-C++
 	QUARTZCORE.DLL!-[CALayer _removeAnimation:](CALayer * self, objc_selector * _cmd, CAAnimation * animation) Line 1392	Objective-C++
 	QUARTZCORE.DLL!-[CAAnimation _removeAnimationsFromLayer](CAAnimation * self, objc_selector * _cmd) Line 302	Objective-C++
 	QUARTZCORE.DLL!-[CALayer removeAllAnimations](CALayer * self, objc_selector * _cmd) Line 1430	Objective-C++
 	QUARTZCORE.DLL!-[CALayer dealloc](CALayer * self, objc_selector * _cmd) Line 1933	Objective-C++
`

Likewise, IWHouse crashes on launch; call stack coming shortly.

### PR DESCRIPTION
**Pull request by aballway**
CALayer was using setObject:nil to remove an object, but as of dad3c32 ( #1698 ) this will throw an NSException.  This was causing CTCatalog to crash when navigating past the first page.

Fixes #1713

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/winobjc/1711)

### CODE REVIEW

File: Frameworks/QuartzCore/CALayer.mm [hunk 1]
```diff
@@ -1389,7 +1389,7 @@ - (void)addAnimation:(CAAnimation*)anim forKey:(NSString*)key {
 
 - (void)_removeAnimation:(CAAnimation*)animation {
     CAAnimation* objForKey = [priv->_animations objectForKey:animation->_keyName];
```
Comment (yiyang-msft) [inline Frameworks/QuartzCore/CALayer.mm]: >objForKey [](start = 17, length = 9)

existing, never used?

**Comment by yiyang-msft** [comment]
:shipit:

**Comment by jaredhms** [comment]
:shipit:

File: Frameworks/UIKit/UIViewController.mm [hunk 2]
```diff
@@ -893,13 +893,14 @@ - (void)loadView {
         TraceVerbose(TAG, L"Loading view %hs with owner=%hs", name ? name : "nil", object_getClassName(self));
 
         if (EbrAccess(openname, 0) != -1) {
-            UIStoryboard* proxyObjects[1];
-            NSString* proxyNames[1];
```
Comment (DHowett-MSFT) [inline Frameworks/UIKit/UIViewController.mm]: What on earth would compel somebody to do this
