### PR TITLE
UIViewController modal appearance event fixes and addition of UIModalPresentationFormSheet overlay

### LINKED ISSUE #2113: UIViewController UIModalPresentationFormSheet needs an overlay
Parent window of modal needs to by covered by a view when a modal is presented. Currently it's possible to interact with the parent while it's presenting a modal - divergence from ref platform (note: patch in progress).

### PR DESCRIPTION
**Pull request by ehren**
Fixes #2113 and #2114. In addition, fixes to bring the invocation order of the view[Did/Will][Appear/Disappear] events in line with the ref platform have had to take #2115 into account (commit 20a4224 from March 19 has a better approach for working around #2115 than the initial commits to this pull).

Notes:

I went with the block based animation to avoid need for a CATransaction (form sheet overlay and the modal view itself have separate layers).

I've also been using a modified version of the testcase in #2194 to validate the order of the [will/did]MoveTo[Superview/Window] events. WinObjC differs from the ref platform (which for example, seems to move the view of a controller completely covered by a modal to an offscreen dummy window first and then removes it from that dummy window entirely, while WinObjC just leaves them in the view hierarchy). However, these changes do a better job of the ordering of the window/superview events vs the view controller appearance events (for example the window/superview events should be finished by the time of viewDidAppear); though, this is not something validated by the testcase in #2194.

### CODE REVIEW

File: Frameworks/UIKit/UIViewController.mm [hunk 1]
```diff
@@ -1207,43 +1196,40 @@ - (void)presentViewController:(UIViewController*)controller animated:(BOOL)anima
...
     [controller view];
+    priv->_presentedViewController = controller;
     controller->priv->_parentViewController = self;
     controller->priv->_presentingViewController = self;
 
     if ([controller modalPresentationStyle] == UIModalPresentationPopover) {
         controller->priv->_popoverPresentationController.attach(
             [[UIPopoverPresentationController alloc] initWithPresentedViewController:controller presentingViewController:self]);
 
+        // Keep popoverPresentationController alive until presentation complete. Fixes a corner case crash where the
```
Comment (ehren) [inline Frameworks/UIKit/UIViewController.mm]: crash exposed by testcase in #2194

File: Frameworks/UIKit/UIPopoverPresentationController.mm [hunk 2]
```diff
@@ -79,7 +71,6 @@ @implementation UIPopoverPresentationController {
     StrongId<UIBarButtonItem*> _barButtonItem;
     StrongId<UIView*> _sourceView;
     CGRect _sourceRect;
-    StrongId<dispatch_block_t> _dismissCompletion;
```
Comment (ehren) [inline Frameworks/UIKit/UIPopoverPresentationController.mm]: No need for a private dismissCompletion API anymore (for the one user UIViewController.mm). This was used for the unlinking of the modal from the parent which is now handled in WYPopoverController (doing the unlinking after didDismissPopover is way too late).

**Comment by ehren** [comment]
The addition of the extension to access the modalOverlayView is to make hacks like http://stackoverflow.com/questions/9102497/dismiss-modal-view-form-sheet-controller-on-outside-tap much easier than on the ref platform.

File: Frameworks/UIKit/UIViewController.mm [hunk 3]
```diff
@@ -1207,43 +1196,40 @@ - (void)presentViewController:(UIViewController*)controller animated:(BOOL)anima
 
     [[UIApplication sharedApplication] beginIgnoringInteractionEvents];
 
-    if ([controller _hidesParent]) {
-        [self _notifyViewWillDisappear:animated];
-    }
-
-    priv->_presentedViewController = controller;
     [controller view];
```
Comment (ehren) [inline Frameworks/UIKit/UIViewController.mm]: reason for setting the presentedViewController after [controller view] (which implicitly can call viewDidLoad) is to match ref platform behavior; but this is not something validated by the #2194 testcase.

File: Frameworks/UIKit/UIViewController.mm [hunk 4]
```diff
@@ -1254,40 +1240,64 @@ - (void)dismissModalViewControllerAnimated:(BOOL)animated {
...
     if (controller != nil) {
-        [controller _notifyViewDidDisappear:TRUE];
+        [controller _notifyViewDidDisappear:animated];
     }
 }
 
-- (void)_dismissTransitionStopped:(id)anim finished:(BOOL)finished {
-    UIView* view = [priv->_dismissController view];
-    [[view layer] removeAnimationForKey:@"ModalDismiss"];
+- (void)_unlinkPresentedController {
```
Comment (ehren) [inline Frameworks/UIKit/UIViewController.mm]: rename of method made the diff worse but |_unlinkPresentedController| is the same method as the previous |_childDismissCleanup|.

File: Frameworks/UIKit/UIViewController.mm [hunk 5]
```diff
@@ -1380,85 +1380,66 @@ - (void)dismissViewControllerAnimated:(BOOL)animated completion:(void (^)(void))
...
-        [presented _notifyViewDidDisappear:NO];
-        [self _notifyViewDidAppear:animated];
-
-        cleanupCompletion();
+        [self _finishModalDismissAnimated:NO completion:completion];
     }
 }
 
-- (void)_notifyDidAppearAnimated:(UIView*)view {
+- (void)_notifyDidAppear:(UIView*)view animated:(BOOL)animated {
```
Comment (ehren) [inline Frameworks/UIKit/UIViewController.mm]: This is the scariest change in that there's no test coverage (previously only the animated code path used this method to recursively call viewDidAppear on any view/subview with an owning controller (likely the existing code relied on the default handling in UIView.mm to handle this in the non-animated case). I wanted to make sure there was no incorrect behavior change after disabling the default appearance handling in UIView.mm so this method is now invoked in the non-animated case as well. Note that the underlying scenario (the need to invoke appearance events for a controller whose view is a subview of a controller being presented via presentViewController) seems obscure. Same comments apply for the similar method that handles viewDidDisappear.

File: include/UIKit/UIViewController.h [hunk 6]
```diff
@@ -117,6 +117,7 @@ UIKIT_EXPORT_CLASS
 @property (readonly, nonatomic, strong) NSExtensionContext* extensionContext STUB_PROPERTY;
 @property (readonly, nonatomic, strong) UISearchDisplayController* searchDisplayController;
 @property (readonly, nonatomic, strong) UIView* viewIfLoaded STUB_PROPERTY;
+@property (readonly, nonatomic, strong) UIView* modalOverlayView; // WinObjC extension
```
Comment (ehren) [inline include/UIKit/UIViewController.h]: If there's no objection, I'm going to push a commit in the coming days to remove this added WinObjC extension from the header. I'll just leave an _ prefixed method in the .mm so that clients can access the modalOverlayView via performSelector.

File: Frameworks/UIKit/WYPopoverController.mm [hunk 7]
```diff
@@ -2634,8 +2639,12 @@ - (void)dismissPopoverAnimated:(BOOL)aAnimated
         }
 #endif
     };
+
+    UIPopoverPresentationController* popoverPresentationController = [viewController popoverPresentationController];
     
     void (^completionBlock)() = ^() {
+        // Keep popoverPresentationController alive via block-capture during teardown.
+        (void)popoverPresentationController;
```
Comment (jaredhms) [inline Frameworks/UIKit/WYPopoverController.mm]: > (void)popoverPresentationController; [](start = 7, length = 37)

nit: might be a bit more clear to do an assignment to a local variable 'strongPopoverPresentationController', rather than this.

File: Frameworks/UIKit/UIViewController.mm (hunk 3 above)
Comment (jaredhms) [inline Frameworks/UIKit/UIViewController.mm]: can you add a comment here so we know not to reorder it in the future?

---
In reply to: [106151392](https://github.com/Microsoft/WinObjC/pull/2195#discussion_r106151392) [](ancestors = 106151392)

File: Frameworks/UIKit/UIViewController.mm [hunk 8]
```diff
@@ -1207,43 +1188,40 @@ - (void)presentViewController:(UIViewController*)controller animated:(BOOL)anima
...
 
     if ([controller modalPresentationStyle] == UIModalPresentationPopover) {
         controller->priv->_popoverPresentationController.attach(
             [[UIPopoverPresentationController alloc] initWithPresentedViewController:controller presentingViewController:self]);
 
+        // Keep popoverPresentationController alive until presentation complete. Fixes a corner case crash where the
+        // popover is dismissed, without animation, in the presentViewController completion block itself.
+        UIPopoverPresentationController* popover = [controller->priv->_popoverPresentationController retain];
+
         dispatch_block_t popoverPresent = ^{
```
Comment (jaredhms) [inline Frameworks/UIKit/UIViewController.mm]: >popoverPresent [](start = 25, length = 14)

nit: should this be called 'presentCompletion' for clarity?

File: Frameworks/UIKit/UIViewController.mm [hunk 9]
```diff
@@ -2148,6 +2103,17 @@ - (UIModalPresentationStyle)modalPresentationStyle {
...
 /**
+ @Status Caveat
+ @Notes  WinObjC-only extension providing access
+         to UIModalPresentationFormSheet overlay.
+         Not exposed in header (clients must access
+         via performSelector).
+*/
+- (UIView*)_modalOverlayView {
+    return priv->_modalOverlayView;
+}
```
Comment (jaredhms) [inline Frameworks/UIKit/UIViewController.mm]: I don't see this used anywhere; is it needed?  Also, we shouldn't be annotating internal/private methods.

Comment (ehren) [inline Frameworks/UIKit/UIViewController.mm]: That's needed to allow users to interact with the overlay view, typically to dismiss the modal on overlay-touch (by attaching a gesture recognizer). I didn't want to expose this in the public header, instead forcing the user to access via performSelector (since it requires private API on iOS, but it's often done). What about a commit adding dismiss via touch on overlay to the modal example in WOCCatalog? (will also remove the annotations from the method comment while I'm at it)

Comment (jaredhms) [inline Frameworks/UIKit/UIViewController.mm]: sounds good - i'm about to pull your changes and try them out locally

---
In reply to: [109035577](https://github.com/Microsoft/WinObjC/pull/2195#discussion_r109035577) [](ancestors = 109035577)

File: Frameworks/UIKit/WYPopoverController.mm (hunk 7 above)
Comment (ehren) [inline Frameworks/UIKit/WYPopoverController.mm]: There's an implicitly strong local defined just above (ARC's enabled) but I need to keep its lifetime tied to that completionBlock via a capture. Unfortunately, I can't say do ```assert(popoverPresentationController != nil);``` in the body of the block since it can be nil in the current implementation with the deprecated UIPopoverController API. I'm inclined to leave as is but the best alternative would probably be to use ```popoverPresentationController``` in a logging statement in the block body.

File: Frameworks/UIKit/UIViewController.mm (hunk 8 above)
Comment (ehren) [inline Frameworks/UIKit/UIViewController.mm]: fixed in latest.

File: Frameworks/UIKit/WYPopoverController.mm (hunk 7 above)
Comment (ehren) [inline Frameworks/UIKit/WYPopoverController.mm]: or an explicit ivar is doable too

Comment (jaredhms) [inline Frameworks/UIKit/WYPopoverController.mm]: I was suggesting something like: UIPopoverPresentationController* blockCapture = popoverPresentationController;

---
In reply to: [109064009](https://github.com/Microsoft/WinObjC/pull/2195#discussion_r109064009) [](ancestors = 109064009)

Comment (jaredhms) [inline Frameworks/UIKit/WYPopoverController.mm]: although this is probably fine - i just kicked off a CI build

---
In reply to: [109265389](https://github.com/Microsoft/WinObjC/pull/2195#discussion_r109265389) [](ancestors = 109265389,109064009)
