### PR TITLE
Handle empty lines, background drawing, and multicolor lines

### LINKED ISSUE #1130: Text Runs are not broken by color
WOCCatalog shows this regression. This would block the release.

### PR DESCRIPTION
**Pull request by aballway**
Handle edge case where a line is made up of white space, fix bug where trying to call CTRunDraw on a background thread would crash, and fix regression of not being able to have multiple colors in the same line.  

Fixes #1130, #1109, and #1171

### CODE REVIEW

File: Frameworks/CoreGraphics/CGContext.mm [hunk 1]
```diff
@@ -1242,3 +1242,7 @@ bool CGContextIsPointInPath(CGContextRef c, bool eoFill, CGFloat x, CGFloat y) {
 void CGContextDrawGlyphRun(CGContextRef ctx, const DWRITE_GLYPH_RUN* glyphRun) {
     ctx->Backing()->CGContextDrawGlyphRun(glyphRun);
 }
+// TODO 1077:: Remove once D2D render target is implemented
+void _CGContextSetScaleFactor(CGContextRef ctx, float scale) {
```
Comment (msft-Jeyaram) [inline Frameworks/CoreGraphics/CGContext.mm]: >ctx [](start = 43, length = 3)

could this be null?

if so add a null check

File: Frameworks/CoreGraphics/CGContextCairo.mm [hunk 2]
```diff
@@ -2037,4 +2042,9 @@
                                   DWRITE_MEASURING_MODE_NATURAL);
 
     THROW_IF_FAILED(imgRenderTarget->EndDraw());
+}
+
+// TODO 1077:: Remove once D2D render target is implemented
+void CGContextCairo::_CGContextSetScaleFactor(CGFloat scale) {
+    _scale = scale;
```
Comment (msft-Jeyaram) [inline Frameworks/CoreGraphics/CGContextCairo.mm]: >scale [](start = 13, length = 5)

this can be set to 0? and how is that handled in the arithmetic

File: Frameworks/CoreGraphics/CGContextCairo.mm [hunk 3]
```diff
@@ -2016,15 +2016,20 @@
...
     // transform calculation to be way off on devices that have scaling. Workaround for now is to divide the verticalScalingFactor and
     // height here with the device scaling factor so they get converted to DIPs and then apply the transform to the D2D render target.
-    // Though this workaround is sufficient to get text rendered on the user screen on all Windows form factor devices, this will not work
-    // when text is rendered on a PDF or printer.
-    static float hostDisplayScale = static_cast<float>([[WGDDisplayInformation getForCurrentView] resolutionScale] / 100.0f);
-    verticalScalingFactor /= hostDisplayScale;
-    height /= hostDisplayScale;
+    // Though this workaround is sufficient to get text rendered on the user screen on all Windows form factor devices, this will not
+    // work when text is rendered on a PDF or printer.
+    verticalScalingFactor /= _scale;
```
Comment (msft-Jeyaram) [inline Frameworks/CoreGraphics/CGContextCairo.mm]: >_scale [](start = 29, length = 6)

sanitize 0? or are you already handling it?

**Comment by msft-Jeyaram** [comment]
> 

{}

---
Refers to: Frameworks/CoreGraphics/CGContextCairo.mm:74 in ff1ac10. [](commit_id = ff1ac10d27c7c380723def25df1d600292450269, deletion_comment = False)

**Comment by msft-Jeyaram** [comment]
>     }

not needed

---
Refers to: Frameworks/CoreText/DWriteWrapper.mm:129 in ff1ac10. [](commit_id = ff1ac10d27c7c380723def25df1d600292450269, deletion_comment = False)

File: Frameworks/CoreGraphics/CGContext.mm (hunk 1 above)
Comment (aballway) [inline Frameworks/CoreGraphics/CGContext.mm]: no, this is only called from one place where ctx will be non-null and scale will be either 1.0 or 2.0

**Comment by aballway** [comment]
>     }

I think this is in the wrong place?

---
In reply to: [254926542](https://github.com/Microsoft/WinObjC/pull/1186#issuecomment-254926542) [](ancestors = 254926542)

---
Refers to: Frameworks/CoreText/DWriteWrapper.mm:129 in ff1ac10. [](commit_id = ff1ac10d27c7c380723def25df1d600292450269, deletion_comment = False)

**Comment by msft-Jeyaram** [comment]
>     if (DEBUG_VERBOSE) {

not needed.

---
Refers to: Frameworks/QuartzCore/CALayer.mm:497 in ff1ac10. [](commit_id = ff1ac10d27c7c380723def25df1d600292450269, deletion_comment = False)

File: tests/testapps/CTCatalog/CTCatalog/Tests/CTCRunTestViewController.mm [hunk 4]
```diff
@@ -84,7 +84,7 @@ - (void)drawRect:(CGRect)rect {
     CTRunRef run = static_cast<CTRunRef>(CFArrayGetValueAtIndex(runs, 0));
 
     // Flips y-axis for our frame
-    CGContextSetTextPosition(context, 0.0, 10.0);
+    CGContextSetTextPosition(context, 0.0, 0.0);
```
Comment (rajsesh-msft) [inline tests/testapps/CTCatalog/CTCatalog/Tests/CTCRunTestViewController.mm]: >. [](start = 44, length = 1)

Does this result in correct behavior in ref platform?

File: Frameworks/include/CGContextCairo.h [hunk 5]
```diff
@@ -136,4 +139,7 @@ class CGContextCairo : public CGContextImpl {
     virtual CGPathRef CGContextCopyPath(void);
 
     virtual void CGContextDrawGlyphRun(const DWRITE_GLYPH_RUN* glyphRun);
+
+    // TODO 1077:: Remove once D2D render target is implemented
+    virtual void CGContextCairo::_CGContextSetScaleFactor(float scale);
```
Comment (rajsesh-msft) [inline Frameworks/include/CGContextCairo.h]: >CGContextCairo:: [](start = 17, length = 16)

remove CGContextCairo:: here

File: Frameworks/CoreGraphics/CGContextCairo.mm (hunk 3 above)
Comment (rajsesh-msft) [inline Frameworks/CoreGraphics/CGContextCairo.mm]: Yes, this *should* work in all device contexts.

---
In reply to: [84155655](https://github.com/Microsoft/WinObjC/pull/1186#discussion_r84155655) [](ancestors = 84155655)

**Comment by rajsesh-msft** [comment]
:shipit:

File: Frameworks/CoreGraphics/CGContextCairo.mm [hunk 6]
```diff
@@ -2016,15 +2016,20 @@
     CGFloat verticalScalingFactor = sqrt((transform.b * transform.b) + (transform.d * transform.d));
     // TODO::
     // Issue #1057 - CG today talks in Pixels but DirectWrite and D2D only understand DIPs. Because CG talks in Pixels,
-    // curState->curTransform contains both the device scaling factor and any user scale applied to it causing the below D2D render target
+    // curState->curTransform contains both the device scaling factor and any user scale applied to it causing the below D2D render
+    // target
```
Comment (ms-jihua) [inline Frameworks/CoreGraphics/CGContextCairo.mm]: nit: can you put this back on the previous line?

File: Frameworks/CoreText/DWriteWrapper.mm [hunk 7]
```diff
@@ -275,16 +275,26 @@ static CFStringRef _CFStringFromLocalizedString(IDWriteLocalizedStrings* localiz
     // TODO::
     // Iterate through all attributed string ranges and identify attributes so they can be used to -
     //  - set indentation
-    //  - set kern
     //  - etc.
     //  These can be done using the DWrite IDWriteTextFormat range property methods.
+
+    // Used to separate runs for attributes which DWrite does not handle until drawing (e.g. Foreground Color)
+    uint32_t incompatableAttributeFlag = 0;
```
Comment (ms-jihua) [inline Frameworks/CoreText/DWriteWrapper.mm]: >incompatable [](start = 13, length = 12)

nit: typo

File: Frameworks/CoreText/DWriteWrapper.mm [hunk 8]
```diff
@@ -275,16 +275,26 @@ static CFStringRef _CFStringFromLocalizedString(IDWriteLocalizedStrings* localiz
...
+
     NSRange attributeRange;
     for (size_t i = 0; i < [ts->_attributedString length]; i += attributeRange.length) {
         NSDictionary* attribs = [ts->_attributedString attributesAtIndex:i
                                                    longestEffectiveRange:&attributeRange
                                                                  inRange:{ i, [ts->_attributedString length] - i }];
 
         const DWRITE_TEXT_RANGE dwriteRange = { attributeRange.location, attributeRange.length };
+
+        ComPtr<IDWriteTypography> typography;
```
Comment (ms-jihua) [inline Frameworks/CoreText/DWriteWrapper.mm]: nit: would it be possible to put this chunk together with the chunk where it's used?

**Comment by ms-jihua** [comment]
:shipit:
