### PR TITLE
Fix the upside-down UIImage drawing encountered in IslandwoodNews.

### LINKED ISSUE #1827: [CGD2D Validation] WOCCatalog UISegmentedControl images upside-down.
image

### PR DESCRIPTION
**Pull request by DHowett-MSFT**
This pull request comprises two commits:
* One commit that fixes our upside-down image drawing. Cairo was taking a negative-height image to mean "draw upside-down", but D2D took that to mean "LOL everything is fine"...
    * On the reference platform, height -300 actually means "draw 300 points above the origin".
* One commit that reimplements _CGContextDrawImageRect, the workhorse for out 9patch image drawing code. This was validated independently.

Test 9patch image:
test9patch

UIImage rendering:
image

Fixes #1827.

### CODE REVIEW

**Comment by DHowett-MSFT** [comment]
Of note: The 9patch drawing code used to invoke the clipping stack and layer composition 9 times. :)

File: Frameworks/UIKit/UIImage.mm [hunk 1]
```diff
@@ -494,11 +494,16 @@ - (void)drawAtPoint:(CGPoint)point blendMode:(CGBlendMode)mode alpha:(float)alph
     pos.size.height = (img_width / _scale);
 
     srcRect.origin.x = 0;
-    srcRect.origin.y = img_height;
+    srcRect.origin.y = 0;
     srcRect.size.width = img_width;
-    srcRect.size.height = -img_height;
+    srcRect.size.height = img_height;
```
Comment (DHowett-MSFT) [inline Frameworks/UIKit/UIImage.mm]: Actually, since this dropped the use of DrawImageRect, srcRect can be removed entirely.

**Comment by DHowett-MSFT** [comment]
Validated with `@2x` images as well.

File: Frameworks/CoreGraphics/CGContext.mm [hunk 2]
```diff
@@ -2494,15 +2494,27 @@ void CGContextDrawImage(CGContextRef context, CGRect rect, CGImageRef image) {
     NOISY_RETURN_IF_NULL(context);
     NOISY_RETURN_IF_NULL(image);
 
+    CGSize imageSize{
```
Comment (aballway) [inline Frameworks/CoreGraphics/CGContext.mm]: 👍

File: Frameworks/UIKit/UIImage.mm [hunk 3]
```diff
@@ -494,11 +494,16 @@ - (void)drawAtPoint:(CGPoint)point blendMode:(CGBlendMode)mode alpha:(float)alph
...
 
-    _CGContextDrawImageRect(cur, img, srcRect, pos);
+    // |1  0 0| is the transformation matrix for flipping a rect about its Y midpoint m. (m = (y + h/2))
+    // |0 -1 0|
+    // |0 2m 1|
+    CGContextConcatCTM(cur, CGAffineTransformMake(1,0,0,-1,0,2*(pos.origin.y+(pos.size.height/2))));
```
Comment (aballway) [inline Frameworks/UIKit/UIImage.mm]: nit: pls the spaces

File: Frameworks/UIKit/UIImage.mm [hunk 4]
```diff
@@ -545,6 +550,11 @@ static inline void drawPatches(CGContextRef context, UIImage* img, CGRect* dst)
     const float dstLeftCap = img->_imageInsets.left;
     const float dstRightCap = img->_imageInsets.right;
 
+    // |1  0 0| is the transformation matrix for flipping a rect about its Y midpoint m. (m = (y + h/2))
+    // |0 -1 0|
+    // |0 2m 1|
+    CGContextConcatCTM(context, CGAffineTransformMake(1,0,0,-1,0,2*(dstY+(dstHeight/2))));
```
Comment (aballway) [inline Frameworks/UIKit/UIImage.mm]: nit: same as above

**Comment by DHowett** [comment]
Consider moving 9patch drawing into CoreGraphics as a shared feature.
If the bitmap is not in a D2D-compliant format, this will save us 8(!) image copies, at the cost of having more of the complexity in CG.

It will also fix shadowing a 9patch image: right now, each section is shadowed independently and their draw order can influence shadow layering.

**Comment by msft-Jeyaram** [comment]
++ 

---
In reply to: [275712723](https://github.com/Microsoft/WinObjC/pull/1847#issuecomment-275712723) [](ancestors = 275712723)
