### PR TITLE
Change fonts used in unit tests to even more common ones

### LINKED ISSUE #1231: Unit tests failure in lab (desktop and phone) from ct-dw merge
The tests pass on build server, only the lab runs fail.

[unittests_failure.zip](https://github.com/Microsoft/WinObjC/files/554212/unittests_failure.zip)

### PR DESCRIPTION
**Pull request by ms-jihua**
Fixes #1231

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/winobjc/1234)

### CODE REVIEW

File: tests/unittests/UIKit/UIFontTests.mm [hunk 1]
```diff
@@ -108,8 +108,8 @@
 
 TEST(UIFont, Metrics) {
     float size = 22.0f;
-    UIFont* font = [UIFont fontWithName:@"Segoe UI Semibold Italic" size:size];
-    ASSERT_OBJCEQ(@"Segoe UI Semibold Italic", [font fontName]);
+    UIFont* font = [UIFont fontWithName:@"Segoe UI" size:size];
+    ASSERT_OBJCEQ(@"Segoe UI", [font fontName]);
 
     ASSERT_NE(0, [font descender]);
```
Comment (msft-Jeyaram) [inline tests/unittests/UIKit/UIFontTests.mm]: EXPECT_NE

Comment (ms-jihua) [inline tests/unittests/UIKit/UIFontTests.mm]: out of scope for this review - this change is both time-sensitive, and due to the nature of the bug, I'd like to minimize risk and keep this change as small as possible. we can address other things if tests pass in the lab tonight, so please file non-showstopper feedback as separate issues.

---
In reply to: [85243923](https://github.com/Microsoft/WinObjC/pull/1234#discussion_r85243923) [](ancestors = 85243923)

Comment (msft-Jeyaram) [inline tests/unittests/UIKit/UIFontTests.mm]: If it's time sensitive, understood.

---
In reply to: [85244713](https://github.com/Microsoft/WinObjC/pull/1234#discussion_r85244713) [](ancestors = 85244713,85243923)
