### PR TITLE
Disable NSURLSession DownloadTaskWithURL_WithCancelResume test

### LINKED ISSUE #1737: NSURL::NSURLSession_DownloadTaskWithURL_WithCancelResume is failing intermittently
I see 2 different failures.
Sometimes we get:
File download should be in progress! Expected: (currentBytesDownloaded) > (lastBytesDownloaded), actual: 1.91231 vs 1.91231

Other times it is:
File download should have stopped! Value of: lastBytesDownloaded Actual: 1.47247 Expected: currentBytesDownloaded Which is: 1.47385

Also, we have only seen this on win32 release.

### PR DESCRIPTION
**Pull request by aballway**
It seems NSURLSession DownloadTaskWithURL_WithCancelResume is still finnicky.  This disables the test until a better testing method is implemented.

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/winobjc/1740)

### CODE REVIEW

File: tests/functionaltests/Tests/NSURLSession.mm [hunk 1]
```diff
@@ -673,14 +670,12 @@ inline int _GetLastDelegateCall(NSURLSessionDownloadTaskTestHelper* downloadTask
     [conditionCancelled unlock];
 
     // Make sure download has stopped.
-    lastBytesDownloaded = (double)downloadTaskTestHelper.totalBytesWritten / 1024 / 1024;
     [NSThread sleepForTimeInterval:0.5];
-    currentBytesDownloaded = (double)downloadTaskTestHelper.totalBytesWritten / 1024 / 1024;
-    ASSERT_EQ_MSG(currentBytesDownloaded, lastBytesDownloaded, "FAILED: File download should have stopped!");
+    ASSERT_EQ(NSURLSessionTaskStateCanceling, downloadTask.state);
```
Comment (DHowett-MSFT) [inline tests/functionaltests/Tests/NSURLSession.mm]: Can it still be "canceling but not cancelled" at this point?

Comment (aballway) [inline tests/functionaltests/Tests/NSURLSession.mm]: As I understand it Canceling is "Cancelled"

File: tests/functionaltests/Tests/NSURLSession.mm [hunk 2]
```diff
@@ -645,14 +645,11 @@ inline int _GetLastDelegateCall(NSURLSessionDownloadTaskTestHelper* downloadTask
...
     LOG_INFO("Download in progress - %fMB", lastBytesDownloaded);
     [NSThread sleepForTimeInterval:0.5];
-    double currentBytesDownloaded = (double)downloadTaskTestHelper.totalBytesWritten / 1024 / 1024;
-    LOG_INFO("Download in progress - %fMB", currentBytesDownloaded);
-    ASSERT_GT_MSG(currentBytesDownloaded, lastBytesDownloaded, "FAILED: File download should be in progress!");
+    ASSERT_EQ(NSURLSessionTaskStateRunning, downloadTask.state);
     [NSThread sleepForTimeInterval:0.5];
-    lastBytesDownloaded = currentBytesDownloaded;
-    currentBytesDownloaded = (double)downloadTaskTestHelper.totalBytesWritten / 1024 / 1024;
+    double currentBytesDownloaded = (double)downloadTaskTestHelper.totalBytesWritten / 1024 / 1024;
```
Comment (msft-Jeyaram) [inline tests/functionaltests/Tests/NSURLSession.mm]: .f

floating point arithmetic

File: tests/functionaltests/Tests/NSURLSession.mm [hunk 3]
```diff
@@ -673,14 +670,12 @@ inline int _GetLastDelegateCall(NSURLSessionDownloadTaskTestHelper* downloadTask
     [conditionCancelled unlock];
 
     // Make sure download has stopped.
-    lastBytesDownloaded = (double)downloadTaskTestHelper.totalBytesWritten / 1024 / 1024;
     [NSThread sleepForTimeInterval:0.5];
-    currentBytesDownloaded = (double)downloadTaskTestHelper.totalBytesWritten / 1024 / 1024;
-    ASSERT_EQ_MSG(currentBytesDownloaded, lastBytesDownloaded, "FAILED: File download should have stopped!");
+    ASSERT_EQ(NSURLSessionTaskStateCanceling, downloadTask.state);
+    lastBytesDownloaded = (double)downloadTaskTestHelper.totalBytesWritten / 1024 / 1024;
```
Comment (msft-Jeyaram) [inline tests/functionaltests/Tests/NSURLSession.mm]: same here

File: tests/functionaltests/Tests/NSURLSession.mm (hunk 2 above)
Comment (aballway) [inline tests/functionaltests/Tests/NSURLSession.mm]: (float) / (integral) => float #WontFix

File: tests/functionaltests/Tests/NSURLSession.mm [hunk 4]
```diff
@@ -673,14 +670,12 @@ inline int _GetLastDelegateCall(NSURLSessionDownloadTaskTestHelper* downloadTask
     [conditionCancelled unlock];
 
     // Make sure download has stopped.
-    lastBytesDownloaded = (double)downloadTaskTestHelper.totalBytesWritten / 1024 / 1024;
     [NSThread sleepForTimeInterval:0.5];
```
Comment (bbowman) [inline tests/functionaltests/Tests/NSURLSession.mm]: PLEASE PLEASE PLEASE NO.

This is *NOT* a good way to test this sort of thing. These tests should honestly be scrapped and rewritten using events / mocks / something so we aren't guessing on when it will complete. It just slows down things for everyone and only adds minimal more reliability because they still hit real endpoints that could take arbitrary time to respond ....

**Comment by bbowman** [comment]
:clock1:

**Comment by DHowett-MSFT** [comment]
@bbowman Would you mind taking a look now that this disables the test?
We'll keep #1737 open to track the bug fix.
