### PR TITLE
Fix Figure Creation in CGPath

### LINKED ISSUE #1419: Fix creation of D2D figures when we use simplify to add geometries to path.

### PR DESCRIPTION
**Pull request by MSFTFox**
CGPath now only walks the path when the geometry is being drawn or accessed in some way. This is required as a D2D1PathGeometry must be closed in order to be queried for information or drawing which may cause unwanted figure closures.

Also adds the default fill mode for CGPath's geometry sinks to be D2D1_FILL_MODE_WINDING.

Fix #1419

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/winobjc/1738)

### CODE REVIEW

File: Frameworks/CoreGraphics/CGPath.mm [hunk 1]
```diff
@@ -35,6 +35,78 @@
...
 static const wchar_t* TAG = L"CGPath";
 
+using namespace Microsoft::WRL;
+
+class _CGPathCustomSink : public RuntimeClass<RuntimeClassFlags<RuntimeClassType::WinRtClassicComMix>, ID2D1SimplifiedGeometrySink> {
+protected:
+    InspectableClass(L"Windows.Bridge.Direct2D._CGPathCustomSink", TrustLevel::BaseTrust);
+
+public:
+    ID2D1GeometrySink* getBackingSink() {
```
Comment (aballway) [inline Frameworks/CoreGraphics/CGPath.mm]: nit: GetBackingSink

File: Frameworks/CoreGraphics/CGPath.mm [hunk 2]
```diff
@@ -35,6 +35,78 @@
...
+        return geometrySink.Get();
+    }
+
+    _CGPathCustomSink(_In_ ID2D1GeometrySink* sink) : geometrySink(sink), isFigureOpen(false) {
+    }
+
+    STDMETHOD_(void, _EndFigure)(D2D1_FIGURE_END figureEnd) {
```
Comment (aballway) [inline Frameworks/CoreGraphics/CGPath.mm]: are these necessary? In CoreText we just did void STDMETHODCALLTYPE fun()... type stuff

File: Frameworks/CoreGraphics/CGPath.mm [hunk 3]
```diff
@@ -35,6 +35,78 @@
...
+                _EndFigure(D2D1_FIGURE_END_OPEN);
+                geometrySink->BeginFigure(startPoint, figureBegin);
+            }
+        } else {
+            geometrySink->BeginFigure(startPoint, figureBegin);
+        }
+        isFigureOpen = true;
+    }
+
+    STDMETHOD_(void, EndFigure)(D2D1_FIGURE_END figureEnd) {
```
Comment (aballway) [inline Frameworks/CoreGraphics/CGPath.mm]: comments on why this is empty

File: Frameworks/CoreGraphics/CGPath.mm [hunk 4]
```diff
@@ -35,6 +35,78 @@
...
+    }
+
+    STDMETHOD(Close)() {
+        return S_OK;
```
Comment (aballway) [inline Frameworks/CoreGraphics/CGPath.mm]: same as above

File: Frameworks/CoreGraphics/CGPath.mm [hunk 5]
```diff
@@ -35,6 +35,78 @@
...
+    }
+
+    STDMETHOD_(bool, IsFigureOpen)() {
+        return isFigureOpen;
+    }
+
+private:
+    ComPtr<ID2D1GeometrySink> geometrySink;
+    D2D1_POINT_2F lastPoint;
+    bool isFigureOpen;
```
Comment (aballway) [inline Frameworks/CoreGraphics/CGPath.mm]: does this need to be threadsafe?

File: Frameworks/CoreGraphics/CGPath.mm [hunk 6]
```diff
@@ -35,6 +35,78 @@
...
+    STDMETHOD(_Close)() {
+        return geometrySink->Close();
+    }
+
+    STDMETHOD_(bool, IsFigureOpen)() {
+        return isFigureOpen;
+    }
+
+private:
+    ComPtr<ID2D1GeometrySink> geometrySink;
```
Comment (aballway) [inline Frameworks/CoreGraphics/CGPath.mm]: nit: m_geometrySink type names for variables.

File: Frameworks/CoreGraphics/CGPath.mm [hunk 7]
```diff
@@ -35,6 +35,78 @@
...
+    }
+
+    STDMETHOD_(void, EndFigure)(D2D1_FIGURE_END figureEnd) {
+    }
+
+    STDMETHOD(Close)() {
+        return S_OK;
+    };
+
+    STDMETHOD(_Close)() {
```
Comment (aballway) [inline Frameworks/CoreGraphics/CGPath.mm]: why do actual close in _Close?

File: Frameworks/CoreGraphics/CGPath.mm (hunk 2 above)
Comment (MSFTFox) [inline Frameworks/CoreGraphics/CGPath.mm]: The private endfigure call is necessary. We pass this to some D2D code which will be calling the normal EndFigure. We need to ignore those and end the figure ourselves.

---
In reply to: [96962369](https://github.com/Microsoft/WinObjC/pull/1738#discussion_r96962369) [](ancestors = 96962369)

File: Frameworks/CoreGraphics/CGPath.mm (hunk 7 above)
Comment (MSFTFox) [inline Frameworks/CoreGraphics/CGPath.mm]: We don't want the simplify method from D2D to call close and invalidate our figure work. We want full control over closing the geometrysink. If close is called, it may put our geometrysink in a bad state and prevent further calls.

---
In reply to: [96963185](https://github.com/Microsoft/WinObjC/pull/1738#discussion_r96963185) [](ancestors = 96963185)

**Comment by DHowett-MSFT** [comment]
> 

I'm not 100% happy that this has to go through the secret internal sink. I do understand why though.

---
Refers to: Frameworks/CoreGraphics/CGPath.mm:346 in 6c1aca3. [](commit_id = 6c1aca3b7e0ca84c3c2df5a36f759d8e017f67a6, deletion_comment = False)

File: Frameworks/CoreGraphics/CGPath.mm [hunk 8]
```diff
@@ -766,11 +860,14 @@ CGMutablePathRef CGPathCreateMutableCopyByTransformingPath(CGPathRef path, const
 
     if (transform && !CGAffineTransformEqualToTransform(*transform, CGAffineTransformIdentity)) {
         CGMutablePathRef transformedPath = CGPathCreateMutable();
-        path->ClosePath();
+        FAIL_FAST_IF_FAILED(path->ClosePath());
+
+        transformedPath->SetStartingPoint(CGPointApplyAffineTransform(path->GetStartingPoint(), *transform));
 
+        transformedPath->BeginFigure();
```
Comment (DHowett-MSFT) [inline Frameworks/CoreGraphics/CGPath.mm]: >BeginFigure [](start = 25, length = 11)

I wonder what happens if you take a mutable copy of a path with an open figure.. hm

File: Frameworks/CoreGraphics/CGPath.mm [hunk 9]
```diff
@@ -627,6 +720,7 @@ void CGPathAddCurveToPoint(CGMutablePathRef path,
     newSink->EndFigure(D2D1_FIGURE_END_OPEN);
     FAIL_FAST_IF_FAILED(newSink->Close());
 
+    path->BeginFigure();
```
Comment (DHowett-MSFT) [inline Frameworks/CoreGraphics/CGPath.mm]: >BeginFigure [](start = 10, length = 11)

Is this so? It doesn't seem like we should start a figure here.

File: Frameworks/CoreGraphics/CGPath.mm [hunk 10]
```diff
@@ -291,7 +383,8 @@ static HRESULT _createPathReadyForFigure(CGPathRef previousPath,
     ComPtr<ID2D1Factory> factory;
     RETURN_IF_FAILED(_CGGetD2DFactory(&factory));
     RETURN_IF_FAILED(factory->CreatePathGeometry(pathGeometry));
-    RETURN_IF_FAILED((*pathGeometry)->Open(geometrySink));
+    RETURN_IF_FAILED((*pathGeometry)->Open((ID2D1GeometrySink**)geometrySink));
```
Comment (DHowett-MSFT) [inline Frameworks/CoreGraphics/CGPath.mm]: >ID2D1GeometrySink [](start = 44, length = 17)

curious cast.

File: Frameworks/CoreGraphics/CGPath.mm (hunk 8 above)
Comment (MSFTFox) [inline Frameworks/CoreGraphics/CGPath.mm]: You mean without us closing it first?

---
In reply to: [96993664](https://github.com/Microsoft/WinObjC/pull/1738#discussion_r96993664) [](ancestors = 96993664)

File: Frameworks/CoreGraphics/CGPath.mm (hunk 9 above)
Comment (DHowett-MSFT) [inline Frameworks/CoreGraphics/CGPath.mm]: I suppose I don't understand why a beginfigure is necessary for this; comments  may help!
