### PR TITLE
Fix delegate dispatch order/threading in NSURLProtocol

### LINKED ISSUE #2521: NSURLProtocol and NSURLSession do not guarantee delegate dispatch order and thread
My last CI build failed in the test execution phase; I've seen this several times over the past few months.

2017-04-14T17:18:29.7225794Z Non-passing Tests:
2017-04-14T17:18:29.7225794Z 
2017-04-14T17:18:29.7225794Z ##[error]:     NSURLSessionTests::DataTaskWithURL_WithCompletionHandler [Failed]
2017-04-14T17:18:29.7225794Z 
2017-04-14T17:18:29.7225794Z Summary: Total=112, Passed=111, Failed=1, Blocked=0, Not Run=0, Skipped=0
2017-04-14T17:18:29.8913424Z ##[error]Process completed with exit code 1.

### PR DESCRIPTION
**Pull request by ms-jihua**
- Client callbacks now occur on client thread
- Client callbacks now have guaranteed order
- NSURLConnection/Session, which are built on top of Protocol, now also have guaranteed ordering/correct callback context
- Re-enabled NSURLSession tests
- Removed schedule/unscheduleInRunLoop: from NSURLProtocol - this is not a part of the contract and is unused even internally

Fixes #2521

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/winobjc/2697)

### CODE REVIEW

File: Frameworks/Foundation/NSURLConnection.mm [hunk 1]
```diff
@@ -346,118 +373,152 @@ - (void)cancel {
...
  @Status Interoperable
 */
-- (void)URLProtocol:(id)urlProtocol didReceiveAuthenticationChallenge:(id)challenge {
-    if ([_delegate respondsToSelector:@selector(connection:willSendRequestForAuthenticationChallenge:)]) {
-        [_delegate connection:self willSendRequestForAuthenticationChallenge:challenge];
-    } else {
-        [_delegate connection:self didReceiveAuthenticationChallenge:challenge];
-    }
+- (void)URLProtocol:(NSURLProtocol*)urlProtocol didReceiveAuthenticationChallenge:(NSURLAuthenticationChallenge*)challenge {
+    __block StrongId<NSURLConnection> strongSelf = self;
```
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSURLConnection.mm]: I believe using __block on these _avoids_ copying the `StrongId` -- self is therefore _not_ strongly held by the block.

File: Frameworks/Foundation/NSURLProtocol_WinHTTP.mm [hunk 2]
```diff
@@ -243,20 +244,35 @@ - (instancetype)initWithRequest:(NSURLRequest*)request
...
+    block();
+}
+
 - (void)startLoading {
     @synchronized(self) {
         if (_httpRequestOperation) {
             return;
         }
 
+        _clientThread = [NSThread currentThread];
```
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSURLProtocol_WinHTTP.mm]: Is it possible for the thread to be dismantled before we finish here?

File: Frameworks/Foundation/NSURLProtocol_WinHTTP.mm [hunk 3]
```diff
@@ -412,19 +428,24 @@ - (HRESULT)_asyncHttpOperation:(AsyncHttpOperation*)pOperation completedWithStat
 
                 // The location header can specify a relative or absolute URL: attempt to join it with the request URL.
                 NSURL* targetUrl = [NSURL URLWithString:Strings::WideToNSString(uriString.Get()) relativeToURL:[request URL]];
-                NSURLRequest* req = [NSURLRequest requestWithURL:targetUrl];
-                [self.client URLProtocol:self wasRedirectedToRequest:req redirectResponse:nsResponse];
+                __block StrongId<NSURLRequest> req = [NSURLRequest requestWithURL:targetUrl];
```
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSURLProtocol_WinHTTP.mm]: It's safe to just capture things in blocks normally; Strong semantics are preserved since blocks referring to `id` types will retain/release.

Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSURLProtocol_WinHTTP.mm]: (it's clearer, in fact, and avoids the StrongId machinery)

File: tests/functionaltests/Tests/NSURLSession.mm [hunk 4]
```diff
@@ -281,7 +281,6 @@ - (void)URLSession:(NSURLSession*)session downloadTask:(NSURLSessionDownloadTask
 public:
     BEGIN_TEST_CLASS(NSURLSessionTests)
     TEST_CLASS_PROPERTY(L"UAP:AppXManifest", L"NSURL.AppxManifest.xml")
-    TEST_CLASS_PROPERTY(L"ignore", L"true")
```
Comment (DHowett-MSFT) [inline tests/functionaltests/Tests/NSURLSession.mm]: there ma ybe other ignores on these tests; would you mind checking?

File: Frameworks/Foundation/NSURLProtocol_WinHTTP.mm (hunk 3 above)
Comment (ms-jihua) [inline Frameworks/Foundation/NSURLProtocol_WinHTTP.mm]: i completely failed to think this through oops

File: tests/functionaltests/Tests/NSURLSession.mm (hunk 4 above)
Comment (ms-jihua) [inline tests/functionaltests/Tests/NSURLSession.mm]: just the arm ones

File: Frameworks/Foundation/NSURLProtocol_WinHTTP.mm (hunk 2 above)
Comment (ms-jihua) [inline Frameworks/Foundation/NSURLProtocol_WinHTTP.mm]: er, i'm assuming by 'before we finish here' you mean the whole set of callbacks and not just this call. pretty sure it's possible, though not in our internal use-cases. with our current impl of performSelector:, this raises an exception. I think this is acceptable since letting the client thread die seems like programmer error.

File: Frameworks/Foundation/NSURLProtocol_WinHTTP.mm (hunk 3 above)
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSURLProtocol_WinHTTP.mm]: this file still has `__block StrongId`s!

File: Frameworks/Foundation/NSURLProtocol_WinHTTP.mm (hunk 2 above)
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSURLProtocol_WinHTTP.mm]: makes perfect sense. thanks!

File: Frameworks/Foundation/NSURLProtocol_WinHTTP.mm [hunk 5]
```diff
@@ -243,20 +244,35 @@ - (instancetype)initWithRequest:(NSURLRequest*)request
     };
 }
 
+// Helper function that executes a block on the client thread - used for client callbacks
+static void __dispatchClientCallback(NSURLProtocol_WinHTTP* protocol, void (^callbackBlock)()) {
+    if (protocol->_clientThread) {
+        [protocol performSelector:@selector(_invokeBlock:) onThread:protocol->_clientThread withObject:callbackBlock waitUntilDone:NO];
```
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSURLProtocol_WinHTTP.mm]: it's valid/specified for block objects to have an `invoke` method, so you could use `callbackBlock performSelector:@selector(invoke) ...`

Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSURLProtocol_WinHTTP.mm]: you know, I take that back. It's valid on the reference platform and on winobjc, but it isn't _specified in the [Language Specification for Blocks](https://clang.llvm.org/docs/BlockLanguageSpec.html)_

Comment (ms-jihua) [inline Frameworks/Foundation/NSURLProtocol_WinHTTP.mm]: 1) don't our NSBlocks not inherit from NSObject and thus not have that function?
2) our NSBlock has a comment on it that we ought to be reducing internal usage of the function. I think that's silly, but...

Comment (ms-jihua) [inline Frameworks/Foundation/NSURLProtocol_WinHTTP.mm]: mhm, it's considered hidden functionality

Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSURLProtocol_WinHTTP.mm]: 1. They do inherit NSObject! It's awesome/terrifying all at the same time.
2. Meh, I left that comment a long time ago because I didn't think `-invoke` was valid.

I did just test it, though:

```
(duhowett-mac) ~/woc/block % cat main.m
#include <stdio.h>

int main() {
        void (^x)() = ^{ fprintf(stderr, "lol?\n"); };
        [x invoke];
        return 0;
}
(duhowett-mac) ~/woc/block % ./main
lol?
```

Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSURLProtocol_WinHTTP.mm]: so if you want to do it, be my guest!

File: Frameworks/Foundation/NSURLProtocol_WinHTTP.mm [hunk 6]
```diff
@@ -395,10 +411,10 @@ - (HRESULT)_asyncHttpOperation:(AsyncHttpOperation*)pOperation completedWithStat
                 default:
                     httpVersionStr = nil;
             }
-            NSHTTPURLResponse* nsResponse = [[[NSHTTPURLResponse alloc] initWithURL:[request URL]
-                                                                         statusCode:statusCode
-                                                                        HTTPVersion:httpVersionStr
-                                                                       headerFields:nsHeaders] autorelease];
+            __block StrongId<NSHTTPURLResponse> nsResponse = [[[NSHTTPURLResponse alloc] initWithURL:[request URL]
```
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSURLProtocol_WinHTTP.mm]: I still don't think this one's necessary either

File: Frameworks/Foundation/NSURLProtocol_WinHTTP.mm (hunk 3 above)
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSURLProtocol_WinHTTP.mm]: (or this one, since `req` will be captured)

File: Frameworks/Foundation/NSURLProtocol_WinHTTP.mm [hunk 7]
```diff
@@ -495,10 +515,15 @@ - (void)_consumeDataStreamForIHttpContent:(IHttpContent*)pHttpContent {
             // We're opting to take a copy of the buffer here, as NSURLProtocol's consumer can legally expect the data
             // to remain valid long after the connection is gone. Eventually, it would be very nice to have an IBuffer-backed
             // NSData.
-            [self.client URLProtocol:strongSelf didLoadData:[NSData dataWithBytes:pOutputBuffer length:length]];
+            __block StrongId<NSData> data = [NSData dataWithBytes:pOutputBuffer length:length];
```
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSURLProtocol_WinHTTP.mm]: another one here :)
