### PR TITLE
Fix NSCalendar tests that fail on OSX

### LINKED ISSUE #744: NSCalendar tests fail on OSX
https://github.com/Microsoft/WinObjC/issues/743 may be related.

[ RUN      ] NSCalendar.GetDates
unknown file: Failure
Unknown C++ exception thrown in the test body.
[  FAILED  ] NSCalendar.GetDates (61 ms)

[ RUN      ] NSCalendar.CompareDates
Foundation/NSCalendarTests.mm:240: Failure
Value of: NSOrderedAscending
  Actual: -1
Expected: [calendar compareDate:date1 toDate:date2 toUnitGranularity:NSCalendarUnitNanosecond]
Which is: 0
[  FAILED  ] NSCalendar.CompareDates (0 ms)

[ RUN      ] NSCalendar.PreserveSmallerUnitsMatching
Foundation/NSCalendarTests.mm:345: Failure
Value of: actualDate
  Actual: 2012-02-29 08:00:00 +0000
Expected: expectedDate
Which is: 2012-02-29 11:04:05 +0000
[  FAILED  ] NSCalendar.PreserveSmallerUnitsMatching (5 ms)

[ RUN      ] NSCalendar.weekOfUnitMatching
Foundation/NSCalendarTests.mm:405: Failure
Value of: actualDate
  Actual: 2000-01-30 08:00:00 +0000
Expected: expectedDate
Which is: 2000-02-05 08:00:00 +0000
[  FAILED  ] NSCalendar.weekOfUnitMatching (7 ms)

[ RUN      ] NSCalendar.NSRangeValidation
Foundation/NSCalendarTests.mm:486: Failure
Value of: 5
Expected: range.length
Which is: 6
[  FAILED  ] NSCalendar.NSRangeValidation (0 ms)

### PR DESCRIPTION
**Pull request by MSFTFox**
Fixes #744

NSCalendar Tests have some failures as well as some unexpected behavior.
Some of the tests actually produce the correct results as described in the
documentation despite OSX actually producing incorrect results. These are
when the nanoseconds of two dates are compared using a calendar, when using
a matching flag that preserves smaller units when matching a leap date such as
February 29th, as well as the range of weeks in months always returning 6
despite not every month having 6 weeks.

These tests have been disabled for OSX.

### CODE REVIEW

File: Frameworks/Foundation/NSCFCalendar.mm [hunk 1]
```diff
@@ -594,6 +594,42 @@ - (void)enumerateDatesStartingAfterDate:(NSDate*)start
...
+
+    // This is a valid solo option as well as when used in conjunction with the others.
+    if (!isOptionsValid) {
+        isOptionsValid = ((opts & NSCalendarMatchStrictly) != 0);
+    }
+
+    THROW_NS_IF_FALSE_MSG(E_INVALIDARG,
+                          (isOptionsValid && !optionsAreInContrast),
+                          "Options must specify exactly one of these matching options: NSCalendarMatchPreviousTimePreservingSmallerUnits, "
+                          "NSCalendarMatchNextTimePreservingSmallerUnits, NSCalendarMatchNextTime");
```
Comment (rajsesh-msft) [inline Frameworks/Foundation/NSCFCalendar.mm]: This whole block could be simplified as:

if ( opts & NSCalendarMatchStrictly) != 0 && opts & NSCalendarMatchPreviousTimePreservingSmallerUnits) != 0 && (opts & NSCalendarMatchNextTimePreservingSmallerUnits != 0 || opts & NSCalendarMatchNextTime != 0)) {
         THROW_....
}

Comment (rajsesh-msft) [inline Frameworks/Foundation/NSCFCalendar.mm]: or not.. you do want one of these flags present, i see it now :)

---
In reply to: [73946729](https://github.com/Microsoft/WinObjC/pull/844#discussion_r73946729) [](ancestors = 73946729)

File: tests/unittests/Foundation/NSCalendarTests.mm [hunk 2]
```diff
@@ -481,15 +472,69 @@
...
+        // No matching options
+        NSDate* date = [calendar nextDateAfterDate:constantDate matchingComponents:comps options:0];
+
+        ASSERT_TRUE_MSG(false, "Should not have gotten here. nextDateAfterDate should throw an INVALID_ARG exception");
+    } @catch (NSException* e) {
+        ASSERT_OBJCEQ(e.name, @"NSInvalidArgumentException");
+    }
+}
+
+OSX_DISABLED_TEST(NSCalendar, DisabledCalendarTests) {
```
Comment (rajsesh-msft) [inline tests/unittests/Foundation/NSCalendarTests.mm]: >DisabledCalendarTests [](start = 30, length = 21)

I suggest you name this something else.

File: tests/unittests/Foundation/NSCalendarTests.mm [hunk 3]
```diff
@@ -481,15 +472,75 @@
...
+        NSDate* expectedNextDay = [calendar dateWithEra:1 year:2010 month:1 day:2 hour:0 minute:0 second:0 nanosecond:0];
+
+        NSDateComponents* comps = [[NSDateComponents alloc] init];
+        comps.day = 2;
+
+        // No matching options
+        NSDate* date = [calendar nextDateAfterDate:constantDate matchingComponents:comps options:0];
+
+        ASSERT_TRUE_MSG(false, "Should not have gotten here. nextDateAfterDate should throw an INVALID_ARG exception");
+    } @catch (NSException* e) {
```
Comment (bviglietta) [inline tests/unittests/Foundation/NSCalendarTests.mm]: >@catch (NSException* e) [](start = 6, length = 23)

Have you validated this test on ARM? I don't think we're able to catch exceptions there.

File: tests/unittests/Foundation/NSCalendarTests.mm [hunk 4]
```diff
@@ -481,15 +472,75 @@
...
+}
+
+OSX_DISABLED_TEST(NSCalendar, RangeOfWeekOfMonth) {
+    // Retrieving the range of a WeekOfMonth unit should return the number of weeks within the month for that date.
+    // The behavior on OSX however, is that the returned range is always 6 weeks regardless of the actual number of
+    // weeks in the given month.
+
+    NSCalendar* calendar = [NSCalendar calendarWithIdentifier:NSCalendarIdentifierGregorian];
+    NSDate* date = [calendar dateWithEra:1 year:2010 month:3 day:31 hour:3 minute:4 second:5 nanosecond:0];
+    NSRange range = [calendar rangeOfUnit:NSCalendarUnitWeekOfMonth inUnit:NSCalendarUnitYear forDate:date];
```
Comment (bviglietta) [inline tests/unittests/Foundation/NSCalendarTests.mm]: >rangeOfUnit:NSCalendarUnitWeekOfMonth inUnit:NSCalendarUnitYear [](start = 30, length = 63)

You're asking for the range within a year, not the range within a month. It sounds like OS X is doing the right thing by returning 6.

File: tests/unittests/Foundation/NSCalendarTests.mm [hunk 5]
```diff
@@ -481,15 +472,75 @@
...
+    ASSERT_EQ(range.location, 1);
+    ASSERT_EQ(range.length, 5);
+}
+
+OSX_DISABLED_TEST(NSCalendar, NSCalendarMatchNextTimePreservingSmallerUnitsLeapDay) {
+    // NSCalendarMatchNextTimePreservingSmallerUnits as a matching option does not reflect the documentation accurately.
+    // When matching a date, this option should preserve all smaller values when finding the next date. The behavior on OSX
+    // has instead stripped the date of these smaller values. The date matched from OSX is 2/29/2012 00:00:00 when it should be
+    // 2/29/2012 03:04:05. Thus, this test is disabled.
```
Comment (bviglietta) [inline tests/unittests/Foundation/NSCalendarTests.mm]: This behavior on OSX is not limited to leap days. It always trims the smaller units when it finds an exact match. The documentation is a little ambiguous, but I think this is the intended behavior, and we should probably match it.

**Comment by bviglietta** [comment]
:clock1:

File: Frameworks/CoreFoundation/Locale.subproj/CFCalendar.c [hunk 6]
```diff
@@ -746,6 +746,12 @@ static CFRange __CFCalendarGetRangeOfUnit2(CFCalendarRef calendar, CFCalendarUni
     // WINOBJC: Add cases for weekOf units. ICU will handle them below.
     case kCFCalendarUnitWeekOfYear:
```
Comment (bviglietta) [inline Frameworks/CoreFoundation/Locale.subproj/CFCalendar.c]: >case kCFCalendarUnitWeekOfYear: [](start = 4, length = 31)

Beware fallthrough.

File: Frameworks/CoreFoundation/Locale.subproj/CFCalendar.c [hunk 7]
```diff
@@ -746,6 +746,12 @@ static CFRange __CFCalendarGetRangeOfUnit2(CFCalendarRef calendar, CFCalendarUni
...
     case kCFCalendarUnitWeekOfMonth:
+    // WINOBJC: Asking for the range of WeekOfMonth in Year always returns 6.
```
Comment (bviglietta) [inline Frameworks/CoreFoundation/Locale.subproj/CFCalendar.c]: >Asking for the range of WeekOfMonth in Year always returns 6. [](start = 16, length = 61)

Why do we need a special case here? The logic in calculate: looks sound, as far as I can tell.

Comment (MSFTFox) [inline Frameworks/CoreFoundation/Locale.subproj/CFCalendar.c]: Calculate provides the number of weeks within that particular month if the larger unit is the year. As you pointed out previously, this is incorrect. The behavior is to always return 6 weeks. Thus we can return 6 here instead of relying on calculate.

---
In reply to: [74336418](https://github.com/Microsoft/WinObjC/pull/844#discussion_r74336418) [](ancestors = 74336418)

Comment (bviglietta) [inline Frameworks/CoreFoundation/Locale.subproj/CFCalendar.c]: OK, but that sounds like a bug in the calculate logic, or maybe in ICU underneath it. Do you know why you were getting that result? I would prefer to fix the error at the source if possible.

---
In reply to: [74342094](https://github.com/Microsoft/WinObjC/pull/844#discussion_r74342094) [](ancestors = 74342094,74336418)

Comment (bviglietta) [inline Frameworks/CoreFoundation/Locale.subproj/CFCalendar.c]: For example, maybe ucal_add doesn't do what we want when told to add one WeekOfMonth to a date? If that's the case, maybe calculate should set fieldToAdd to Week instead of WeekOfMonth. Just speculating.

---
In reply to: [74354002](https://github.com/Microsoft/WinObjC/pull/844#discussion_r74354002) [](ancestors = 74354002,74342094,74336418)

Comment (MSFTFox) [inline Frameworks/CoreFoundation/Locale.subproj/CFCalendar.c]: It seems to be an issue with ICU. Since ICU is operating on a particular date, and that date happens to not have 6 weeks in it, ICU will not update weekOfMonth to 6. It's essentially an out of bounds date component. Setting the smaller unit to week would instead return how many weeks are in the year. Even if we changed the unit to add to week, it would still not update to 6 weeks if the month does not have that because again, it's an out of bounds value for the unit of WeekOfMonth. To begin with, it doesn't make much sense to ask how many weeks are in a month in a year. I'm merely matching what the reference platform does in this case. I'd consider this a very low priority fringe case that doesn't provide much of a basis for changing core foundation code.

---
In reply to: [74354002](https://github.com/Microsoft/WinObjC/pull/844#discussion_r74354002) [](ancestors = 74354002,74342094,74336418)

Comment (bviglietta) [inline Frameworks/CoreFoundation/Locale.subproj/CFCalendar.c]: I think the question makes sense: it's asking what is the range of WeekOfMonth values within a year. Normally (always?) it can range from 1 to 6.

---
In reply to: [74356593](https://github.com/Microsoft/WinObjC/pull/844#discussion_r74356593) [](ancestors = 74356593,74354002,74342094,74336418)

Comment (bviglietta) [inline Frameworks/CoreFoundation/Locale.subproj/CFCalendar.c]: OK, I see the problem here. The calculate logic works by setting the starting date to the first moment in the larger unit, then advancing in increments of the smaller unit to find the min and max values. The problem is that this may not work correctly when the smaller unit doesn't divide the larger unit evenly.

For example, try getting the range of WeekOfMonth in Month for July 2016. The answer should be [1..6], but you will actually get [1..5].

This also explains why you sometimes get the wrong answer when asking for the range of WeekOfMonth in Year. It's not returning the number of weeks in the current month; it's advancing from Jan 1 week by week through the year, querying the WeekOfMonth each time.

The logic in calculate should be fixed.

---
In reply to: [74359393](https://github.com/Microsoft/WinObjC/pull/844#discussion_r74359393) [](ancestors = 74359393,74356593,74354002,74342094,74336418)

Comment (MSFTFox) [inline Frameworks/CoreFoundation/Locale.subproj/CFCalendar.c]: Yeah, it definitely seems like calculate has a few problems in it. Fixing that is beyond the scope of fixing the tests for OSX though. Could you file another issue for fixing the calculate function?

---
In reply to: [74461625](https://github.com/Microsoft/WinObjC/pull/844#discussion_r74461625) [](ancestors = 74461625,74359393,74356593,74354002,74342094,74336418)

Comment (bviglietta) [inline Frameworks/CoreFoundation/Locale.subproj/CFCalendar.c]: I opened bug 8463791 for this.

But I don't think we should put in the workaround that you have now for WeekOfMonth in Year. It's insufficient and not the right way to address the problem.

---
In reply to: [74468177](https://github.com/Microsoft/WinObjC/pull/844#discussion_r74468177) [](ancestors = 74468177,74461625,74359393,74356593,74354002,74342094,74336418)

Comment (MSFTFox) [inline Frameworks/CoreFoundation/Locale.subproj/CFCalendar.c]: It begs the question as to why other units are fast tracked to return constant values here though.  Everything from second up through hour seems incorrect to then return constant values. Especially given that there hopefully aren't 60 seconds in a year. These should also be addressed in the work done for fixing calculate.

I think the workaround to return a constant 6 is sufficient to match the reference platform on this one case for the time being. I've yet to find a case where it's incorrect even if it's a faulty mechanism for determining the actual values. Especially given the other short cuts that core foundation has already taken for those smaller values I think it's acceptable until the actual calculations are fixed.

---
In reply to: [74473193](https://github.com/Microsoft/WinObjC/pull/844#discussion_r74473193) [](ancestors = 74473193,74468177,74461625,74359393,74356593,74354002,74342094,74336418)

Comment (MSFTFox) [inline Frameworks/CoreFoundation/Locale.subproj/CFCalendar.c]: Looking into this further, I agree we shouldn't patch this with a constant 6 value. There's simply too many cases where this function returns the incorrect range and adding any additional patches just creates a bigger mess. Removing.

---
In reply to: [74478358](https://github.com/Microsoft/WinObjC/pull/844#discussion_r74478358) [](ancestors = 74478358,74473193,74468177,74461625,74359393,74356593,74354002,74342094,74336418)

File: tests/unittests/Foundation/NSCalendarTests.mm [hunk 8]
```diff
@@ -481,15 +481,63 @@
...
+
+        NSDateComponents* comps = [[NSDateComponents alloc] init];
+        comps.day = 2;
+
+        // No matching options
+        NSDate* date = [calendar nextDateAfterDate:constantDate matchingComponents:comps options:0];
+
+        ASSERT_TRUE_MSG(false, "Should not have gotten here. nextDateAfterDate should throw an INVALID_ARG exception");
+    } @catch (NSException* e) {
+        ASSERT_OBJCEQ(e.name, @"NSInvalidArgumentException");
```
Comment (DHowett-MSFT) [inline tests/unittests/Foundation/NSCalendarTests.mm]: You could make this test work on ARM with ASSERT_ANY_THROW. That would remove the need for both of these and the explicit catch.

Comment (DHowett-MSFT) [inline tests/unittests/Foundation/NSCalendarTests.mm]: If you're going to check the name of the exception, however, please use the constant `NSInvalidArgumentException`.

---
In reply to: [74656977](https://github.com/Microsoft/WinObjC/pull/844#discussion_r74656977) [](ancestors = 74656977)

File: tests/unittests/Foundation/NSCalendarTests.mm [hunk 9]
```diff
@@ -481,15 +481,63 @@
...
+    // is the same.
+
+    NSCalendar* calendar = [NSCalendar calendarWithIdentifier:NSCalendarIdentifierGregorian];
+    NSDate* date1 = [NSDate dateWithTimeIntervalSinceReferenceDate:.1];
+    NSDate* date2 = [NSDate dateWithTimeIntervalSinceReferenceDate:.9];
+    ASSERT_EQ([calendar compareDate:date1 toDate:date2 toUnitGranularity:NSCalendarUnitNanosecond], NSOrderedAscending);
+    ASSERT_EQ([calendar compareDate:date2 toDate:date1 toUnitGranularity:NSCalendarUnitNanosecond], NSOrderedDescending);
+}
+
+DISABLED_TEST(NSCalendar, rangeOfWeekOfMonthTest) {
```
Comment (DHowett-MSFT) [inline tests/unittests/Foundation/NSCalendarTests.mm]: >DISABLED_TEST [](start = 0, length = 13)

Does this test work on OS X?

**Comment by DHowett-MSFT** [comment]
:shipit:

File: tests/unittests/Foundation/NSCalendarTests.mm (hunk 9 above)
Comment (MSFTFox) [inline tests/unittests/Foundation/NSCalendarTests.mm]: Yes, I'll enable on OSX.

---
In reply to: [74657115](https://github.com/Microsoft/WinObjC/pull/844#discussion_r74657115) [](ancestors = 74657115)

**Comment by ms-jihua** [comment]
:shipit:
