### PR TITLE
Fix test file/file path-related issues in unit tests on OSX

### LINKED ISSUE #751: NSFileManager tests fail on OSX
Probably a test infrastructure issue?

[ RUN      ] NSFileManager.GetAttributes
[  INFO ] this test try to validate file creation date and modification date and size for /
Foundation/NSFileManagerTests.mm:76: Failure
Value of: [manager fileExistsAtPath:testFileFullPath]
  Actual: false
Expected: true
Failed: file /
[  FAILED  ] NSFileManager.GetAttributes (0 ms)
[ RUN      ] NSFileManager.EnumateDirectoryUsingURL
Foundation/NSFileManagerTests.mm:124: Failure
Value of: SetCurrentDirectoryW(startUpPath) != 0
  Actual: false
Expected: true
[  FAILED  ] NSFileManager.EnumateDirectoryUsingURL (0 ms)

### LINKED ISSUE #769: NSString tests fail on OSX (URL/file-related)
[ RUN      ] NSString.FromContentsOfURL
Foundation/ReferenceFoundation/TestNSString.mm:226: Failure
Expected: (nullptr) != (testFileURL), actual: NULL vs NULL
URL for NSStringTestData.txt is nil
[  FAILED  ] NSString.FromContentsOfURL (1 ms)
[ RUN      ] NSString.FromContentOfFile
Foundation/ReferenceFoundation/TestNSString.mm:245: Failure
Expected: (nullptr) != (testFilePath), actual: NULL vs NULL
[  FAILED  ] NSString.FromContentOfFile (1 ms)

[ RUN      ] NSString.StringByResolvingSymlinksInPath
Foundation/ReferenceFoundation/TestNSString.mm:644: Failure
Value of: expected
  Actual: /
Expected: result
Which is: /private
For absolute paths, all symbolic links are guaranteed to be removed.
[  FAILED  ] NSString.StringByResolvingSymlinksInPath (1 ms)

### LINKED ISSUE #777: NSURL tests fail on OSX
May be infrastructure issue, or need to ifdef based on platform:

[ RUN      ] NSURL.CheckResourceIsReachable
Foundation/NSURLTests.m:224: Failure
Value of: [targetURL checkResourceIsReachableAndReturnError:nullptr]
  Actual: false
Expected: true
The target URL data/NSFileManagerUT.txt -- file:///Volumes/WinObjC/tests/unittests/ exists
[  FAILED  ] NSURL.CheckResourceIsReachable (3 ms)

[ RUN      ] NSURL.FileURLWithPath_relativeToURL
Foundation/ReferenceFoundation/TestNSURL.mm:173: Failure
Value of: homeURL.path
  Actual: /Users/jihua
Expected: [NSString stringWithCString:gBaseCurrentWorkingDirectoryPath.data() encoding:NSUTF8StringEncoding]
Which is: /Volumes/WinObjC/tests/unittests
[  FAILED  ] NSURL.FileURLWithPath_relativeToURL (5 ms)
[ RUN      ] NSURL.URLStrings
unknown file: Failure
Unknown C++ exception thrown in the test body.
[  FAILED  ] NSURL.URLStrings (0 ms)

[ RUN      ] NSURL.URLByResolvingSymlinksInPath
Foundation/ReferenceFoundation/TestNSURL.mm:482: Failure
Value of: expected
  Actual: file:////Volumes/WinObjC/tests/unittests/~
Expected: result
Which is: file:///Volumes/WinObjC/tests/unittests/~
URLByResolvingSymlinksInPath resolves relative paths using current working directory.
[  FAILED  ] NSURL.URLByResolvingSymlinksInPath (1 ms)
[ RUN      ] NSURL.String
unknown file: Failure
Unknown C++ exception thrown in the test body.
[  FAILED  ] NSURL.String (1 ms)

### LINKED ISSUE #779: NSPropertyList tests fail on OSX
[----------] 3 tests from NSPropertyList
[ RUN      ] NSPropertyList.BasicConstruction
[       OK ] NSPropertyList.BasicConstruction (0 ms)
[ RUN      ] NSPropertyList.Decode
Foundation/ReferenceFoundation/TestNSPropertyList.mm:47: Failure
Expected: decoded = [NSPropertyListSerialization propertyListWithData:data options:0 format:&format error:&error] doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] NSPropertyList.Decode (1 ms)
[ RUN      ] NSPropertyList.DecodeMutable
Foundation/ReferenceFoundation/TestNSPropertyList.mm:69: Failure
Expected: (decoded) != (nullptr), actual: NULL vs NULL
[  FAILED  ] NSPropertyList.DecodeMutable (1 ms)
[----------] 3 tests from NSPropertyList (3 ms total)

### LINKED ISSUE #794: OSX Unit test run should support file staging
NSFileManager & NSFileHandler expect some files to be present in the location where the test is being executed. The OSX unit test should be able to stage the files (already present in Foundation)

### PR DESCRIPTION
**Pull request by ms-jihua**
- Updated the way Foundation.UnitTests.exe is built, so that test files are in the correct relative path
    - Makefile for Foundation.UnitTests.exe moved tests/unitests -> tests/unittests/Foundation
    - Output location for Foundation.UnitTests.exe moved tests/unittests -> build/Tests/UnitTests/Foundation/OSX
    - Output location for .o files moved build/Tests/UnitTests/Foundation/OSX -> build/Tests/UnitTests/Foundation/OSX/Objects
    - Test resource, data files now correctly copied to build/Tests/UnitTests/Foundation/OSX
- Fixed minor errors in shims, OSX file path/string handling in unit tests

Fixes #751
Fixes #777
Fixes #794
Fixes #779
Fixes #769

### CODE REVIEW

File: tests/unittests/Foundation/Makefile [hunk 1]
```diff
@@ -0,0 +1,96 @@
...
+
+clean:
+	$(RM) $(OUT_OBJ_DIR)/*.o
+	$(RM) -d $(OUT_OBJ_DIR)
+	$(RM) -d $(OUTDIR)/tmp/*
+	$(RM) -d $(OUTDIR)/tmp
+	$(RM) $(OUTDIR)/data/*
+	$(RM) -d $(OUTDIR)/data
+	$(RM) $(OUTDIR)/*.*
+	$(RM) $(OUTDIR)/*
```
Comment (DHowett-MSFT) [inline tests/unittests/Foundation/Makefile]: You can combine these all into a single `$(RM) -r "$(OUT_OBJ_DIR)" "$(OUTDIR)"`
It may also be good to put a `-` before `$(RM)`, to signify that an error can be ignored and should not result in a failure.

Comment (ms-jihua) [inline tests/unittests/Foundation/Makefile]: _Can_ we say that an error can be ignored?

---
In reply to: [73583033](https://github.com/Microsoft/WinObjC/pull/816#discussion_r73583033) [](ancestors = 73583033)

Comment (DHowett-MSFT) [inline tests/unittests/Foundation/Makefile]: I think it's safe here. It helps the case where you run `make clean all` without having an output directory (which is nonfatal), and the user is probably going to ignore the error from clean anyway.

If it's a problem with locking, the build will fail to copy it or the test will fail to interact with it, which hints at a deeper problem anyway.

---
In reply to: [73583199](https://github.com/Microsoft/WinObjC/pull/816#discussion_r73583199) [](ancestors = 73583199,73583033)

**Comment by ms-jihua** [comment]
>     *   YOU HAVE 9 DISABLED TESTS

We'll update this at the end of the week or something, but I just checked and we're currently down to 86 failed tests! Nice progress, everyone!

---
Refers to: docs/Testing/OSXWinObjCTests.md:185 in 1e85f5a. [](commit_id = 1e85f5a71efd67dc83eb3ba4b134b8ac638d7d54, deletion_comment = False)

File: tests/unittests/Foundation/NSFileManagerTests.mm [hunk 2]
```diff
@@ -118,14 +122,18 @@ void deleteFile(NSString* name) {
...
+#else
+    std::wstring startUpDir(startUpPath);
+    ASSERT_TRUE(SetCurrentDirectoryW(startUpDir.substr(0, startUpDir.find_last_of('/')).c_str()) != 0);
+#endif
+
     wchar_t currentDir[_MAX_PATH];
     DWORD ret = GetCurrentDirectoryW(_MAX_PATH, currentDir);
     ASSERT_TRUE(ret > 0 && ret < _MAX_PATH);
-    LOG_INFO("Change current dir to:%@", [NSString stringWithCharacters:(const unichar*)currentDir length:_MAX_PATH]);
+    LOG_INFO("Change current dir to:%@", [NSString stringWithBytes:currentDir length:sizeof(wchar_t) * ret encoding:WCHAR_ENCODING]);
```
Comment (ms-jihua) [inline tests/unittests/Foundation/NSFileManagerTests.mm]: Woops, this should be #ifdef'd

File: tests/unittests/Foundation/Makefile [hunk 3]
```diff
@@ -0,0 +1,96 @@
...
+
+$(OUTDIR)/% :
+	cp -f $(RF_RESOURCE_DIR)/$* $@
+
+$(OUTDIR)/data/NSFileManagerUT.txt :
+	mkdir -p $(OUTDIR)/data
+	cp -f $(SRCDIR)/NSFileManagerUT.txt $@
```
Comment (msft-Jeyaram) [inline tests/unittests/Foundation/Makefile]: can we place the files that are being staged into a certain folder.
This would make sure future staging files don't' have to be added to this make file.

Pretty much has a designated folder for staging and just copy it over.

**Comment by DHowett-MSFT** [comment]
:shipit:

**Comment by rajsesh-msft** [comment]
:shipit:
