### PR TITLE
Fix implementation of POST in NSURLConnection

### LINKED ISSUE #2468: Support uploading/POST in NSURLConnection & callbacks
Prerequisite: #2466

### PR DESCRIPTION
**Pull request by ms-jihua**
- Fix flawed reading of HTTPBodyStream in NSURLProtocol_WinHTTP
- Add support for
    connection:didSendBodyData:totalBytesWritten:totalBytesExpectedToWrite: and
    connection:didWriteData:totalBytesWritten:expectedTotalBytes:
- Add functional tests

Fixes #2468

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/winobjc/2720)

### CODE REVIEW

File: Frameworks/Foundation/NSURLProtocol_WinHTTP.mm [hunk 1]
```diff
@@ -151,34 +154,48 @@
...
+                                          [requestBody length]));
+
+        ComPtr<IHttpBufferContentFactory> httpBufferContentFactory;
+        THROW_IF_FAILED(GetActivationFactory(Wrappers::HStringReference(RuntimeClass_Windows_Web_Http_HttpBufferContent).Get(),
+                                             &httpBufferContentFactory));
+        THROW_IF_FAILED(httpBufferContentFactory->CreateFromBuffer(bodyBuffer.Get(), &httpContent));
+        THROW_IF_FAILED(httpRequestMessage->put_Content(httpContent.Get()));
+
+    } else if (NSInputStream* bodyStream = nsRequest.HTTPBodyStream) {
         // VSO 6693048: Properly support streaming bodies instead of flattening the data up front.
```
Comment (ms-jihua) [inline Frameworks/Foundation/NSURLProtocol_WinHTTP.mm]: Burned a few days trying to fix this as well, but the threading turns out to be super difficult to get right without C++/CX-y or C#-y language async support (Tried to implement own IASyncOperationWithProgress, tripped over threading requirements). Decided to cut losses and just go with this.

File: Frameworks/Foundation/NSURLConnection.mm [hunk 2]
```diff
@@ -513,4 +516,23 @@ - (void)URLProtocol:(NSURLProtocol*)protocol didCancelAuthenticationChallenge:(N
...
+            [_delegate connection:self
+                          didSendBodyData:bytesWritten
+                        totalBytesWritten:totalBytesWritten
+                totalBytesExpectedToWrite:totalBytesExpectedToWrite];
+        } else if ([_delegate respondsToSelector:@selector(connection:didWriteData:totalBytesWritten:expectedTotalBytes:)]) {
+            [_delegate connection:self
+                             didWriteData:bytesWritten
+                        totalBytesWritten:totalBytesWritten
+                totalBytesExpectedToWrite:totalBytesExpectedToWrite];
+        }
```
Comment (aballway) [inline Frameworks/Foundation/NSURLConnection.mm]: do we want to log any sort of warning if the delegate responds to neither?

File: Frameworks/Foundation/NSURLProtocol_WinHTTP.mm (hunk 1 above)
Comment (aballway) [inline Frameworks/Foundation/NSURLProtocol_WinHTTP.mm]: Does cppwinrt have the support you'd need?

File: Frameworks/Foundation/NSURLProtocol_WinHTTP.mm [hunk 3]
```diff
@@ -264,7 +283,20 @@ - (void)startLoading {
         NSError* error = nil;
 
         try {
-            auto httpRequestMessage = _requestMessageForNS(self.request);
+            auto httpRequestMessage = _requestMessageForNS(self.request, _flattenedBodyStream);
+
+            // VSO 6693048: If this properly supports streaming bodies instead of flattening the data up front,
+            // more accurate callbacks can be done
+            NSInteger contentSize = self.request.HTTPBody ? self.request.HTTPBody.length : _flattenedBodyStream.size();
```
Comment (aballway) [inline Frameworks/Foundation/NSURLProtocol_WinHTTP.mm]: nit: should this be NSUInteger?

File: tests/functionaltests/Tests/NSURLConnection.mm [hunk 4]
```diff
@@ -228,10 +283,15 @@ static void _testRequestWithURL(NSURLConnectionTestHelper* connectionTestHelper)
...
     ASSERT_EQ_MSG(NSURLConnectionDelegateDidReceiveData,
                   [(NSNumber*)[connectionTestHelper.delegateCallOrder objectAtIndex:1] integerValue],
-                  "FAILED: didReceiveData should be the first delegate to be called!");
+                  "FAILED: didReceiveData should be the 2nd delegate to be called!");
     ASSERT_TRUE_MSG((connectionTestHelper.data != nil), "FAILED: We should have received some data!");
     LOG_INFO("Received data: %@", [[NSString alloc] initWithData:connectionTestHelper.data encoding:NSUTF8StringEncoding]);
 
+    // Make sure we received a didFinishLoading callback
+    ASSERT_EQ_MSG(NSURLConnectionDelegateDidFinishLoading,
+                  [(NSNumber*)[connectionTestHelper.delegateCallOrder objectAtIndex:2] integerValue],
```
Comment (aballway) [inline tests/functionaltests/Tests/NSURLConnection.mm]: nit: ASSERT_OBJCEQ so you shouldn't have to cast it to NSNumber*

File: tests/functionaltests/Tests/NSURLConnection.mm [hunk 5]
```diff
@@ -240,37 +300,129 @@ static void _testRequestWithURL(NSURLConnectionTestHelper* connectionTestHelper)
...
+    for (int i = 0; (i < 5) && (!connectionTestHelper.done); ++i) {
+        [connectionTestHelper.doneCondition waitUntilDate:[NSDate dateWithTimeIntervalSinceNow:c_testTimeoutInSec]];
+    }
+    ASSERT_LE_MSG(4, [connectionTestHelper.delegateCallOrder count], "FAILED: We should have received 4 or more delegate calls by now!");
+    [connectionTestHelper.doneCondition unlock];
+
+    size_t index = 0;
+
+    // Should have received a number of didSendBodyData callbacks
+    for (;
```
Comment (aballway) [inline tests/functionaltests/Tests/NSURLConnection.mm]: this makes me sad

File: Frameworks/Foundation/NSURLConnection.mm (hunk 2 above)
Comment (ms-jihua) [inline Frameworks/Foundation/NSURLConnection.mm]: nah, it's valid for delegates to not care about all of the callbacks

File: Frameworks/Foundation/NSURLProtocol_WinHTTP.mm (hunk 1 above)
Comment (ms-jihua) [inline Frameworks/Foundation/NSURLProtocol_WinHTTP.mm]: We don't have access to concurrency runtime, so I'd eventually run into the same threading issues.

File: Frameworks/Foundation/NSURLProtocol_WinHTTP.mm (hunk 3 above)
Comment (ms-jihua) [inline Frameworks/Foundation/NSURLProtocol_WinHTTP.mm]: Nah, the downstream delegates want NSInteger https://developer.apple.com/reference/foundation/nsurlconnectiondatadelegate/1418264-connection?language=objc

File: tests/functionaltests/Tests/NSURLConnection.mm (hunk 5 above)
Comment (ms-jihua) [inline tests/functionaltests/Tests/NSURLConnection.mm]: i know...

File: tests/functionaltests/Tests/NSURLConnection.mm (hunk 4 above)
Comment (ms-jihua) [inline tests/functionaltests/Tests/NSURLConnection.mm]: good call

File: Frameworks/Foundation/NSURLProtocol_WinHTTP.mm (hunk 1 above)
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSURLProtocol_WinHTTP.mm]: it might be worthwhile to port this to a github ID :)

File: Frameworks/Foundation/NSURLProtocol_WinHTTP.mm [hunk 6]
```diff
@@ -264,7 +283,20 @@ - (void)startLoading {
...
+            if (contentSize > 0) {
+                __dispatchClientCallback(self, ^void() {
+                    [self.client URLProtocol:self
```
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSURLProtocol_WinHTTP.mm]: It seems curious to send this before the connection is established.

Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSURLProtocol_WinHTTP.mm]: though i guess this is the earliest viable time?

File: tests/functionaltests/Tests/NSURLConnection.mm [hunk 7]
```diff
@@ -155,11 +194,10 @@ - (void)dealloc {
...
 
 // Does nothing. Used to keep the run loop alive.
-- (void)doNothing {
-}
+- (void)doNothing{}
 
-// Keeps the run loop on the current thread spinning.
-- (void)spinRunLoop {
+    // Keeps the run loop on the current thread spinning.
+    - (void)spinRunLoop {
```
Comment (DHowett-MSFT) [inline tests/functionaltests/Tests/NSURLConnection.mm]: formatter gone mad

File: tests/functionaltests/Tests/NSURLConnection.mm [hunk 8]
```diff
@@ -240,37 +300,129 @@ static void _testRequestWithURL(NSURLConnectionTestHelper* connectionTestHelper)
...
+
+    NSData* nsData = [NSData dataWithBytesNoCopy:data.data() length:data.size() freeWhenDone:NO];
+
+    if (useStream) {
+        request.HTTPBodyStream = [NSInputStream inputStreamWithData:nsData];
+    } else {
+        request.HTTPBody = nsData;
+    }
+    request.HTTPMethod = @"POST";
+    [request setValue:[NSString stringWithFormat:@"%lu", data.size()] forHTTPHeaderField:@"Content-Length"];
```
Comment (DHowett-MSFT) [inline tests/functionaltests/Tests/NSURLConnection.mm]: The burden might be on `NSURLProtocol` to set the outgoing content-length, right?

Comment (DHowett-MSFT) [inline tests/functionaltests/Tests/NSURLConnection.mm]: Or to use the chunked transfer-encoding if the stream is of unknown length.

File: Frameworks/Foundation/NSURLProtocol_WinHTTP.mm (hunk 6 above)
Comment (ms-jihua) [inline Frameworks/Foundation/NSURLProtocol_WinHTTP.mm]: This won't actually send until the message is sent, since it's dispatching to the client thread. The other option would be to put this in _asyncHttpOperation:completedWithStatus:, but that seems too _late_...

File: tests/functionaltests/Tests/NSURLConnection.mm (hunk 8 above)
Comment (ms-jihua) [inline tests/functionaltests/Tests/NSURLConnection.mm]: Nope, checked on ref plat, burden is on caller.

File: tests/functionaltests/Tests/NSURLConnection.mm (hunk 4 above)
Comment (ms-jihua) [inline tests/functionaltests/Tests/NSURLConnection.mm]: our test macros interact poorly, using ASSERT_TRUE isEqual: instead

File: tests/functionaltests/Tests/NSURLConnection.mm [hunk 9]
```diff
@@ -281,16 +281,14 @@ static void _testRequestWithURL(NSURLConnectionTestHelper* connectionTestHelper)
     LOG_INFO("Received HTTP response headers: %d", [httpResponse allHeaderFields]);
 
     // Make sure we received data.
-    ASSERT_EQ_MSG(NSURLConnectionDelegateDidReceiveData,
-                  [(NSNumber*)[connectionTestHelper.delegateCallOrder objectAtIndex:1] integerValue],
-                  "FAILED: didReceiveData should be the 2nd delegate to be called!");
+    ASSERT_TRUE_MSG([@(NSURLConnectionDelegateDidReceiveData) isEqual:[connectionTestHelper.delegateCallOrder objectAtIndex:1]],
```
Comment (DHowett-MSFT) [inline tests/functionaltests/Tests/NSURLConnection.mm]: It's strange we can't use `OBJCEQ` :(

Comment (ms-jihua) [inline tests/functionaltests/Tests/NSURLConnection.mm]: Come to think of it, I think our ASSERT_OBJCEQ has problems with array and dictionary literals too...

Comment (aballway) [inline tests/functionaltests/Tests/NSURLConnection.mm]: The only issue I've seen with it is with objects that need commas, what error are you getting when trying to use OBJCEQ?  ASSERT_TRUE isn't that nice here since we don't actually see the values should it fail.

Comment (DHowett-MSFT) [inline tests/functionaltests/Tests/NSURLConnection.mm]: Oh, right. I hate those macros actually.

The way they're implemented, they'll break up the args to `ASSERT_OBJCEQ({@1, @2}, arr)` into `{@1`, `@2}` and `arr`, and then try to emit (simplified) `{@1 == @2}` (lel)

Comment (ms-jihua) [inline tests/functionaltests/Tests/NSURLConnection.mm]: 1>C:\WinObjC\tests\functionaltests\Tests\NSURLConnection.mm(313,5): error : 'testing' is not a class, namespace, or enumeration
