### PR TITLE
Re-implement NSOperationQueue

### LINKED ISSUE #869: NSOperationQueue is suboptimal (but it does work)
- Busy wait if an operation with dependencies is added, but the dependencies are not _yet_ added.
- Queue does not subscribe to notifications for operation status.
  - `isReady` could help avoid the busy wait.
- We only support three priority tiers out of the five which are defined.
- The magic inside `RunOperationFromLists` is arcane and black.
  - Takes the source list. Drops it down, flips it and reverses it.
  - That new list is the "pending" list. Operations are run preferentially from the pending list.
  - The pending list is unceremoniously destroyed (via `memset`) at the start of the next queue thread iteration.

### LINKED ISSUE #1655: Crash in -[NSOperationQueue _doMainWork]
We’re seeing the following crash in NSOperationQueue / NSAtomicList:

```
HEAP_CORRUPTION_ACTIONABLE_LFHSegmentDoubleFree_DOUBLE_FREE_c0000374_Foundation.dll!NSAtomicListPop

Frame	Image	Function	Offset
0	ntdll	RtlpHpLfhSubsegmentFreeBlock	0xE5	
1	ntdll	RtlpHpSegFree	0x5C	
2	ntdll	RtlpHpFreeHeap	0x18A	
3	ntdll	RtlpFreeHeapInternal	0x4F	
4	ntdll	RtlpHpFreeWithExceptionProtection	0x2E	
5	ntdll	RtlFreeHeap	0x4AADB	
6	ucrtbase	_free_base	0x1B	
7	ucrtbase	free	0x18	
8	Foundation	NSAtomicListPop	0x85	
9	Foundation	RunOperationFromLists	0x96	
10	Foundation	-[NSOperationQueue _doMainWork]	0xD0	
11	Foundation	-[NSOperationQueue _workThread]	0x1B	
12	Foundation	-[NSThread main]	0x4A	
13	Foundation	_threadBody	0x4D	
14	Starboard	ThreadRoutine	0x3F	
15	kernel32	BaseThreadInitThunk	0x24	
16	ntdll	__RtlUserThreadStart	0x2F	
17	ntdll	_RtlUserThreadStart	0x1B	
```

### LINKED ISSUE #2228: Add support for NSOperation queuePriority
We would like to see support for `NSOperation.queuePriority` to change the relative priority of an operation in a queue.

This might depend on or be part of #869.

### PR DESCRIPTION
**Pull request by ms-jihua**
- Add support for
    - queuePriority
    - underlyingQueue
    - currentQueue
    - maxConcurrentOperationCount
    - KVO-compliance
- Fixes some edge cases (ie: hanging on certain non-ready operations)
- Add unit tests
- Add performance benchmark tests

Fixes #2228
Fixes #1655
Fixes #869

### CODE REVIEW

File: Frameworks/Foundation/NSOperationQueue.mm [hunk 1]
```diff
@@ -1,443 +1,381 @@
...
+    switch (quality) {
+        case NSQualityOfServiceUserInteractive:
+            return QOS_CLASS_USER_INTERACTIVE;
+        case NSQualityOfServiceUserInitiated:
+            return QOS_CLASS_USER_INITIATED;
+        case NSQualityOfServiceUtility:
+            return QOS_CLASS_UTILITY;
+        case NSQualityOfServiceBackground:
+            // currently generates a warning:
+            // 'QOS_CLASS_BACKGROUND' is deprecated: QOS_CLASS_BACKGROUND is the same as DISPATCH_QUEUE_PRIORITY_LOW on WinObjC
```
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSOperationQueue.mm]: do we have an issue ID for this?

File: Frameworks/Foundation/NSOperationQueue.mm [hunk 2]
```diff
@@ -1,443 +1,381 @@
...
-#import "Platform/EbrPlatform.h"
-#import "Foundation/NSString.h"
-#import "Foundation/NSOperationQueue.h"
-#import "Foundation/NSThread.h"
-#import "Foundation/NSAutoreleasePool.h"
-#import "Foundation/NSLock.h"
-#import <time.h>
-#import "LoggingNative.h"
-#import "NSOperationInternal.h"
+@interface NSOperationQueue_MainQueue : NSOperationQueue
```
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSOperationQueue.mm]: If this is file-internal, i'd prefer a `_` prepended :smile:

File: Frameworks/Foundation/NSOperationQueue.mm [hunk 3]
```diff
@@ -1,443 +1,381 @@
...
+- (void)_setDispatchQueueUsingQualityOfService;
+@end
 
-    NSOperationQueuePriv() {
-        memset(this, 0, sizeof(NSOperationQueuePriv));
-        _threadRunningLock = PTHREAD_MUTEX_INITIALIZER;
-    }
-};
+@implementation NSOperationQueue {
+@private
```
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSOperationQueue.mm]: nit: prefer ivars on class extension above instead of implementation

File: Frameworks/Foundation/NSOperationQueue.mm [hunk 4]
```diff
@@ -1,443 +1,381 @@
...
-    id workAvailable;
-    id suspendedCondition;
-    id allWorkDone;
-    id curOperation;
-    BOOL isSuspended;
+#pragma region NSOperationQueue
 
-    id _name;
+@interface NSOperationQueue ()
+// Private member functions
```
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSOperationQueue.mm]: nit: comment redundant with location

Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSOperationQueue.mm]: (and with naming)

**Comment by ms-jihua** [comment]
Here are perf numbers, comparing on Release with this change, develop, and #1676 which we backed out:
image

Things to note:
- The time it takes to add 1000 operations individually has doubled from develop. However, if we look under the hood we see that 
image
90% of this time is spent in KVO (!!), which we are looking at next.
- The time it takes to add 1000 operations together, and wait for them to finish, has largely remained the same. However, unlike develop, not waiting for them to finish provides no significant time discount - it appears that unlike develop, we are bottlenecked by KVO rather than the process of executing the operations, so our perf should improve once we look at KVO.

File: Frameworks/Foundation/NSOperationQueue.mm [hunk 5]
```diff
@@ -1,443 +1,381 @@
...
-NSAtomicListRef NSAtomicListSteal(NSAtomicListRef* listPtr) {
-    NSAtomicListRef ret;
-    do {
-        ret = *listPtr;
-    } while (CompareExchangePointer((void**)listPtr, NULL, ret) != ret);
-    return ret;
-}
+    // Protects _dispatchQueue, _underlyingQueue, and _qualityOfService
+    // Should never be locked before _concurrentOperationCountLock
+    std::recursive_mutex _dispatchQueueLock;
```
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSOperationQueue.mm]: it worries me that we're mixing _dispatch_ queues with _STL_ mutexes and atomics.

File: Frameworks/Foundation/NSOperationQueue.mm [hunk 6]
```diff
@@ -1,443 +1,381 @@
...
 
-void NSAtomicListReverse(NSAtomicListRef* listPtr) {
-    struct NSAtomicListNode* cur = *listPtr;
-    struct NSAtomicListNode* prev = NULL;
-    struct NSAtomicListNode* next = NULL;
+    StrongId<NSMutableArray> _operations;
```
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSOperationQueue.mm]: Are operations inherently indexed? Do we need to use an ordered set here for quick removal?

File: Frameworks/Foundation/NSOperationQueue.mm [hunk 7]
```diff
@@ -1,443 +1,381 @@
...
+    std::lock_guard<std::recursive_mutex> lock(_concurrentOperationCountLock);
+    NSInteger maxOps = self.maxConcurrentOperationCount;
+    return (maxOps <= 0) || (_currentConcurrentOperationCount < maxOps);
 }
 
-NSObject* NSAtomicListPop(NSAtomicListRef* listPtr) {
-    struct NSAtomicListNode* node = *listPtr;
-    if (!node) {
-        return NULL;
+// Private helper that tries to starts a single NSOperation on the dispatch queue and manages associated state.
```
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSOperationQueue.mm]: nit: "tries to starts"

File: Frameworks/Foundation/NSOperationQueue.mm [hunk 8]
```diff
@@ -1,443 +1,381 @@
...
-    }
+        ++_currentConcurrentOperationCount;
+    } // _concurrentOperationCountLock scope
 
-    return node->elt;
-}
+    std::lock_guard<std::recursive_mutex> lock(_dispatchQueueLock);
+    dispatch_async(_dispatchQueue, ^{
+        // Check if currentQueue needs to be changed
+        NSMutableDictionary* threadDictionary = [[NSThread currentThread] threadDictionary];
```
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSOperationQueue.mm]: [Curiosity only]

Why'd you choose to use NSThread's thread dictionary instead of a thread_local?

File: Frameworks/Foundation/NSOperationQueue.mm [hunk 9]
```diff
@@ -1,443 +1,381 @@
...
+        case NSQualityOfServiceUserInteractive:
+            return QOS_CLASS_USER_INTERACTIVE;
+        case NSQualityOfServiceUserInitiated:
+            return QOS_CLASS_USER_INITIATED;
+        case NSQualityOfServiceUtility:
+            return QOS_CLASS_UTILITY;
+        case NSQualityOfServiceBackground:
+            // currently generates a warning:
+            // 'QOS_CLASS_BACKGROUND' is deprecated: QOS_CLASS_BACKGROUND is the same as DISPATCH_QUEUE_PRIORITY_LOW on WinObjC
+            // should go away once libdispatch is updated
```
Comment (ms-jihua) [inline Frameworks/Foundation/NSOperationQueue.mm]: #2241

File: Frameworks/Foundation/NSOperationQueue.mm [hunk 10]
```diff
@@ -1,443 +1,381 @@
...
-    NSOperationQueuePriv() {
-        memset(this, 0, sizeof(NSOperationQueuePriv));
-        _threadRunningLock = PTHREAD_MUTEX_INITIALIZER;
-    }
-};
+@implementation NSOperationQueue {
+@private
+    // The actual dispatch queue to which operations are dispatched
+    // Currently, changing between dispatch queues is done by reassigning this member
+    // TODO #:  WinObjC's libdispatch cannot create concurrent dispatch queues (DISPATCH_QUEUE_CONCURRENT just returns a serial queue)
```
Comment (ms-jihua) [inline Frameworks/Foundation/NSOperationQueue.mm]: #2241

File: Frameworks/Foundation/NSOperationQueue.mm [hunk 11]
```diff
@@ -1,443 +1,381 @@
...
+        if (needToChangeCurrentQueue) {
+            [threadDictionary setObject:self forKey:_NSOperationQueueCurrentQueueKey];
+        }
 
-    do {
-        node->next = *listPtr;
-    } while (CompareExchangePointer((void**)listPtr, node, node->next) != node->next);
-}
+        // Restore state once the operation is done, and attempt to start any queued operations
+        auto cleanup = wil::ScopeExit([self, threadDictionary, currentQueue, needToChangeCurrentQueue]() {
```
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSOperationQueue.mm]: clarity: Why's the queue drained as a "side effect of exiting"? This doesn't seem clearer than sequencing the operation start before the code inside this block.

File: Frameworks/Foundation/NSOperationQueue.mm [hunk 12]
```diff
@@ -1,443 +1,381 @@
...
-        *listPtr = NSAtomicListSteal(sourceListPtr);
-        // source lists are in LIFO order, but we want to execute operations in the order they were enqueued
-        // so we reverse the list before we do anything with it
-        NSAtomicListReverse(listPtr);
-        op = NSAtomicListPop(listPtr);
-    }
+// Private helper that sets _dispatchQueue based on the current quality of service
+- (void)_setDispatchQueueUsingQualityOfService {
+    std::lock_guard<std::recursive_mutex> lock(_dispatchQueueLock);
+    _dispatchQueue = dispatch_get_global_queue(_QOSClassForNSQualityOfService(self.qualityOfService), 0);
```
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSOperationQueue.mm]: nit: no need for the getter call for QOS here

File: Frameworks/Foundation/NSOperationQueue.mm [hunk 13]
```diff
@@ -1,443 +1,381 @@
...
+        _maxConcurrentOperationCount = NSOperationQueueDefaultMaxConcurrentOperationCount;
+        _qualityOfService = NSQualityOfServiceDefault;
 
-    while (!stop) {
-        [self _doMainWork];
-        pthread_mutex_lock(&priv->_threadRunningLock);
-        if (![self hasMoreWork]) {
-            stop = TRUE;
-            priv->_thread = nil;
+        if (dispatch_queue_t underlyingQueue = [self underlyingQueue]) {
```
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSOperationQueue.mm]: ! ! !

This wasn't allowed before (C++11); do we have CC on whether we can do this?

File: tests/unittests/Foundation/NSOperationTests.mm [hunk 14]
```diff
@@ -586,4 +690,628 @@ - (void)main {
...
+    ASSERT_NO_THROW([mainQueue setUnderlyingQueue:nil]);
+    ASSERT_EQ([mainQueue underlyingQueue], dispatch_get_main_queue());
+    ASSERT_NO_THROW([mainQueue setUnderlyingQueue:dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0)]);
+    ASSERT_EQ([mainQueue underlyingQueue], dispatch_get_main_queue());
+    ASSERT_NO_THROW([mainQueue setUnderlyingQueue:dispatch_get_main_queue()]);
+    ASSERT_EQ([mainQueue underlyingQueue], dispatch_get_main_queue());
+}
+
+TEST(NSOperation, CurrentQueue) {
+// TODO #: WinObjC's implementation of NSThread does not consider this context the main thread - this is a bug
```
Comment (ms-jihua) [inline tests/unittests/Foundation/NSOperationTests.mm]: #2242

File: Frameworks/Foundation/NSOperationQueue.mm [hunk 15]
```diff
@@ -1,443 +1,381 @@
...
+}
 
-        for (int i = 0; i < NSOperationQueuePriority_Count; i++) {
-            [priv->suspendedCondition lock];
-            while (priv->isSuspended) {
-                [priv->suspendedCondition wait];
+- (void)observeValueForKeyPath:(NSString*)keyPath ofObject:(id)object change:(NSDictionary*)change context:(void*)context {
+    if ([keyPath isEqualToString:@"isFinished"]) {
+        NSOperation* op = static_cast<NSOperation*>(object);
+        if (op.isFinished) {
```
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSOperationQueue.mm]: nit: if we request the 'new' value from the change, we can avoid the synchronized call back into operation to query it.

File: Frameworks/Foundation/NSOperationQueue.mm [hunk 16]
```diff
@@ -1,443 +1,381 @@
...
+            // Minor optimization:
+            // Because of constraints in addOperation:, it is safe to assume that there is exactly one instance of op in the array
+            // removeObject: keeps going after finding first instance of object, which is unnecessary work
+            // Use indexOfObject:op instead
+            @synchronized(_operations.get()) {
+                NSUInteger index = [_operations indexOfObject:op];
```
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSOperationQueue.mm]: Prefer `indexOfObjectIdenticalTo:`, as it will require far fewer `isEqual:` calls

File: Frameworks/Foundation/NSOperationQueue.mm [hunk 17]
```diff
@@ -1,443 +1,381 @@
...
+#import "NSOperationInternal.h"
+#import "Starboard.h"
 
-The above copyright notice and this permission notice shall be included in all copies or substantial portions of the
-Software.
+#import <atomic>
+#import <mutex>
+#import <queue>
+
+static const wchar_t* g_logTag = L"NSOperationQueue";
```
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSOperationQueue.mm]: I know this name makes more sense, but our convention everywhere else is the shouty `TAG`

File: Frameworks/Foundation/NSOperationQueue.mm [hunk 18]
```diff
@@ -1,443 +1,381 @@
...
+            // Clean up state from addOperation:
+            [op removeObserver:self forKeyPath:@"isFinished" context:nil];
+            [op removeObserver:self forKeyPath:@"isReady" context:nil];
         }
-    } while (didWork);
-
-    [innerPool release];
-
-    return self;
+    } else if ([keyPath isEqualToString:@"isReady"]) {
```
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSOperationQueue.mm]: Can `isReady` ever be transitioning to false? If so, we may have to handle that.

File: Frameworks/Foundation/NSOperationQueue.mm [hunk 19]
```diff
@@ -1,443 +1,381 @@
...
 /**
  @Status Interoperable
 */
-- (BOOL)hasMoreWork {
-    if (priv->curOperation != nil) {
-        return TRUE;
++ (NSOperationQueue*)currentQueue {
+    NSThread* currentThread = [NSThread currentThread];
+    if ([currentThread isMainThread]) {
+        return [[self class] mainQueue];
```
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSOperationQueue.mm]: While it won't break anything, using `[self class]` in a `+` method is ambiguous as to whether it should be a meta-metaclass, or just a metaclass.

Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSOperationQueue.mm]: (technically, it is well-defined, but I thought this was an instance method when i saw the `-class` call)

File: Frameworks/Foundation/NSOperationQueue.mm [hunk 20]
```diff
@@ -1,443 +1,381 @@
...
-    /*
-    //  Add any dependencies
-    id dependencies = [op dependencies];
-    int count = [dependencies count];
-    for ( int i = 0; i < count; i ++ ) {
-    id curDep = [dependencies objectAtIndex:i];
-    [self addOperation:curDep];
+- (void)addOperation:(NSOperation*)op {
+    if (op.isExecuting || op.isFinished) {
+        @throw [NSException exceptionWithName:NSInvalidArgumentException reason:@"operation is already or finished executing" userInfo:nil];
```
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSOperationQueue.mm]: We may want to have an exception formatter that prepends `-[ClassName selector:name:]` to our exceptions; i know we have a couple scattered around.

File: Frameworks/Foundation/NSOperationQueue.mm [hunk 21]
```diff
@@ -1,443 +1,381 @@
...
-    [priv->workAvailable signal];
+    [self willChangeValueForKey:@"operations"];
+    [self willChangeValueForKey:@"operationCount"];
 
-    pthread_mutex_lock(&priv->_threadRunningLock);
-    if (priv->_thread == nil) {
-        priv->_thread = [[NSThread alloc] initWithTarget:self selector:@selector(_workThread) object:nil];
-        [priv->_thread start];
-        [priv->_thread release];
+    @synchronized(_operations.get()) {
```
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSOperationQueue.mm]: Should we be guarding the will/did?

File: Frameworks/Foundation/NSOperationQueue.mm [hunk 22]
```diff
@@ -1,443 +1,381 @@
...
-*/
-- (void)addOperationWithBlock:(void (^)())block {
-    id op = [NSOperation new];
-    [op setCompletionBlock:block];
-    [self addOperation:op];
-    [op release];
+    [self didChangeValueForKey:@"operationCount"];
+    [self didChangeValueForKey:@"operations"];
+
+    [op addObserver:self forKeyPath:@"isFinished" options:0 context:nil];
```
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSOperationQueue.mm]: Can the operation change status between when we add it to the array and when we register for its notifications?

File: Frameworks/Foundation/NSOperationQueue.mm [hunk 23]
```diff
@@ -1,443 +1,381 @@
...
-- (id)operations {
-    id ret = [NSMutableArray array];
-
-    TraceVerbose(TAG, L"Should lock queue for this");
-    id cur = priv->curOperation;
-    if (cur != nil) {
-        [ret addObject:cur];
+- (NSArray<__kindof NSOperation*>*)operations {
+    @synchronized(_operations.get()) {
+        return [_operations copy];
```
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSOperationQueue.mm]: copy + autorelease; otherwise, this leaks

File: Frameworks/Foundation/NSOperationQueue.mm [hunk 24]
```diff
@@ -446,138 +384,112 @@ - (void)cancelAllOperations {
...
 - (void)waitUntilAllOperationsAreFinished {
-    BOOL isWorking;
-
-    [priv->workAvailable lock];
-    isWorking = [self hasMoreWork];
-
-    if (isWorking) {
-        [priv->allWorkDone wait];
-        isWorking = [self hasMoreWork];
+    while (NSOperation* lastOp = [_operations lastObject]) {
```
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSOperationQueue.mm]: What if another operation is added while we're waiting for them all to finish?

File: Frameworks/Foundation/NSOperationQueue.mm (hunk 12 above)
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSOperationQueue.mm]: (since it's under the same lock)

File: include/Foundation/NSOperationQueue.h [hunk 25]
```diff
@@ -19,25 +19,23 @@
...
 FOUNDATION_EXPORT_CLASS
 @interface NSOperationQueue : NSObject
 + (NSOperationQueue*)currentQueue;
 + (NSOperationQueue*)mainQueue;
 - (void)addOperation:(NSOperation*)operation;
-- (void)addOperations:(NSArray*)ops waitUntilFinished:(BOOL)wait;
+- (void)addOperations:(NSArray<NSOperation*>*)ops waitUntilFinished:(BOOL)wait;
 - (void)addOperationWithBlock:(void (^)(void))block;
-@property (readonly, copy) NSArray* operations;
+@property (readonly, copy) NSArray<__kindof NSOperation*>* operations;
```
Comment (DHowett-MSFT) [inline include/Foundation/NSOperationQueue.h]: we may have to add the `suspended` property

File: tests/Benchmark/NSOperationQueueBenchmarkTests.mm [hunk 26]
```diff
@@ -0,0 +1,87 @@
...
+        }
+    }
+}
+class AddOperation : public ::benchmark::BenchmarkCaseBase {
+    StrongId<NSOperationQueue> m_queue;
+
+public:
+    void PreRun() {
+        @autoreleasepool {
+            m_queue = [[NSOperationQueue new] autorelease];
```
Comment (DHowett-MSFT) [inline tests/Benchmark/NSOperationQueueBenchmarkTests.mm]: you could use .attach here and avoid the round trip

File: Frameworks/Foundation/NSOperationQueue.mm (hunk 1 above)
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSOperationQueue.mm]: You beat me to it, and the other issue ID questions. Deleting.

File: Frameworks/Foundation/NSOperationQueue.mm [hunk 27]
```diff
@@ -1,443 +1,381 @@
...
+        return;
+    }
 
-    NSObject* elt = [[node->elt retain] autorelease];
-    delete node;
-    return elt;
-}
+    {
+        std::lock_guard<std::recursive_mutex> lock(_concurrentOperationCountLock);
+        if ((self.isSuspended) || (![self _belowMaxConcurrentOperations])) {
```
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSOperationQueue.mm]: when we add the property for suspended, this should become `self.suspended`; the getter form is for `[self isSuspended]` use

File: Frameworks/Foundation/NSOperationQueue.mm (hunk 17 above)
Comment (ms-jihua) [inline Frameworks/Foundation/NSOperationQueue.mm]: define 'everywhere else', we've also had non-zero g_logTags...

File: Frameworks/Foundation/NSOperationQueue.mm (hunk 4 above)
Comment (ms-jihua) [inline Frameworks/Foundation/NSOperationQueue.mm]: oops somehow completely missed this

File: Frameworks/Foundation/NSOperationQueue.mm (hunk 8 above)
Comment (ms-jihua) [inline Frameworks/Foundation/NSOperationQueue.mm]: i forgot thread_local existed derp

**Comment by DHowett-MSFT** [comment]
FWIW we have 2 `g_logTag`s, both in CoreText; we have 182 `TAG`s :)

File: Frameworks/Foundation/NSOperationQueue.mm (hunk 11 above)
Comment (ms-jihua) [inline Frameworks/Foundation/NSOperationQueue.mm]: don't we generally prefer wil::ScopeExit for safer cleanups if the inbetween function is relatively unknown/risky?

File: Frameworks/Foundation/NSOperationQueue.mm (hunk 12 above)
Comment (ms-jihua) [inline Frameworks/Foundation/NSOperationQueue.mm]: subclasses could override though?

File: Frameworks/Foundation/NSOperationQueue.mm (hunk 13 above)
Comment (ms-jihua) [inline Frameworks/Foundation/NSOperationQueue.mm]: we do it all the time as 'if (self = [super init])' though

File: Frameworks/Foundation/NSOperationQueue.mm (hunk 11 above)
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSOperationQueue.mm]: Absolutely. It feels like this is a little bigger than "cleanup" though, it'll even go and reschedule more operations.

Aside: Should we pay any heed to trying to run operations back-to-back without spinning up another async dispatch?

File: Frameworks/Foundation/NSOperationQueue.mm (hunk 13 above)
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSOperationQueue.mm]: We don't use the type-declaring version, though.

File: Frameworks/Foundation/NSOperationQueue.mm (hunk 22 above)
Comment (ms-jihua) [inline Frameworks/Foundation/NSOperationQueue.mm]: oh hm, i didn't think about this angle. i'll hold the lock on the operation then.

File: Frameworks/Foundation/NSOperationQueue.mm (hunk 24 above)
Comment (ms-jihua) [inline Frameworks/Foundation/NSOperationQueue.mm]: won't lastOp be set to a new value every loop?

File: include/Foundation/NSOperationQueue.h (hunk 25 above)
Comment (ms-jihua) [inline include/Foundation/NSOperationQueue.h]: ? it's there, it's just hidden under the github cutoff where it doesn't like to show you the whole file

File: tests/Benchmark/NSOperationQueueBenchmarkTests.mm (hunk 26 above)
Comment (ms-jihua) [inline tests/Benchmark/NSOperationQueueBenchmarkTests.mm]: derp derp

File: include/Foundation/NSOperationQueue.h (hunk 25 above)
Comment (DHowett-MSFT) [inline include/Foundation/NSOperationQueue.h]: Oh jeez, I was looking at the wrong file locally T_T

**Comment by ms-jihua** [comment]
@DHowett-MSFT I am defeated

File: Frameworks/Foundation/NSOperationQueue.mm (hunk 5 above)
Comment (ms-jihua) [inline Frameworks/Foundation/NSOperationQueue.mm]: how come? this more has to do with synchronizing these members' getters/setters

File: Frameworks/Foundation/NSOperationQueue.mm (hunk 6 above)
Comment (ms-jihua) [inline Frameworks/Foundation/NSOperationQueue.mm]: Not inherently indexed, but the ordering needs to be consistent. Ordered set would be good, I kind of neglected other possibilities just because the operations property is an array. However, we don't actually have NSMutableOrderedSet yet. I'll keep an eye on #2225, and change this to use it once it's in.

File: Frameworks/Foundation/NSOperationQueue.mm (hunk 11 above)
Comment (ms-jihua) [inline Frameworks/Foundation/NSOperationQueue.mm]: You have a good point. I moved this to be async, and to be triggered in observing isFinished instead.

File: include/Foundation/NSOperation.h [hunk 28]
```diff
@@ -64,7 +55,7 @@ FOUNDATION_EXPORT_CLASS
 - (void)addDependency:(NSOperation*)operation;
 - (void)removeDependency:(NSOperation*)operation;
 @property (readonly, copy) NSArray* dependencies;
-@property NSQualityOfService qualityOfService STUB_PROPERTY;
+@property NSQualityOfService qualityOfService;
 @property double threadPriority STUB_PROPERTY;
```
Comment (rajsesh-msft) [inline include/Foundation/NSOperation.h]: >threadPriority [](start = 17, length = 14)

can we add support for this as well?

File: Frameworks/Foundation/NSOperationQueue.mm (hunk 15 above)
Comment (ms-jihua) [inline Frameworks/Foundation/NSOperationQueue.mm]: it seems easier than doing the dictionary lookup, cast to nsnumber, and get boolvalue, though

File: include/Foundation/NSOperation.h (hunk 28 above)
Comment (ms-jihua) [inline include/Foundation/NSOperation.h]: yeah - i seem to have lost a commit somewhere

File: Frameworks/Foundation/NSOperationQueue.mm (hunk 21 above)
Comment (ms-jihua) [inline Frameworks/Foundation/NSOperationQueue.mm]: I don't think it really matters. KVO has an expectation that the timing might be a little off, right?

File: Frameworks/Foundation/NSOperationInternal.h [hunk 29]
```diff
@@ -18,4 +18,5 @@
 
 @interface NSOperation ()
 @property (nonatomic, assign, getter=_completionQueue, setter=_setCompletionQueue:) dispatch_queue_t _completionQueue;
+- (BOOL)_acquirePermissionToAddToQueue;
```
Comment (rajsesh-msft) [inline Frameworks/Foundation/NSOperationInternal.h]: >_acquirePermissionToAddToQueue [](start = 8, length = 30)

something about this name doesn't fit right with me.  We are not requesting any permissions here, perhaps just make this an atomic property InQueue and set it directly.

File: Frameworks/Foundation/NSOperationQueue.mm [hunk 30]
```diff
@@ -1,443 +1,381 @@
...
+            return QOS_CLASS_USER_INTERACTIVE;
+        case NSQualityOfServiceUserInitiated:
+            return QOS_CLASS_USER_INITIATED;
+        case NSQualityOfServiceUtility:
+            return QOS_CLASS_UTILITY;
+        case NSQualityOfServiceBackground:
+            // currently generates a warning:
+            // 'QOS_CLASS_BACKGROUND' is deprecated: QOS_CLASS_BACKGROUND is the same as DISPATCH_QUEUE_PRIORITY_LOW on WinObjC
+            // should go away once libdispatch is updated
+            return QOS_CLASS_BACKGROUND;
```
Comment (rajsesh-msft) [inline Frameworks/Foundation/NSOperationQueue.mm]: >QOS_CLASS_BACKGROUND [](start = 19, length = 20)

Could we not introduce a "deprecated" warning in our new code if avoidable.

File: include/Foundation/NSOperation.h (hunk 28 above)
Comment (ms-jihua) [inline include/Foundation/NSOperation.h]: no wait i was thinking of another thing, i actually just missed this, sorry!

File: Frameworks/Foundation/NSOperationQueue.mm (hunk 30 above)
Comment (ms-jihua) [inline Frameworks/Foundation/NSOperationQueue.mm]: I think I'd prefer to disable the warning in this instance, since it's one that'll go away once we Do The Right Thing and update libdispatch.

File: Frameworks/Foundation/NSOperationInternal.h (hunk 29 above)
Comment (ms-jihua) [inline Frameworks/Foundation/NSOperationInternal.h]: i like having it as an atomic operation so that it's harder to break contract, i'll try to think of a better name...

Comment (ms-jihua) [inline Frameworks/Foundation/NSOperationInternal.h]: going with _markInQueue for now...

File: Frameworks/Foundation/NSOperationQueue.mm (hunk 11 above)
Comment (ms-jihua) [inline Frameworks/Foundation/NSOperationQueue.mm]: no wait i didn't think this all the way through.

- isFinished is set at the end of [operation start]. if we schedule more operations when we observe isFinished, we end up doing so before we decrement _currentConcurrentOperationCount, causing _popAndStart to do the wrong thing.
- we can move the decrement to the isFinished observation, but i dislike this because 1) the increment and decrement ideally should be in the same function 2) an operation can finish through means besides _startOperation (ie: if a user decides to start it manually for whatever reason)
- as it currently is, we're basically checking if new operations need to be started when an old operation has finished, using the same async context. i think that this makes intuitive sense, so i'm going to leave it as is for now. (it might look less scary once you see the thread_local version also)

**Comment by ms-jihua** [comment]
I just realized I pushed the branch to the main repo instead of my own fork. I'll keep the PR open for now and delete the branch when I'm done.

File: Frameworks/Foundation/NSOperationQueue.mm [hunk 31]
```diff
@@ -38,27 +38,52 @@ static inline long _QOSClassForNSQualityOfService(NSQualityOfService quality) {
...
+
+// STL compare for NSOperation*, sorting by queuePriority, putting the greatest priority first
+struct _NSOperation_ComparePrioritySTL {
+    bool operator()(NSOperation* lhs, NSOperation* rhs) {
+        return lhs.queuePriority > rhs.queuePriority;
+    }
+};
+
+// Used for [NSOperationQueue currentQueue]
+thread_local static StrongId<NSOperationQueue*> tls_currentQueue;
```
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSOperationQueue.mm]: So this is sorta silly; ehren ran into an issue with destructors on file-level thread_locals; they never get called and then leak.

File: Frameworks/Foundation/NSOperationQueue.mm [hunk 32]
```diff
@@ -116,83 +133,90 @@ @implementation NSOperationQueue {
...
-
-        // If so, cache the previous currentQueue stored in the threadDictionary, and store the new currentQueue
-        if (needToChangeCurrentQueue) {
-            [threadDictionary setObject:self forKey:_NSOperationQueueCurrentQueueKey];
-        }
+        std::lock_guard<std::recursive_mutex> lock(_dispatchQueueLock);
+        dispatch_async(_dispatchQueue, ^{
+            // Check if currentQueue needs to be changed
+            StrongId<NSOperationQueue> currentQueue = tls_currentQueue;
+            bool needToChangeCurrentQueue = (![[NSThread currentThread] isMainThread]) && (![self isEqual:tls_currentQueue.get()]);
```
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSOperationQueue.mm]: `isEqual` is likely overkill here; `==` will do

File: Frameworks/Foundation/NSOperationQueue.mm [hunk 33]
```diff
@@ -38,27 +38,52 @@ static inline long _QOSClassForNSQualityOfService(NSQualityOfService quality) {
...
+    bool operator()(NSOperation* lhs, NSOperation* rhs) {
+        return lhs.queuePriority > rhs.queuePriority;
+    }
+};
+
+// Used for [NSOperationQueue currentQueue]
+thread_local static StrongId<NSOperationQueue*> tls_currentQueue;
+
+// Used for key-value observing on held operations - faster than comparing keypaths
+static void* _NSOperationQueue_IsFinishedContext = &_NSOperationQueue_IsFinishedContext;
```
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSOperationQueue.mm]: nit: you can use use `static char _xyz` and then `&_xyz` later; no need for initialization (or emitting a binary relocation that requires updating a pointer :smile:)

Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSOperationQueue.mm]: (doing it the aforementioned way is common in objc associated object scenarios; they use `key`s which are just `void*`)

File: Frameworks/Foundation/NSOperationQueue.mm [hunk 34]
```diff
@@ -246,32 +270,31 @@ - (void)dealloc {
...
-                [self willChangeValueForKey:@"operationCount"];
-                [_operations removeObjectAtIndex:index];
-                [self didChangeValueForKey:@"operationCount"];
-                [self didChangeValueForKey:@"operations"];
+    NSOperation* op = static_cast<NSOperation*>(object);
+    if ((context == _NSOperationQueue_IsFinishedContext) && (op.finished)) {
+        // Minor optimization:
+        // Because of constraints in addOperation:, it is safe to assume that there is exactly one instance of op in the array
+        // removeObject: keeps going after finding first instance of object, which is unnecessary work
+        // Use indexOfObject:op instead
```
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSOperationQueue.mm]: nit: comment out of date

File: Frameworks/Foundation/NSOperationQueue.mm [hunk 35]
```diff
@@ -281,64 +304,70 @@ - (void)observeValueForKeyPath:(NSString*)keyPath ofObject:(id)object change:(NS
...
+        }
 
-    [self didChangeValueForKey:@"operationCount"];
-    [self didChangeValueForKey:@"operations"];
+        [self didChangeValueForKey:@"operationCount"];
+        [self didChangeValueForKey:@"operations"];
 
-    [op addObserver:self forKeyPath:@"isFinished" options:0 context:nil];
-    [op addObserver:self forKeyPath:@"isReady" options:0 context:nil];
+        [op addObserver:self forKeyPath:@"isFinished" options:NSKeyValueObservingOptionNew context:_NSOperationQueue_IsFinishedContext];
```
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSOperationQueue.mm]: since you didn't in the end decide to use the change dictionary, you'll save a few cycles killing the **new** option here.

File: tests/unittests/Foundation/NSOperationTests.mm [hunk 36]
```diff
@@ -88,14 +88,15 @@ - (instancetype)initWithBlock:(void (^)())block;
 @implementation BlockThread
 - (instancetype)initWithBlock:(void (^)())block {
     if (self = [super init]) {
-        self->_block = block;
-        self->_finishCondition = [[_NSBooleanCondition new] autorelease];
+        self.block = block;
```
Comment (DHowett-MSFT) [inline tests/unittests/Foundation/NSOperationTests.mm]: huh, is block observable? 🌟 never knew!

Comment (DHowett-MSFT) [inline tests/unittests/Foundation/NSOperationTests.mm]: though, wait; we generally avoid using setters in init, because they can be overridden by subclasses who are not yet initialized.

Comment (DHowett-MSFT) [inline tests/unittests/Foundation/NSOperationTests.mm]: even though that doesn't apply here

**Comment by DHowett-MSFT** [comment]
strangely, it marked some of my new comments as outdated.

File: Frameworks/Foundation/NSOperationQueue.mm (hunk 31 above)
Comment (ms-jihua) [inline Frameworks/Foundation/NSOperationQueue.mm]: oh yeah i remember that...

File: Frameworks/Foundation/NSOperationQueue.mm (hunk 35 above)
Comment (ms-jihua) [inline Frameworks/Foundation/NSOperationQueue.mm]: oops oops
i should version control a little more aggressively so i avoid these sorts of mistakes

File: tests/unittests/Foundation/NSOperationTests.mm (hunk 36 above)
Comment (ms-jihua) [inline tests/unittests/Foundation/NSOperationTests.mm]: er, not sure what you're getting excited about here, actually. if a block were observable it'd be on the block member changing, not the block finishing.

File: Frameworks/Foundation/NSOperationQueue.mm [hunk 37]
```diff
@@ -1,443 +1,415 @@
...
+    } else if (pri1 < pri2) {
+        return NSOrderedDescending;
+    }
+    return NSOrderedSame;
+}
+
+// STL compare for NSOperation*, sorting by queuePriority, putting the greatest priority first
+struct _NSOperation_ComparePrioritySTL {
+    bool operator()(NSOperation* lhs, NSOperation* rhs) {
+        return lhs.queuePriority > rhs.queuePriority;
```
Comment (aballway) [inline Frameworks/Foundation/NSOperationQueue.mm]: This would put the lowest priority on top of the pqueue

File: Frameworks/Foundation/NSOperationQueue.mm [hunk 38]
```diff
@@ -1,443 +1,415 @@
...
+
+            ++_currentConcurrentOperationCount;
+        } // _concurrentOperationCountLock scope
+
+        std::lock_guard<std::recursive_mutex> lock(_dispatchQueueLock);
+        dispatch_async(_dispatchQueue, ^{
+            // Check if currentQueue needs to be changed
+            StrongId<NSOperationQueue*>& currentQueue = _getCurrentQueue();
+            StrongId<NSOperationQueue*> prevCurrentQueue(currentQueue.get());
+            bool needToChangeCurrentQueue = (![[NSThread currentThread] isMainThread]) && (!(self == currentQueue.get()));
```
Comment (aballway) [inline Frameworks/Foundation/NSOperationQueue.mm]: nit: prefer !(A || B) to (!A && !B)

File: tests/unittests/Foundation/TestUtils.mm [hunk 39]
```diff
@@ -52,4 +52,4 @@ void deleteFile(NSString* name) {
     if ([[NSFileManager defaultManager] fileExistsAtPath:fullPath]) {
         [[NSFileManager defaultManager] removeItemAtPath:fullPath error:nil];
     }
-};
+};
```
Comment (aballway) [inline tests/unittests/Foundation/TestUtils.mm]: nit: revert this file

File: Frameworks/Foundation/NSOperationQueue.mm (hunk 37 above)
Comment (ms-jihua) [inline Frameworks/Foundation/NSOperationQueue.mm]: oops, i didn't realize priority queue had opposite sorting from objective-c ;;;;

File: Frameworks/Foundation/NSOperation.mm [hunk 40]
```diff
@@ -349,4 +355,37 @@ - (void)dealloc {
...
+    } else if (queuePriority > NSOperationQueuePriorityVeryLow) {
+        _queuePriority = NSOperationQueuePriorityLow;
+
+    } else {
+        _queuePriority = NSOperationQueuePriorityVeryLow;
+    }
+}
+
+- (BOOL)_markInQueue {
+    return !_inQueue.fetch_or(YES); // only returns true for the first caller
```
Comment (DHowett-MSFT) [inline Frameworks/Foundation/NSOperation.mm]: nit: since it's truly a `bool`, you'll want `true`; though we're using an `atomic_bool` to back a `BOOL` property o_O

Comment (ms-jihua) [inline Frameworks/Foundation/NSOperation.mm]: it's an atomic<BOOL>

**Comment by ms-jihua** [comment]
Ping @rajsesh-msft - I want to make sure you have no additional issues with this before it merges.
