### PR TITLE
Fix CGPathEqualToPath Implementation

### LINKED ISSUE #1777: CGPathEqualToPath Implementation Incorrect
CGPathEqualToPath should iterate over each path using CGPathApply and check that each segment are the same.

### PR DESCRIPTION
**Pull request by MSFTFox**
Use CGPathApply to check the equality of two paths.

Fix #1777

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/winobjc/1813)

### CODE REVIEW

File: Frameworks/CoreGraphics/CGPath.mm [hunk 1]
```diff
@@ -283,10 +283,64 @@ CFTypeID CGPathGetTypeID() {
     return __CGPath::GetTypeID();
 }
 
+// A helper for determining the number of points per path element type
+static inline int CGPathGetExpectedPointCountForType(CGPathElementType type) {
```
Comment (DHowett-MSFT) [inline Frameworks/CoreGraphics/CGPath.mm]: Nit: name this with two underscores, and perhaps have it return a size_t as it can never be negative and we are using it for pointer offsets

File: Frameworks/CoreGraphics/CGPath.mm [hunk 2]
```diff
@@ -283,10 +283,64 @@ CFTypeID CGPathGetTypeID() {
...
+    return type == kCGPathElementMoveToPoint || type == kCGPathElementAddLineToPoint ?
+               1 :
+               type == kCGPathElementAddQuadCurveToPoint ? 2 : type == kCGPathElementAddCurveToPoint ? 3 : 0;
+}
+
+// Create a mimic of CGPathElement that holds the points in a vector with a convenient copy constructor.
+struct _CGPathElementVector {
+    CGPathElementType _type;
+    std::vector<CGPoint> _points;
+    _CGPathElementVector(const CGPathElement el)
```
Comment (DHowett-MSFT) [inline Frameworks/CoreGraphics/CGPath.mm]: You'll want `const CGPathElement&`, otherwise the compiler will emit a copy of CGPathElement that will be immediately destroyed after you copy it again.

File: Frameworks/CoreGraphics/CGPath.mm [hunk 3]
```diff
@@ -283,10 +283,64 @@ CFTypeID CGPathGetTypeID() {
...
+        : _type(el.type), _points(el.points, el.points + CGPathGetExpectedPointCountForType(el.type)) {
+    }
+};
+
+// A struct to pass to the equality matching CGPathApply since only a single void* may be passed.
+struct CGPathElementMatch {
```
Comment (DHowett-MSFT) [inline Frameworks/CoreGraphics/CGPath.mm]: Naming! Or, put this in an anonymous namespace. Or both.

File: Frameworks/CoreGraphics/CGPath.mm [hunk 4]
```diff
@@ -283,10 +283,64 @@ CFTypeID CGPathGetTypeID() {
...
+    std::vector<_CGPathElementVector> elements;
+    bool equal = true;
+    int positionToMatch = 0;
+};
+
+// A function to pass to CGPathApply to determine whether two paths are equal.
+static void _CGPathApplyCheckEquality(void* pathElements, const CGPathElement* element1) {
```
Comment (DHowett-MSFT) [inline Frameworks/CoreGraphics/CGPath.mm]: Fully internal things get two underscores

File: Frameworks/CoreGraphics/CGPath.mm [hunk 5]
```diff
@@ -283,10 +283,64 @@ CFTypeID CGPathGetTypeID() {
...
+    if (!((CGPathElementMatch*)pathElements)->equal) {
```
Comment (DHowett-MSFT) [inline Frameworks/CoreGraphics/CGPath.mm]: Nit: explain short circuiting logic

File: Frameworks/CoreGraphics/CGPath.mm [hunk 6]
```diff
@@ -283,10 +283,64 @@ CFTypeID CGPathGetTypeID() {
...
+        return;
+    }
+    int i = ((CGPathElementMatch*)pathElements)->positionToMatch;
+    _CGPathElementVector element2 = ((CGPathElementMatch*)pathElements)->elements[i];
+    if (element2._type != element1->type) {
+        ((CGPathElementMatch*)pathElements)->equal = false;
+    } else {
+        for (int i = 0; i < CGPathGetExpectedPointCountForType(element1->type); i++) {
```
Comment (DHowett-MSFT) [inline Frameworks/CoreGraphics/CGPath.mm]: Use the size() of the existing points vector instead of calculating this more than once

File: Frameworks/CoreGraphics/CGPath.mm [hunk 7]
```diff
@@ -283,10 +283,64 @@ CFTypeID CGPathGetTypeID() {
...
+            if (element1->points[i] != element2._points[i]) {
+                ((CGPathElementMatch*)pathElements)->equal = false;
```
Comment (DHowett-MSFT) [inline Frameworks/CoreGraphics/CGPath.mm]: You can break after this

File: Frameworks/CoreGraphics/CGPath.mm [hunk 8]
```diff
@@ -283,10 +283,64 @@ CFTypeID CGPathGetTypeID() {
...
+            }
+        }
+    }
+
+    ((CGPathElementMatch*)pathElements)->positionToMatch++;
```
Comment (DHowett-MSFT) [inline Frameworks/CoreGraphics/CGPath.mm]: To avoid the duplicate casting, do it once at the top of the function

File: Frameworks/CoreGraphics/CGPath.mm [hunk 9]
```diff
@@ -283,10 +283,64 @@ CFTypeID CGPathGetTypeID() {
...
+    _CGPathElementVector newElement = _CGPathElementVector(*element);
+    ((std::vector<_CGPathElementVector>*)pathElements)->emplace_back(newElement);
+}
+
 static Boolean __CGPathEqual(CFTypeRef cf1, CFTypeRef cf2) {
     if (!cf1 && !cf2) {
         return true;
     }
+
+    if (cf1 == cf2) {
```
Comment (DHowett-MSFT) [inline Frameworks/CoreGraphics/CGPath.mm]: The above check is redundant with this one. Remove the above one in favour of this one

File: tests/unittests/CoreGraphics/CGPathTests.mm [hunk 10]
```diff
@@ -871,7 +871,31 @@ static bool testSymmetricEquivalence(CGPathRef path1, CGPathRef path2) {
...
+    CGPathMoveToPoint(thepath, NULL, xstart + .5 * width, ystart + .5 * height);
+    CGPathAddArc(thepath, NULL, xstart + .625 * width, ystart + .5 * height, .25 * height, M_PI, 0, true);
+    CGPathMoveToPoint(thepath, NULL, xstart + .4375 * width, ystart + .5 * height);
+    CGPathAddArc(thepath, NULL, xstart + .375 * width, ystart + .5 * height, .125 * height, 0, M_PI / 2, true);
+    CGPathAddArc(thepath, NULL, xstart + .375 * width, ystart + .5 * height, .125 * height, M_PI / 2, 0, true);
+    CGPathMoveToPoint(thepath, NULL, xstart + .6875 * width, ystart + .5 * height);
+    CGPathAddArc(thepath, NULL, xstart + .625 * width, ystart + .5 * height, .125 * height, 0, M_PI / 2, true);
+    CGPathAddArc(thepath, NULL, xstart + .625 * width, ystart + .5 * height, .125 * height, M_PI / 2, 0, true);
+
+    EXPECT_TRUE(testSymmetricEquivalence(thepath, CGPathCreateCopy(thepath)));
```
Comment (DHowett-MSFT) [inline tests/unittests/CoreGraphics/CGPathTests.mm]: This copy leaks

Comment (DHowett-MSFT) [inline tests/unittests/CoreGraphics/CGPathTests.mm]: I prefer testSymmetricEquivalence to be a macro. That would allow GTest to log the real test source line that caused the failing comparison.

File: Frameworks/CoreGraphics/CGPath.mm [hunk 11]
```diff
@@ -283,10 +283,64 @@ CFTypeID CGPathGetTypeID() {
     return __CGPath::GetTypeID();
 }
 
+// A helper for determining the number of points per path element type
+static inline int CGPathGetExpectedPointCountForType(CGPathElementType type) {
+    return type == kCGPathElementMoveToPoint || type == kCGPathElementAddLineToPoint ?
```
Comment (rajsesh-msft) [inline Frameworks/CoreGraphics/CGPath.mm]: nit: please change this to switch/case to make it more readable.

File: Frameworks/CoreGraphics/CGPath.mm (hunk 1 above)
Comment (rajsesh-msft) [inline Frameworks/CoreGraphics/CGPath.mm]: _CGPathGetExpectedPointCountForType?

File: Frameworks/CoreGraphics/CGPath.mm (hunk 5 above)
Comment (rajsesh-msft) [inline Frameworks/CoreGraphics/CGPath.mm]: recommend stashing this in a local variable for readability. (CGPathElementMatch*)pathElements

File: Frameworks/CoreGraphics/CGPath.mm (hunk 1 above)
Comment (aballway) [inline Frameworks/CoreGraphics/CGPath.mm]: nit: in that case ptrdiff_t? It's signed but is clearer about what it's used for

File: Frameworks/CoreGraphics/CGPath.mm (hunk 11 above)
Comment (aballway) [inline Frameworks/CoreGraphics/CGPath.mm]: nit: just do a switch

File: Frameworks/CoreGraphics/CGPath.mm [hunk 12]
```diff
@@ -283,10 +283,64 @@ CFTypeID CGPathGetTypeID() {
...
+               1 :
+               type == kCGPathElementAddQuadCurveToPoint ? 2 : type == kCGPathElementAddCurveToPoint ? 3 : 0;
+}
+
+// Create a mimic of CGPathElement that holds the points in a vector with a convenient copy constructor.
+struct _CGPathElementVector {
+    CGPathElementType _type;
```
Comment (aballway) [inline Frameworks/CoreGraphics/CGPath.mm]: nit: don't use the objc class naming convention, just use plain type, points. etc.  Or maybe c++ class style m_type, ...

File: Frameworks/CoreGraphics/CGPath.mm [hunk 13]
```diff
@@ -283,10 +283,64 @@ CFTypeID CGPathGetTypeID() {
...
+        }
+    }
+
+    ((CGPathElementMatch*)pathElements)->positionToMatch++;
+}
+
+// A function to pass to CGPathApply to retrieve the individual path elements to check equality against.
+static void _CGPathApplyGetElements(void* pathElements, const CGPathElement* element) {
+    _CGPathElementVector newElement = _CGPathElementVector(*element);
+    ((std::vector<_CGPathElementVector>*)pathElements)->emplace_back(newElement);
```
Comment (aballway) [inline Frameworks/CoreGraphics/CGPath.mm]: nit: just emplace the construction

File: tests/unittests/CoreGraphics/CGPathTests.mm (hunk 10 above)
Comment (aballway) [inline tests/unittests/CoreGraphics/CGPathTests.mm]: thepath leaks as well

Comment (MSFTFox) [inline tests/unittests/CoreGraphics/CGPathTests.mm]: It does log the line since testSymmetricEquivalence returns the result. It doesn't grab which direction the equivalence failed on but this was preferable to having two macros for fail vs succeed or having to pass an extra bool to state whether it should fail or succeed. At least in my opinion.

---
In reply to: [97699788](https://github.com/Microsoft/WinObjC/pull/1813#discussion_r97699788) [](ancestors = 97699788)

File: Frameworks/CoreGraphics/CGPath.mm [hunk 14]
```diff
@@ -282,11 +282,73 @@ HRESULT _CGPathGetGeometry(CGPathRef path, ID2D1Geometry** pGeometry) {
...
+static inline size_t __CGPathGetExpectedPointCountForType(CGPathElementType type) {
+    switch (type) {
+        case kCGPathElementMoveToPoint:
+        case kCGPathElementAddLineToPoint:
+            return 1;
+        case kCGPathElementAddQuadCurveToPoint:
+            return 2;
+        case kCGPathElementAddCurveToPoint:
+            return 3;
+        case kCGPathElementCloseSubpath:
```
Comment (aballway) [inline Frameworks/CoreGraphics/CGPath.mm]: nit: also default here

File: Frameworks/CoreGraphics/CGPath.mm [hunk 15]
```diff
@@ -282,11 +282,73 @@ HRESULT _CGPathGetGeometry(CGPathRef path, ID2D1Geometry** pGeometry) {
...
+            }
+        }
+    }
+
+    elements->m_positionToMatch++;
+}
+
+// A function to pass to CGPathApply to retrieve the individual path elements to check equality against.
+static void _CGPathApplyGetElements(void* pathElements, const CGPathElement* element) {
+    ((std::vector<__CGPathElementVector>*)pathElements)->emplace_back(__CGPathElementVector(*element));
```
Comment (DHowett-MSFT) [inline Frameworks/CoreGraphics/CGPath.mm]: Still no; just use `*element` in the emplace_back.

Comment (DHowett-MSFT) [inline Frameworks/CoreGraphics/CGPath.mm]: (A naive compiler could emit a copy here.)

File: Frameworks/CoreGraphics/CGPath.mm [hunk 16]
```diff
@@ -296,20 +358,22 @@ static Boolean __CGPathEqual(CFTypeRef cf1, CFTypeRef cf2) {
...
+    RETURN_FALSE_IF_FAILED(path1->GetPathGeometry()->GetSegmentCount(&count1));
+    RETURN_FALSE_IF_FAILED(path2->GetPathGeometry()->GetSegmentCount(&count2));
+    if (count1 != count2) {
+        return false;
     }
 
-    return false;
+    std::vector<__CGPathElementVector> path1Elements;
+    CGPathApply(path1, &path1Elements, _CGPathApplyGetElements);
+    struct __CGPathElementMatch match;
```
Comment (DHowett-MSFT) [inline Frameworks/CoreGraphics/CGPath.mm]: nit: drop `struct `; that's a C thing.

File: tests/unittests/CoreGraphics/CGPathTests.mm [hunk 17]
```diff
@@ -871,7 +871,35 @@ static bool testSymmetricEquivalence(CGPathRef path1, CGPathRef path2) {
...
+    CGPathAddArc(thePath, NULL, xstart + .375 * width, ystart + .5 * height, .125 * height, 0, M_PI / 2, true);
+    CGPathAddArc(thePath, NULL, xstart + .375 * width, ystart + .5 * height, .125 * height, M_PI / 2, 0, true);
+    CGPathMoveToPoint(thePath, NULL, xstart + .6875 * width, ystart + .5 * height);
+    CGPathAddArc(thePath, NULL, xstart + .625 * width, ystart + .5 * height, .125 * height, 0, M_PI / 2, true);
+    CGPathAddArc(thePath, NULL, xstart + .625 * width, ystart + .5 * height, .125 * height, M_PI / 2, 0, true);
+
+    CGMutablePathRef thePathCopy = CGPathCreateCopy(thePath);
+    EXPECT_TRUE(testSymmetricEquivalence(thePath, CGPathCreateCopy(thePath)));
+
+    CGPathRelease(thePath);
```
Comment (DHowett-MSFT) [inline tests/unittests/CoreGraphics/CGPathTests.mm]: nit: could use AutoCF here, but w/e

File: tests/unittests/CoreGraphics/CGPathTests.mm [hunk 18]
```diff
@@ -871,7 +871,35 @@ static bool testSymmetricEquivalence(CGPathRef path1, CGPathRef path2) {
...
+    CGPathAddArc(thePath, NULL, xstart + .625 * width, ystart + .5 * height, .25 * height, M_PI, 0, true);
+    CGPathMoveToPoint(thePath, NULL, xstart + .4375 * width, ystart + .5 * height);
+    CGPathAddArc(thePath, NULL, xstart + .375 * width, ystart + .5 * height, .125 * height, 0, M_PI / 2, true);
+    CGPathAddArc(thePath, NULL, xstart + .375 * width, ystart + .5 * height, .125 * height, M_PI / 2, 0, true);
+    CGPathMoveToPoint(thePath, NULL, xstart + .6875 * width, ystart + .5 * height);
+    CGPathAddArc(thePath, NULL, xstart + .625 * width, ystart + .5 * height, .125 * height, 0, M_PI / 2, true);
+    CGPathAddArc(thePath, NULL, xstart + .625 * width, ystart + .5 * height, .125 * height, M_PI / 2, 0, true);
+
+    CGMutablePathRef thePathCopy = CGPathCreateCopy(thePath);
+    EXPECT_TRUE(testSymmetricEquivalence(thePath, CGPathCreateCopy(thePath)));
```
Comment (DHowett-MSFT) [inline tests/unittests/CoreGraphics/CGPathTests.mm]: !!!!!!!


_what_

Comment (MSFTFox) [inline tests/unittests/CoreGraphics/CGPathTests.mm]: Woops, reasons to not get distracted by email pop ups.

---
In reply to: [97888196](https://github.com/Microsoft/WinObjC/pull/1813#discussion_r97888196) [](ancestors = 97888196)

Comment (DHowett-MSFT) [inline tests/unittests/CoreGraphics/CGPathTests.mm]: Can confirm, e-mail popup distracted me into looking at this.

File: Frameworks/CoreGraphics/CGPath.mm (hunk 5 above)
Comment (MSFTFox) [inline Frameworks/CoreGraphics/CGPath.mm]: I'm not sure what you mean here, could you elaborate?

---
In reply to: [97700178](https://github.com/Microsoft/WinObjC/pull/1813#discussion_r97700178) [](ancestors = 97700178)

File: Frameworks/CoreGraphics/CGPath.mm (hunk 1 above)
Comment (MSFTFox) [inline Frameworks/CoreGraphics/CGPath.mm]: I'd prefer if it's unsigned. I don't think the ptrdiff_t would be any more clear.

---
In reply to: [97700376](https://github.com/Microsoft/WinObjC/pull/1813#discussion_r97700376) [](ancestors = 97700376)

File: Frameworks/CoreGraphics/CGPath.mm (hunk 5 above)
Comment (DHowett-MSFT) [inline Frameworks/CoreGraphics/CGPath.mm]: ..? you already did this, you're commenting on a comment that you resolved already.

---
In reply to: [97907600](https://github.com/Microsoft/WinObjC/pull/1813#discussion_r97907600) [](ancestors = 97907600,97700178)

Comment (MSFTFox) [inline Frameworks/CoreGraphics/CGPath.mm]: I misunderstood that. My bad.

---
In reply to: [97907976](https://github.com/Microsoft/WinObjC/pull/1813#discussion_r97907976) [](ancestors = 97907976,97907600,97700178)
