### PR TITLE
Switch our D2D factory to be multithreaded.

### LINKED ISSUE #1895: Crash in CGContext::PopEndDraw
Some D2D deferred render target is null deep inside Direct2D.

```
 	[Inline Frame] d2d1.dll!* C++
 	CoreGraphics.dll!__CGContext::PopEndDraw() Line 399	Objective-C++
 	CoreGraphics.dll!??R<lambda_7>@?DrawImage@__CGContext@@QAEJPAUID2D1Image@@@Z@QBE?A?<auto>@@XZ() Line 2242	Objective-C++
 	CoreGraphics.dll!Z::ScopeExitFn<,__CGContext::awImage,unsigned char * const,long,ID2D1Image *>::operator()() Line 2482	Objective-C++
 	CoreGraphics.dll!Z::ScopeExitFn<,__CGContext::awImage,unsigned char * const,long,ID2D1Image *>::~ScopeExitFn<,__CGContext::awImage,unsigned char * const,long,ID2D1Image *>() Line 2475	Objective-C++
 	CoreGraphics.dll!Z::ScopeExitFn<,__CGContext::awImage,unsigned char * const,long,ID2D1Image *>::`vbase destructor'() Line 2475	Objective-C++
 	CoreGraphics.dll!__CGContext::DrawImage(ID2D1Image * image) Line 2270	Objective-C++
 	CoreGraphics.dll!__CGContext::DrawGeometry(_CGCoordinateMode coordinateMode, ID2D1Geometry * pGeometry, long drawMode) Line 2304	Objective-C++
>	CoreGraphics.dll!CGContextFillRect(__CGContext * context, CGRect rect) Line 2352	Objective-C++
```

### PR DESCRIPTION
**Pull request by DHowett-MSFT**
This commit also switches our static initialization around to be less
likely to trigger the static init order fiasco.

Fixes #1895.

### CODE REVIEW

File: Frameworks/CoreGraphics/D2DWrapper.mm [hunk 1]
```diff
@@ -19,18 +19,32 @@
...
+namespace {
+template <typename T>
+struct HRComPtr {
+    HRESULT hr;
+    ComPtr<T> ptr;
+};
+}
+
 HRESULT _CGGetD2DFactory(ID2D1Factory** factory) {
-    static ComPtr<ID2D1Factory> sFactory;
```
Comment (DHowett-MSFT) [inline Frameworks/CoreGraphics/D2DWrapper.mm]: (there may have been an innate unsafeness here: I don't know if the static init order here is specified or if it's guaranteed that this `ComPtr` will construct before the static HRESULT is initialized.

File: Frameworks/CoreGraphics/D2DWrapper.mm [hunk 2]
```diff
@@ -19,18 +19,32 @@
 
 using namespace Microsoft::WRL;
 
+namespace {
+template <typename T>
```
Comment (aballway) [inline Frameworks/CoreGraphics/D2DWrapper.mm]: what's the advantage of doing this?

File: Frameworks/CoreGraphics/D2DWrapper.mm [hunk 3]
```diff
@@ -19,18 +19,32 @@
...
+};
+}
+
 HRESULT _CGGetD2DFactory(ID2D1Factory** factory) {
-    static ComPtr<ID2D1Factory> sFactory;
-    static HRESULT sHr = D2D1CreateFactory(D2D1_FACTORY_TYPE_SINGLE_THREADED, __uuidof(ID2D1Factory), &sFactory);
-    sFactory.CopyTo(factory);
-    RETURN_HR(sHr);
+    static auto sFactory = []() -> HRComPtr<ID2D1Factory> {
+        ComPtr<ID2D1Factory> factory;
```
Comment (msft-Jeyaram) [inline Frameworks/CoreGraphics/D2DWrapper.mm]: nit: naming confusion between the **factory vs factory

File: Frameworks/CoreGraphics/D2DWrapper.mm (hunk 2 above)
Comment (rajsesh-msft) [inline Frameworks/CoreGraphics/D2DWrapper.mm]: could get the same result by capturing factory reference into the lambda.

Comment (aballway) [inline Frameworks/CoreGraphics/D2DWrapper.mm]: IIRC you can't capture a static variable b/c of lifetime stuff

**Comment by DHowett-MSFT** [comment]
Gated on #1876.

**Comment by DHowett-MSFT** [comment]
Benchmarks: too noisy to tell, but the difference appears to be negligible.

image

image

**Comment by DHowett-MSFT** [comment]
The change is negligible. Comparing the median runtimes between tests, most changes were <1%. The few that weren't differed by a few hundred nanoseconds (3% at max).
