### PR TITLE
Fix CGImage's interpolation mode & fix some lingering TODOs

### LINKED ISSUE #2669: kCGInterpolationHigh not working?
In UIImage if I call the method below (which is the WINOBJC implementation but with the 3 ADD lines shown and method name change to my_* ) the image still does not interpolate very well when the CTM is scaled down (image made smaller). Is there something I am missing?

```objc
- (void)my_drawAtPoint:(CGPoint)point blendMode:(CGBlendMode)mode alpha:(float)alpha {
    CGContextRef cur = UIGraphicsGetCurrentContext();
    RETURN_IF(!cur);

    CGImageRef img = getImage(self);
    RETURN_IF(!img);

    CGContextSaveGState(cur);
    _CGContextPushBeginDraw(cur);

    auto popEnd = wil::ScopeExit([cur]() {
        _CGContextPopEndDraw(cur);
        CGContextRestoreGState(cur);
    });

    CGContextSetBlendMode(cur, mode);
    CGContextSetAlpha(cur, alpha);

    float img_height = CGImageGetHeight(img);
    float img_width = CGImageGetWidth(img);

    CGRect pos;
    pos.origin = point;
    pos.size.height = (img_height / _scale);
    pos.size.width = (img_width / _scale);

    // |1  0 0| is the transformation matrix for flipping a rect about its Y midpoint m. (m = (y + h/2))
    // |0 -1 0|
    // |0 2m 1|
    CGContextConcatCTM(cur, CGAffineTransformMake(1, 0, 0, -1, 0, 2 * (pos.origin.y + (pos.size.height / 2))));

    CGContextSetShouldAntialias(cur, YES); // ADD
    CGContextSetAllowsAntialiasing(cur, YES); // ADD
    CGContextSetInterpolationQuality(cur, kCGInterpolationHigh); // ADD

    CGContextDrawImage(cur, pos, img);
}
```

### PR DESCRIPTION
**Pull request by DHowett-MSFT**
This pull request removes `__CGImage::Impl`, the fluent API, and the copied code in all of the `CGImage*Copy*` APIs.

It also fixes #2669, which was caused by us not copying the interpolation mode when we converted an image into another pixel format.

I suggest you look at the two commits in isolation.

Tests are passing with interpolation results validated in CGCatalog.

### CODE REVIEW

File: Frameworks/CoreGraphics/CGImage.mm [hunk 1]
```diff
@@ -599,14 +578,17 @@ bool _CGIsValidRenderTargetPixelFormat(WICPixelFormatGUID pixelFormat) {
 HRESULT _CGImageGetWICImageSource(CGImageRef image, IWICBitmap** source) {
     RETURN_HR_IF_NULL(E_INVALIDARG, image);
     RETURN_HR_IF_NULL(E_POINTER, source);
-    return image->ImageSource().CopyTo(source);
+    IWICBitmap* copy = image->ImageSource();
```
Comment (aballway) [inline Frameworks/CoreGraphics/CGImage.mm]: nit: should make this method take **, return HRESULT

**Comment by msft-Jeyaram** [comment]
@DHowett-MSFT thank you for updating, given we started this at the start of the CPPbase helper era, the impl remained and now its gone 😂

**Comment by msft-Jeyaram** [comment]
@DHowett-MSFT codeflow does a bad job at comparing the commits :(

File: Frameworks/CoreGraphics/CGImage.mm (hunk 1 above)
Comment (DHowett-MSFT) [inline Frameworks/CoreGraphics/CGImage.mm]: oh i know. trust me i know.

Comment (DHowett-MSFT) [inline Frameworks/CoreGraphics/CGImage.mm]: my heart can only break so many times

File: Frameworks/CoreGraphics/CGImage.mm [hunk 2]
```diff
@@ -47,180 +47,175 @@ COREGRAPHICS_EXPORT void _CGImageAddDestructionListener(CGImageDestructionListen
...
+        RETURN_IF_FAILED(imageFactory->CreateBitmapFromSourceRect(bitmapSource.Get(), rect.origin.x, rect.origin.y, rect.size.width, rect.size.height, &newBitmap));
 
-    inline const __CGImagePixelProperties* Properties() const {
-        WICPixelFormatGUID pixelFormat = PixelFormat();
-        return _CGGetPixelFormatProperties(pixelFormat);
-    }
+        RETURN_IF_FAILED(SetImageSource(newBitmap.Get())); // also sets _colorSpace
+        _isMask = other._isMask;
+        _interpolate = other._interpolate;
+        _renderingIntent = other._renderingIntent;
```
Comment (msft-Jeyaram) [inline Frameworks/CoreGraphics/CGImage.mm]: hmmm i still feel reluctant about this, could we get a method like copy properties so everyone can use that.
This way a future developer who tries to manually copy over properties will not miss it.

File: Frameworks/CoreGraphics/CGImage.mm (hunk 1 above)
Comment (msft-Jeyaram) [inline Frameworks/CoreGraphics/CGImage.mm]: LOL the early early days of our lives

File: Frameworks/CoreGraphics/CGImage.mm [hunk 3]
```diff
@@ -269,7 +264,10 @@ CGImageRef CGImageCreate(size_t width,
         imageFactory->CreateBitmapFromMemory(width, height, pixelFormat, bytesPerRow, height * bytesPerRow, bytes, &image));
 
     CGImageRef imageRef = __CGImage::CreateInstance();
-    imageRef->SetImageSource(image).SetColorSpace(colorSpace).SetRenderingIntent(intent).SetInterpolate(shouldInterpolate);
+    RETURN_NULL_IF_FAILED(imageRef->SetImageSource(image.Get()));
+    imageRef->SetColorSpace(colorSpace);
+    imageRef->SetRenderingIntent(intent);
+    imageRef->SetInterpolate(shouldInterpolate);
```
Comment (rajsesh-msft) [inline Frameworks/CoreGraphics/CGImage.mm]: Thank you!

**Comment by DHowett-MSFT** [comment]
I would like to add some test collateral for interpolation. Ideally as well we would cache ore converted images across drawing operations so we don't have to convert to 32bpp every time. That would require our lock invalidation work to land, but it would help heavy image drawing perf.

**Comment by msft-Jeyaram** [comment]
@DHowett-MSFT  we were looking at improving the conversion path.
I wonder if windows <The apis we use supplied by windows> is being smart and internally caching them.
Even though we would end up getting a copy vs a reference.

**Comment by DHowett-MSFT** [comment]
tests now exist!

it turns out that all of our earlier "interpolation" tests _loaded the image and set shouldInterpolate=FALSE_ 😠

File: Frameworks/CoreGraphics/CGImage.mm [hunk 4]
```diff
@@ -63,7 +63,7 @@ COREGRAPHICS_EXPORT void _CGImageAddDestructionListener(CGImageDestructionListen
 
     // User-specified
     bool _isMask;
-    bool _interpolate;
+    bool _interpolate; // default: true
```
Comment (aballway) [inline Frameworks/CoreGraphics/CGImage.mm]: nit: can this just be `bool _interpolate = true;`?

File: Frameworks/CoreGraphics/CGImage.mm [hunk 5]
```diff
@@ -47,180 +47,175 @@ COREGRAPHICS_EXPORT void _CGImageAddDestructionListener(CGImageDestructionListen
...
+    size_t _height;
+    size_t _bitsPerPixel;
+    size_t _bitsPerComponent;
+    size_t _bytesPerRow;
+    CGBitmapInfo _bitmapInfo;
+    CGImageAlphaInfo _alphaInfo;
+
+    // User-specified
+    bool _isMask;
+    bool _interpolate; // default: true
```
Comment (aballway) [inline Frameworks/CoreGraphics/CGImage.mm]: nit: can this just be `bool _interpolate = true;`?

Comment (DHowett-MSFT) [inline Frameworks/CoreGraphics/CGImage.mm]: it could.
