### PR TITLE
Fix #955 by switching away from array literal syntax.

### LINKED ISSUE #955: AddressBook ModifyContactsTests Crashes Visual Studio Project
The ModifyContactsTests crashes Visual Studio when one of its tools tries to parse the file. The root cause still needs to be identified. Until this is fixed, the file will be disabled.

### PR DESCRIPTION
**Pull request by DHowett-MSFT**

### CODE REVIEW

File: tests/unittests/AddressBook/ModifyContactsTests.mm [hunk 1]
```diff
@@ -84,10 +84,6 @@ virtual void TearDown() {
     [dateComponents release];
 }
 
-// TODO: 955 AddressBook ModifyContactsTests Crashes Visual Studio Project #955
-// This test has been disabled due to an issue in Visual Studio attempting to parse the contents of this test.
```
Comment (pradipd) [inline tests/unittests/AddressBook/ModifyContactsTests.mm]: > Visual Studio attempting to parse the contents of this test [](start = 49, length = 60)

Have we contacted VS about this?  I'd hate to have to do this in every UT.

**Comment by memontic-ms** [comment]
:shipit:

**Comment by rajsesh-msft** [comment]
:shipit:
