### PR TITLE
Use custom font for stable version and copyright

### LINKED ISSUE #1798: CoreText CTFont/FontCopyName tests failing with recent Windows update
Copyright updated from 2015->2016, and Version 5.53->5.54

### PR DESCRIPTION
**Pull request by aballway**
Fixes #1798

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/winobjc/1799)

### CODE REVIEW

File: tests/unittests/CoreText/CTFontTests.mm [hunk 1]
```diff
@@ -17,8 +17,15 @@
...
 #import <CoreText/CoreText.h>
+#import <Starboard/SmartTypes.h>
 #import <vector>
 
+static NSURL* __GetURLFromPathRelativeToModuleDirectory(NSString* relativePath) {
+    static char fullPath[_MAX_PATH];
+    static int unused = [](char* path) { return GetModuleFileNameA(NULL, path, _MAX_PATH); }(fullPath);
+    return [NSURL fileURLWithPath:[[@(fullPath) stringByDeletingLastPathComponent] stringByAppendingPathComponent:relativePath]];
+}
+
```
Comment (rajsesh-msft) [inline tests/unittests/CoreText/CTFontTests.mm]: This will probably make @bbowman very unhappy.

File: tests/unittests/CoreText/CTFontTests.mm [hunk 2]
```diff
@@ -73,8 +72,7 @@ virtual void TearDown() {
 
 INSTANTIATE_TEST_CASE_P(CTFont,
                         FontCopyName,
-                        ::testing::Values(::testing::make_tuple(kCTFontCopyrightNameKey, c_copyrightName),
```
Comment (ms-jihua) [inline tests/unittests/CoreText/CTFontTests.mm]: confused why you took this approach - why not just swap out the constants above for the ones in WinObjC.ttf, and reuse this parameterized test instead of adding a new one?

Comment (ms-jihua) [inline tests/unittests/CoreText/CTFontTests.mm]: (if it's that WinObjC.ttf currently lacks these other metadata, is there a way we could add them to WinObjC.ttf?)

---
In reply to: [97684882](https://github.com/Microsoft/WinObjC/pull/1799#discussion_r97684882) [](ancestors = 97684882)

Comment (aballway) [inline tests/unittests/CoreText/CTFontTests.mm]: I'm not sure how difficult it would be to add the metadata, as that would make this much cleaner.  @DHowett-MSFT ?

**Comment by DHowett-MSFT** [comment]
@aballway we can make one explicitly for the purposes of containing metadata. that might be preferable to updating the WinObjC font in the ~4 places we have it copied.

File: tests/unittests/CoreText/CTFontTests.mm [hunk 3]
```diff
@@ -53,21 +59,23 @@ virtual void TearDown() {
...
 const NSString* c_designerName = nullptr;
 const NSString* c_descriptionName = nullptr;
-const NSString* c_vendorURLName = @"http://www.microsoft.com/typography/fonts/";
+const NSString* c_vendorURLName = @"https://developer.microsoft.com/en-us/windows/bridges/ios";
 const NSString* c_designerURLName = nullptr;
-const NSString* c_licenseURLName = @"http://www.microsoft.com/typography/fonts/";
+const NSString* c_licenseURLName = @"https://developer.microsoft.com/en-us/windows/bridges/ios";
 const NSString* c_sampleTextName = nullptr;
+const NSString* c_copyrightName = @"Copyright (c) Microsoft";
+const NSString* c_versionName = @"Version 1.01 ";
```
Comment (DHowett-MSFT) [inline tests/unittests/CoreText/CTFontTests.mm]: How strange that it leave a space at the end; I was even cautious to have it not do that.

File: tests/unittests/CoreText/CTFontTests.mm [hunk 4]
```diff
@@ -46,35 +59,28 @@ virtual void TearDown() {
...
 const NSString* c_manufacturerName = @"Microsoft Corporation";
 const NSString* c_designerName = nullptr;
 const NSString* c_descriptionName = nullptr;
-const NSString* c_vendorURLName = @"http://www.microsoft.com/typography/fonts/";
+const NSString* c_vendorURLName = @"https://developer.microsoft.com/en-us/windows/bridges/ios";
 const NSString* c_designerURLName = nullptr;
-const NSString* c_licenseURLName = @"http://www.microsoft.com/typography/fonts/";
+const NSString* c_licenseURLName = @"https://developer.microsoft.com/en-us/windows/bridges/ios";
 const NSString* c_sampleTextName = nullptr;
+const NSString* c_copyrightName = @"Copyright (c) Microsoft";
```
Comment (DHowett-MSFT) [inline tests/unittests/CoreText/CTFontTests.mm]: aww, these moved around w.r.t. the true original. the diff could look so much prettier if Version was below fullName and copyright was above familyName! :P

File: tests/unittests/CoreText/CTFontTests.mm [hunk 5]
```diff
@@ -46,35 +59,28 @@ virtual void TearDown() {
...
+const NSString* c_versionName = @"Version 1.01 ";
 const NSString* c_postscriptCIDName = nullptr;
 
 INSTANTIATE_TEST_CASE_P(CTFont,
                         FontCopyName,
-                        ::testing::Values(::testing::make_tuple(kCTFontCopyrightNameKey, c_copyrightName),
-                                          ::testing::make_tuple(kCTFontFamilyNameKey, c_familyName),
+                        ::testing::Values(::testing::make_tuple(kCTFontFamilyNameKey, c_familyName),
```
Comment (DHowett-MSFT) [inline tests/unittests/CoreText/CTFontTests.mm]: you could revert this to the original completely. no point in taking a diff on an unnecessary reorganization
