### PR TITLE
Disabling test that causes a crash in Visual Studio.

### LINKED ISSUE #955: AddressBook ModifyContactsTests Crashes Visual Studio Project
The ModifyContactsTests crashes Visual Studio when one of its tools tries to parse the file. The root cause still needs to be identified. Until this is fixed, the file will be disabled.

### PR DESCRIPTION
**Pull request by MSFTFox**
This test causes a crash when visual studio attempts to parse
the content of this test. It has been commented out.

### CODE REVIEW

**Comment by DHowett-MSFT** [comment]
:clock1:

**Comment by aballway** [comment]
:shipit:

**Comment by memontic-ms** [comment]
:shipit:

File: tests/unittests/AddressBook/ModifyContactsTests.mm [hunk 1]
```diff
@@ -84,6 +84,10 @@ virtual void TearDown() {
     [dateComponents release];
 }
 
+// TODO: 955 AddressBook ModifyContactsTests Crashes Visual Studio Project #955
```
Comment (DHowett-MSFT) [inline tests/unittests/AddressBook/ModifyContactsTests.mm]: > 955 AddressBook ModifyContactsTests Crashes Visual Studio Project #955 [](start = 8, length = 71)

why `955 #955`?

**Comment by DHowett-MSFT** [comment]
:shipit:

**Comment by bbowman** [comment]
Uh what? This doesn't seem like the correct solution. What about this test is crashing vs?
