### PR TITLE
Return false for tab stops in CTParagraphStyle

### LINKED ISSUE #1404: [CoreText] AV Crash in __CTParagraphStyle::SetValue with kCTParagraphStyleSpecifierTabStops specifier
WOCCatalog crashes with an AV on startup trying to set kCTParagraphStyleSpecifierTabStops. (CTParagraphStyle.mm@ln76)

Thanks AJ!

### PR DESCRIPTION
**Pull request by aballway**
CTParagraphStyleCreate would cause an issue when trying to set tab stops when none are present.  Since they are not supported just ignore any when creating for now.

Fixes #1404 

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/winobjc/1409)

### CODE REVIEW

File: Frameworks/CoreText/CTParagraphStyle.mm [hunk 1]
```diff
@@ -106,8 +106,8 @@ bool GetValue(CTParagraphStyleSpecifier specifier, size_t size, void* outValue)
         if (specifier <= kCTParagraphStyleSpecifierCount && outValue != nullptr && size == __CTParagraphStyleSizeTable[specifier]) {
             switch (specifier) {
                 case kCTParagraphStyleSpecifierTabStops:
```
Comment (aballway) [inline Frameworks/CoreText/CTParagraphStyle.mm]: I didn't think we supported tab stops before.

Comment (rajsesh-msft) [inline Frameworks/CoreText/CTParagraphStyle.mm]: okay.  If we have sample code that is using it, we should remove it.

---
In reply to: [88520384](https://github.com/Microsoft/WinObjC/pull/1409#discussion_r88520384) [](ancestors = 88520384)

**Comment by rajsesh-msft** [comment]
:shipit:
