### PR TITLE
Fix spelling in status

### LINKED ISSUE #2664: NSKeyValueCoding.mm(604,18): Invalid @status specified: interopertable
Build break in ApiAnalyzer.

### PR DESCRIPTION
**Pull request by aballway**
Fixes #2664

### CODE REVIEW

File: Frameworks/Foundation/NSKeyValueCoding.mm [hunk 1]
```diff
@@ -599,7 +599,7 @@ - (NSMutableSet*)mutableSetValueForKey:(NSString*)key {
 }
 
 /**
- @Status Interopertable
+ @Status Interoperable
```
Comment (pradipd) [inline Frameworks/Foundation/NSKeyValueCoding.mm]: Passed spellcheck!
