### PR TITLE
Fix CoreText Drawing

### LINKED ISSUE #1290: [NSString drawInRect] incorrectly positions the y origin of lines that contain accents or punctuation such as apostrophies
NSString drawInRect is used by Cocos2D to create text textures, so open GL games using cocos2D or apps using NSString drawInRect will draw the lines incorrectly.

### PR DESCRIPTION
**Pull request by aballway**
It seems our drawing implementation was overcomplicated, doing unnecessary transformations which made assumptions about the state of the context which were not always true.  Removes now unnecessary private drawing functions and removes ascent as well as simplifying CGContextDrawGlyphRun.

This *should* be the last change we need for drawing

Fixes #1290

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/winobjc/1297)

### CODE REVIEW

File: Frameworks/CoreGraphics/CGContext.mm [hunk 1]
```diff
@@ -1239,8 +1239,8 @@ bool CGContextIsPointInPath(CGContextRef c, bool eoFill, CGFloat x, CGFloat y) {
     return c->Backing()->CGContextIsPointInPath(eoFill, x, y);
 }
 
-void CGContextDrawGlyphRun(CGContextRef ctx, const DWRITE_GLYPH_RUN* glyphRun, float lineAscent) {
-    ctx->Backing()->CGContextDrawGlyphRun(glyphRun, lineAscent);
+void CGContextDrawGlyphRun(CGContextRef ctx, const DWRITE_GLYPH_RUN* glyphRun) {
```
Comment (aballway) [inline Frameworks/CoreGraphics/CGContext.mm]: #1301

File: Frameworks/CoreGraphics/CGContextCairo.mm [hunk 2]
```diff
@@ -1853,34 +1853,25 @@
...
+    // All of which are rolled into one concatenation
     float height = _imgDest->Backing()->Height();
     CGAffineTransform userTransform =
-        CGAffineTransformConcat(curState->curTransform, CGAffineTransformMake(1.0f / _scale, 0, 0, 1.0f / _scale, 0, -height / _scale));
-
-    // Apply the context CTM to get total matrix
-    transform = CGAffineTransformConcat(transform, userTransform);
+        CGAffineTransformConcat(curState->curTransform, CGAffineTransformMake(1.0f / _scale, 0, 0, -1.0f / _scale, 0, height / _scale));
 
-    // Perform anti-clockwise rotation required to match the reference platform.
```
Comment (ms-jihua) [inline Frameworks/CoreGraphics/CGContextCairo.mm]: are we still respecting this? (do we rotate in the wrong orientation now?)

**Comment by ms-jihua** [comment]
:shipit:

**Comment by bbowman** [comment]
:shipit:
